export type Lang = 'hi-IN' | 'mr-IN' | 'en-IN'

type Str = Record<Lang, string>
type StrFn1 = Record<Lang, (a: string | number) => string>

function pick<T>(obj: Record<Lang, T>, lang: Lang): T {
  return obj[lang] ?? obj['en-IN']
}

// Helper: get a plain string for the current language
export function g(obj: Str, lang: Lang): string {
  return obj[lang] ?? obj['en-IN'] ?? ''
}

// Helper: get + call a templated string for the current language
export function gf(obj: StrFn1, lang: Lang, arg: string | number): string {
  const fn = obj[lang] ?? obj['en-IN']
  return fn ? fn(arg) : ''
}

export const S = {
  // ── FULL MODE ─────────────────────────────────────────────
  full: {
    brandTag: { 'hi-IN': 'सरकारी योजना खोजक', 'mr-IN': 'सरकारी योजना शोधक', 'en-IN': 'GOVERNMENT SCHEME FINDER' } as Str,
    farmerMaharashtra: { 'hi-IN': 'किसान · महाराष्ट्र', 'mr-IN': 'शेतकरी · महाराष्ट्र', 'en-IN': 'Farmer · Maharashtra' } as Str,

    navSchemes: { 'hi-IN': 'योजना खोज', 'mr-IN': 'योजना शोध', 'en-IN': 'Scheme Search' } as Str,
    navCompare: { 'hi-IN': 'योजनाओं की तुलना', 'mr-IN': 'योजनांची तुलना', 'en-IN': 'Compare Schemes' } as Str,
    navPrep: { 'hi-IN': 'आवेदन तैयारी', 'mr-IN': 'अर्ज तयारी', 'en-IN': 'Application Prep' } as Str,
    navTracker: { 'hi-IN': 'आवेदन ट्रैकर', 'mr-IN': 'अर्ज ट्रॅकर', 'en-IN': 'Application Tracker' } as Str,
    navCSC: { 'hi-IN': 'CSC खोजें', 'mr-IN': 'CSC शोधा', 'en-IN': 'CSC Locator' } as Str,
    navHelpline: { 'hi-IN': 'हेल्पलाइन', 'mr-IN': 'हेल्पलाइन', 'en-IN': 'Helpline' } as Str,
    navMain: { 'hi-IN': 'मुख्य', 'mr-IN': 'मुख्य', 'en-IN': 'MAIN' } as Str,

    searchLabel: { 'hi-IN': 'अपनी स्थिति बताएं', 'mr-IN': 'तुमची परिस्थिती सांगा', 'en-IN': 'Describe Your Situation' } as Str,
    searchPlaceholder: { 'hi-IN': 'मैं 45 साल का किसान हूँ...', 'mr-IN': 'मी 45 वर्षांचा शेतकरी आहे...', 'en-IN': 'I am a 45 year old farmer from Maharashtra...' } as Str,
    searchBtn: { 'hi-IN': 'खोजें', 'mr-IN': 'शोधा', 'en-IN': 'Search' } as Str,
    showingAll: { 'hi-IN': (n) => `सभी ${n} योजनाएं दिखाई जा रही हैं`, 'mr-IN': (n) => `सर्व ${n} योजना दाखवत आहे`, 'en-IN': (n) => `Showing all ${n} schemes` } as StrFn1,
    schemesFound: { 'hi-IN': (n) => `${n} योजनाएं मिलीं`, 'mr-IN': (n) => `${n} योजना सापडल्या`, 'en-IN': (n) => `${n} schemes found` } as StrFn1,
    filterState: { 'hi-IN': 'राज्य: महाराष्ट्र', 'mr-IN': 'राज्य: महाराष्ट्र', 'en-IN': 'State: Maharashtra' } as Str,
    filterAge: { 'hi-IN': 'आयु: 45', 'mr-IN': 'वय: 45', 'en-IN': 'Age: 45' } as Str,
    filterOccupation: { 'hi-IN': 'व्यवसाय: किसान', 'mr-IN': 'व्यवसाय: शेतकरी', 'en-IN': 'Occupation: Farmer' } as Str,
    filterIncome: { 'hi-IN': 'आय: कम', 'mr-IN': 'उत्पन्न: कमी', 'en-IN': 'Income: Low' } as Str,

    bestMatch: { 'hi-IN': 'सर्वश्रेष्ठ मिलान', 'mr-IN': 'सर्वोत्तम जुळणी', 'en-IN': 'Best Match' } as Str,
    highestBenefit: { 'hi-IN': 'सर्वाधिक लाभ', 'mr-IN': 'सर्वाधिक लाभ', 'en-IN': 'Highest Benefit' } as Str,
    easiest: { 'hi-IN': 'सबसे आसान', 'mr-IN': 'सर्वात सोपे', 'en-IN': 'Easiest' } as Str,

    eligible: { 'hi-IN': '✓ पात्र', 'mr-IN': '✓ पात्र', 'en-IN': '✓ Eligible' } as Str,
    partial: { 'hi-IN': '⚠ आंशिक', 'mr-IN': '⚠ आंशिक', 'en-IN': '⚠ Partial' } as Str,
    ineligible: { 'hi-IN': '✗ अपात्र', 'mr-IN': '✗ अपात्र', 'en-IN': '✗ Ineligible' } as Str,
    highMatch: { 'hi-IN': 'उच्च मिलान', 'mr-IN': 'उच्च जुळणी', 'en-IN': 'High Match' } as Str,
    partialMatch: { 'hi-IN': 'आंशिक मिलान', 'mr-IN': 'आंशिक जुळणी', 'en-IN': 'Partial Match' } as Str,
    matchPercent: { 'hi-IN': (n) => `${n}% मिलान`, 'mr-IN': (n) => `${n}% जुळणी`, 'en-IN': (n) => `${n}% match` } as StrFn1,
    viewDetails: { 'hi-IN': 'विवरण देखें', 'mr-IN': 'तपशील पहा', 'en-IN': 'View Details' } as Str,
    fixArrow: { 'hi-IN': 'समाधान →', 'mr-IN': 'उपाय →', 'en-IN': 'Fix →' } as Str,

    eligibilityCheck: { 'hi-IN': 'पात्रता जाँच', 'mr-IN': 'पात्रता तपासणी', 'en-IN': 'Eligibility Check' } as Str,
    rejectionRisks: { 'hi-IN': 'अस्वीकृति के जोखिम', 'mr-IN': 'नकार जोखीम', 'en-IN': 'Rejection Risks' } as Str,
    howToApply: { 'hi-IN': 'आवेदन कैसे करें', 'mr-IN': 'अर्ज कसा करावा', 'en-IN': 'How to Apply' } as Str,
    docsRequired: { 'hi-IN': 'आवश्यक दस्तावेज़', 'mr-IN': 'आवश्यक कागदपत्रे', 'en-IN': 'Documents Required' } as Str,

    eligRow1: { 'hi-IN': 'ज़मीन का स्वामित्व सत्यापित', 'mr-IN': 'जमीन मालकी सत्यापित', 'en-IN': 'Land holding verified' } as Str,
    eligRow2: { 'hi-IN': 'व्यवसाय और राज्य पुष्टि', 'mr-IN': 'व्यवसाय आणि राज्य पुष्टी', 'en-IN': 'Occupation and state confirmed' } as Str,
    eligRow3: { 'hi-IN': 'आय पात्रता सीमा के भीतर', 'mr-IN': 'उत्पन्न पात्रता मर्यादेत', 'en-IN': 'Income within eligibility limit' } as Str,
    eligRow4: { 'hi-IN': 'सभी मानदंड पूरे', 'mr-IN': 'सर्व निकष पूर्ण', 'en-IN': 'All criteria met' } as Str,
    eligRow4Partial: { 'hi-IN': 'कुछ मानदंडों की पुष्टि बाकी', 'mr-IN': 'काही निकषांची पडताळणी बाकी', 'en-IN': 'Some criteria need verification' } as Str,

    modeOnline: { 'hi-IN': 'ऑनलाइन', 'mr-IN': 'ऑनलाइन', 'en-IN': 'online' } as Str,
    modeOffline: { 'hi-IN': 'ऑफलाइन', 'mr-IN': 'ऑफलाइन', 'en-IN': 'offline' } as Str,
    modeCSC: { 'hi-IN': 'CSC', 'mr-IN': 'CSC', 'en-IN': 'csc' } as Str,

    annual: { 'hi-IN': 'सालाना', 'mr-IN': 'वार्षिक', 'en-IN': 'Annual' } as Str,
    installments: { 'hi-IN': 'किस्तें', 'mr-IN': 'हप्ते', 'en-IN': 'Installments' } as Str,
    payments: { 'hi-IN': 'भुगतान', 'mr-IN': 'देयके', 'en-IN': 'Payments' } as Str,
    direct: { 'hi-IN': 'सीधे', 'mr-IN': 'थेट', 'en-IN': 'Direct' } as Str,
    bankTransfer: { 'hi-IN': 'बैंक ट्रांसफर', 'mr-IN': 'बँक हस्तांतरण', 'en-IN': 'Bank Transfer' } as Str,

    generateDoc: { 'hi-IN': '📋 तैयारी दस्तावेज़ बनाएं', 'mr-IN': '📋 तयारी दस्तऐवज बनवा', 'en-IN': '📋 Generate Preparation Doc' } as Str,
    saveScheme: { 'hi-IN': '⭐ योजना सहेजें', 'mr-IN': '⭐ योजना जतन करा', 'en-IN': '⭐ Save Scheme' } as Str,
    schemeSaved: { 'hi-IN': '✓ योजना सहेजी गई', 'mr-IN': '✓ योजना जतन केली', 'en-IN': '✓ Scheme Saved' } as Str,
    shareWA: { 'hi-IN': '💬 WhatsApp पर भेजें', 'mr-IN': '💬 WhatsApp वर पाठवा', 'en-IN': '💬 Share via WhatsApp' } as Str,
    officialSite: { 'hi-IN': '🔗 आधिकारिक वेबसाइट →', 'mr-IN': '🔗 अधिकृत वेबसाइट →', 'en-IN': '🔗 Official Website →' } as Str,

    comparing: { 'hi-IN': 'तुलना कर रहे हैं:', 'mr-IN': 'तुलना करत आहे:', 'en-IN': 'Comparing:' } as Str,
    compareNow: { 'hi-IN': 'अभी तुलना करें →', 'mr-IN': 'आता तुलना करा →', 'en-IN': 'Compare Now →' } as Str,
    clearAll: { 'hi-IN': 'सब हटाएं', 'mr-IN': 'सर्व काढा', 'en-IN': 'Clear all' } as Str,
    maxCompare: { 'hi-IN': 'अधिकतम 3 योजनाओं की तुलना की जा सकती है', 'mr-IN': 'जास्तीत जास्त 3 योजनांची तुलना करता येते', 'en-IN': 'Maximum 3 schemes can be compared' } as Str,

    noSchemesCompare: { 'hi-IN': 'तुलना के लिए कोई योजना नहीं चुनी गई', 'mr-IN': 'तुलनेसाठी कोणतीही योजना निवडली नाही', 'en-IN': 'No schemes selected for comparison' } as Str,
    compareHint: { 'hi-IN': 'योजना खोज में जाएं और किसी भी कार्ड पर +C बटन दबाएं। 3 योजनाओं तक तुलना करें।', 'mr-IN': 'योजना शोधमध्ये जा आणि कोणत्याही कार्डवर +C दाबा. 3 योजनांपर्यंत तुलना करा.', 'en-IN': 'Go to Scheme Search and click +C button on any card. Compare up to 3 schemes.' } as Str,
    goToSearch: { 'hi-IN': '← योजना खोज पर जाएं', 'mr-IN': '← योजना शोधावर जा', 'en-IN': '← Go to Scheme Search' } as Str,
    startPrep: { 'hi-IN': 'तैयारी शुरू करें →', 'mr-IN': 'तयारी सुरू करा →', 'en-IN': 'Start Preparation →' } as Str,
    compareCol: { 'hi-IN': 'तुलना', 'mr-IN': 'तुलना', 'en-IN': 'Compare' } as Str,

    cmpEligibility: { 'hi-IN': 'पात्रता', 'mr-IN': 'पात्रता', 'en-IN': 'Eligibility' } as Str,
    cmpMatchScore: { 'hi-IN': 'मिलान स्कोर', 'mr-IN': 'जुळणी स्कोअर', 'en-IN': 'Match Score' } as Str,
    cmpBenefit: { 'hi-IN': 'लाभ राशि', 'mr-IN': 'लाभाची रक्कम', 'en-IN': 'Benefit Amount' } as Str,
    cmpHowApply: { 'hi-IN': 'आवेदन कैसे करें', 'mr-IN': 'अर्ज कसा करावा', 'en-IN': 'How to Apply' } as Str,
    cmpDocuments: { 'hi-IN': 'दस्तावेज़', 'mr-IN': 'कागदपत्रे', 'en-IN': 'Documents' } as Str,
    cmpProcessing: { 'hi-IN': 'प्रसंस्करण समय', 'mr-IN': 'प्रक्रिया वेळ', 'en-IN': 'Processing Time' } as Str,
    cmpRejection: { 'hi-IN': 'अस्वीकृति जोखिम', 'mr-IN': 'नकार जोखीम', 'en-IN': 'Rejection Risk' } as Str,
    cmpRecommended: { 'hi-IN': 'अनुशंसित', 'mr-IN': 'शिफारस केलेले', 'en-IN': 'Recommended' } as Str,
    cmpAction: { 'hi-IN': 'कार्रवाई', 'mr-IN': 'कृती', 'en-IN': 'Action' } as Str,
    cmpStartHere: { 'hi-IN': '✓ यहाँ से शुरू करें', 'mr-IN': '✓ येथून सुरू करा', 'en-IN': '✓ Start Here' } as Str,
    cmpApplyNth: { 'hi-IN': (n) => `${n}. आवेदन करें`, 'mr-IN': (n) => `${n}. अर्ज करा`, 'en-IN': (n) => `Apply ${n}` } as StrFn1,
    cmpDocsCount: { 'hi-IN': (n) => `${n} दस्तावेज़`, 'mr-IN': (n) => `${n} कागदपत्रे`, 'en-IN': (n) => `${n} documents` } as StrFn1,
    lowRisk: { 'hi-IN': 'कम', 'mr-IN': 'कमी', 'en-IN': 'Low' } as Str,
    mediumRisk: { 'hi-IN': 'मध्यम', 'mr-IN': 'मध्यम', 'en-IN': 'Medium' } as Str,
    highRisk: { 'hi-IN': 'उच्च', 'mr-IN': 'उच्च', 'en-IN': 'High' } as Str,

    prepSubHead: { 'hi-IN': 'अपनी जानकारी भरें', 'mr-IN': 'तुमची माहिती भरा', 'en-IN': 'Create Your Profile' } as Str,
    prepSubDesc: { 'hi-IN': 'व्यक्तिगत आवेदन दस्तावेज़ बनाने के लिए हमें आपकी बुनियादी जानकारी चाहिए। इसमें 2 मिनट से कम समय लगेगा।', 'mr-IN': 'वैयक्तिक अर्ज दस्तऐवज तयार करण्यासाठी आम्हाला तुमची मूलभूत माहिती हवी आहे. यासाठी 2 मिनिटांपेक्षा कमी वेळ लागेल.', 'en-IN': 'To generate a personalised application document, we need your basic details. This takes less than 2 minutes.' } as Str,
    weNeed: { 'hi-IN': 'हमें चाहिए: ', 'mr-IN': 'आम्हाला हवे: ', 'en-IN': 'We need: ' } as Str,
    fillAndGenerate: { 'hi-IN': 'भरें और दस्तावेज़ बनाएं →', 'mr-IN': 'भरा आणि दस्तऐवज बनवा →', 'en-IN': 'Fill Details and Generate →' } as Str,
    useDemo: { 'hi-IN': 'डेमो प्रोफ़ाइल उपयोग करें (राजेश पाटिल — किसान)', 'mr-IN': 'डेमो प्रोफाइल वापरा (राजेश पाटील — शेतकरी)', 'en-IN': 'Use Demo Profile (Rajesh Patil — Farmer)' } as Str,

    trackerTitle: { 'hi-IN': 'आवेदन ट्रैकर', 'mr-IN': 'अर्ज ट्रॅकर', 'en-IN': 'Application Tracker' } as Str,
    trackerSub: { 'hi-IN': 'अपने आवेदनों की स्थिति देखें', 'mr-IN': 'तुमच्या अर्जांची स्थिती पहा', 'en-IN': 'Track status of your applications' } as Str,
    filterAll: { 'hi-IN': 'सभी', 'mr-IN': 'सर्व', 'en-IN': 'All' } as Str,
    filterPending: { 'hi-IN': 'लंबित', 'mr-IN': 'प्रलंबित', 'en-IN': 'Pending' } as Str,
    filterApproved: { 'hi-IN': 'स्वीकृत', 'mr-IN': 'मंजूर', 'en-IN': 'Approved' } as Str,
    filterAction: { 'hi-IN': 'कार्रवाई ज़रूरी', 'mr-IN': 'कृती आवश्यक', 'en-IN': 'Action Needed' } as Str,
    stepApplied: { 'hi-IN': 'आवेदन किया', 'mr-IN': 'अर्ज केला', 'en-IN': 'Applied' } as Str,
    stepReview: { 'hi-IN': 'समीक्षा में', 'mr-IN': 'समीक्षेत', 'en-IN': 'Under Review' } as Str,
    stepVerified: { 'hi-IN': 'सत्यापित', 'mr-IN': 'सत्यापित', 'en-IN': 'Verified' } as Str,
    stepDisbursed: { 'hi-IN': 'वितरित', 'mr-IN': 'वितरित', 'en-IN': 'Disbursed' } as Str,
    statusApproved: { 'hi-IN': '✓ स्वीकृत', 'mr-IN': '✓ मंजूर', 'en-IN': '✓ APPROVED' } as Str,
    statusDocs: { 'hi-IN': '⚠ दस्तावेज़ चाहिए', 'mr-IN': '⚠ कागदपत्रे हवीत', 'en-IN': '⚠ DOCS NEEDED' } as Str,
    statusPending: { 'hi-IN': '⏳ लंबित', 'mr-IN': '⏳ प्रलंबित', 'en-IN': '⏳ PENDING' } as Str,
    statusRejected: { 'hi-IN': '✗ अस्वीकृत', 'mr-IN': '✗ नाकारले', 'en-IN': '✗ REJECTED' } as Str,
    noRefYet: { 'hi-IN': 'अभी कोई संदर्भ नंबर नहीं', 'mr-IN': 'अद्याप संदर्भ क्रमांक नाही', 'en-IN': 'No reference number yet' } as Str,
    updateBtn: { 'hi-IN': 'अपडेट करें', 'mr-IN': 'अपडेट करा', 'en-IN': 'Update' } as Str,
    findCSCArrow: { 'hi-IN': 'CSC खोजें →', 'mr-IN': 'CSC शोधा →', 'en-IN': 'Find CSC →' } as Str,
    shareCheck: { 'hi-IN': 'भेजें ✓', 'mr-IN': 'पाठवा ✓', 'en-IN': 'Share ✓' } as Str,
    approvedShare: { 'hi-IN': (name) => `${name} — आवेदन स्वीकृत!`, 'mr-IN': (name) => `${name} — अर्ज मंजूर!`, 'en-IN': (name) => `${name} — Application APPROVED!` } as StrFn1,

    cscTitle: { 'hi-IN': 'CSC लोकेटर', 'mr-IN': 'CSC लोकेटर', 'en-IN': 'CSC Locator' } as Str,
    cscSearchPlaceholder: { 'hi-IN': 'क्षेत्र या पिनकोड से खोजें...', 'mr-IN': 'क्षेत्र किंवा पिनकोडने शोधा...', 'en-IN': 'Search by area or pincode...' } as Str,
    cscOpen: { 'hi-IN': 'खुला', 'mr-IN': 'उघडे', 'en-IN': 'Open' } as Str,
    cscClosed: { 'hi-IN': 'बंद', 'mr-IN': 'बंद', 'en-IN': 'Closed' } as Str,
    directions: { 'hi-IN': '📍 रास्ता', 'mr-IN': '📍 दिशा', 'en-IN': '📍 Directions' } as Str,
    callBtn: { 'hi-IN': '📞 कॉल', 'mr-IN': '📞 कॉल', 'en-IN': '📞 Call' } as Str,
    waBtn: { 'hi-IN': '💬 WhatsApp', 'mr-IN': '💬 WhatsApp', 'en-IN': '💬 WhatsApp' } as Str,
    waHelpText: { 'hi-IN': 'मुझे सरकारी योजना आवेदन में मदद चाहिए', 'mr-IN': 'मला सरकारी योजना अर्जासाठी मदत हवी आहे', 'en-IN': 'I need help with government scheme application' } as Str,
    openInMaps: { 'hi-IN': 'Google Maps में खोलें', 'mr-IN': 'Google Maps मध्ये उघडा', 'en-IN': 'Open in Google Maps' } as Str,
    mapsHint: { 'hi-IN': 'अपने वर्तमान स्थान के पास सभी CSC केंद्र खोजने के लिए नीचे बटन दबाएं।', 'mr-IN': 'तुमच्या सध्याच्या स्थानाजवळील सर्व CSC केंद्रे शोधण्यासाठी खालील बटण दाबा.', 'en-IN': 'Click button below to find all CSC centres near your current location on Google Maps.' } as Str,
    openMaps: { 'hi-IN': '📍 नज़दीकी CSC केंद्र खोजें →', 'mr-IN': '📍 जवळचे CSC केंद्र शोधा →', 'en-IN': '📍 Find CSC Centres Near Me →' } as Str,
    mapsAltHint: { 'hi-IN': 'या क्षेत्र या पिनकोड से खोजने के लिए बाईं ओर की सूची का उपयोग करें।', 'mr-IN': 'किंवा क्षेत्र किंवा पिनकोडने शोधण्यासाठी डावीकडील यादी वापरा.', 'en-IN': 'Or use list on the left to find by area or pincode.' } as Str,

    helplineTitle: { 'hi-IN': 'सरकारी हेल्पलाइन', 'mr-IN': 'सरकारी हेल्पलाइन', 'en-IN': 'Government Helplines' } as Str,
    helplineSub: { 'hi-IN': 'सभी केंद्र सरकार योजनाओं के लिए आधिकारिक संपर्क नंबर', 'mr-IN': 'सर्व केंद्र सरकार योजनांसाठी अधिकृत संपर्क क्रमांक', 'en-IN': 'Official contact numbers for all central government schemes' } as Str,
    callNow: { 'hi-IN': '📞 अभी कॉल करें', 'mr-IN': '📞 आता कॉल करा', 'en-IN': '📞 Call Now' } as Str,

    backHome: { 'hi-IN': 'होम पर वापस जाएं', 'mr-IN': 'मुख्यपृष्ठावर परत जा', 'en-IN': 'Back to Home' } as Str,
    loginSave: { 'hi-IN': 'लॉगिन / प्रोफ़ाइल सहेजें', 'mr-IN': 'लॉगिन / प्रोफाइल जतन करा', 'en-IN': 'Login / Save Profile' } as Str,
    profileSaved: { 'hi-IN': (n) => `✓ ${n} की प्रोफ़ाइल`, 'mr-IN': (n) => `✓ ${n} ची प्रोफाइल`, 'en-IN': (n) => `✓ ${n}'s Profile` } as StrFn1,
    profileSavedAlert: { 'hi-IN': 'प्रोफ़ाइल सहेजी गई!', 'mr-IN': 'प्रोफाइल जतन केली!', 'en-IN': 'Profile saved!' } as Str,
    simpleMode: { 'hi-IN': 'सरल', 'mr-IN': 'सोपे', 'en-IN': 'Simple' } as Str,
    fullMode: { 'hi-IN': 'फुल मोड', 'mr-IN': 'फुल मोड', 'en-IN': 'Full Mode' } as Str,

    panelTitles: {
      schemes: { 'hi-IN': 'योजना खोज', 'mr-IN': 'योजना शोध', 'en-IN': 'Scheme Search' } as Str,
      compare: { 'hi-IN': 'योजनाओं की तुलना', 'mr-IN': 'योजनांची तुलना', 'en-IN': 'Compare Schemes' } as Str,
      prep: { 'hi-IN': 'आवेदन तैयारी', 'mr-IN': 'अर्ज तयारी', 'en-IN': 'Application Preparation' } as Str,
      tracker: { 'hi-IN': 'आवेदन ट्रैकर', 'mr-IN': 'अर्ज ट्रॅकर', 'en-IN': 'Application Tracker' } as Str,
      csc: { 'hi-IN': 'CSC लोकेटर', 'mr-IN': 'CSC लोकेटर', 'en-IN': 'CSC Locator' } as Str,
      helpline: { 'hi-IN': 'हेल्पलाइन', 'mr-IN': 'हेल्पलाइन', 'en-IN': 'Helplines' } as Str,
    },
    panelSubs: {
      schemes: { 'hi-IN': 'सक्रिय', 'mr-IN': 'सक्रिय', 'en-IN': 'Active' } as Str,
      tracker: { 'hi-IN': 'आवेदन', 'mr-IN': 'अर्ज', 'en-IN': 'applications' } as Str,
      csc: { 'hi-IN': 'पुणे, महाराष्ट्र के पास', 'mr-IN': 'पुणे, महाराष्ट्र जवळ', 'en-IN': 'Near Pune, Maharashtra' } as Str,
      helpline: { 'hi-IN': 'अखिल भारत', 'mr-IN': 'संपूर्ण भारत', 'en-IN': 'All India' } as Str,
      compare: { 'hi-IN': (n: number) => `${n} योजनाएं चुनी गईं`, 'mr-IN': (n: number) => `${n} योजना निवडल्या`, 'en-IN': (n: number) => `${n} schemes selected` } as StrFn1,
    },

    labelName: { 'hi-IN': 'पूरा नाम', 'mr-IN': 'पूर्ण नाव', 'en-IN': 'Full Name' } as Str,
    labelAge: { 'hi-IN': 'आयु', 'mr-IN': 'वय', 'en-IN': 'Age' } as Str,
    labelState: { 'hi-IN': 'राज्य', 'mr-IN': 'राज्य', 'en-IN': 'State' } as Str,
    labelOccupation: { 'hi-IN': 'व्यवसाय', 'mr-IN': 'व्यवसाय', 'en-IN': 'Occupation' } as Str,
    labelIncome: { 'hi-IN': 'वार्षिक आय', 'mr-IN': 'वार्षिक उत्पन्न', 'en-IN': 'Annual Income' } as Str,
    labelLand: { 'hi-IN': 'ज़मीन का आकार', 'mr-IN': 'जमिनीचा आकार', 'en-IN': 'Land Size' } as Str,

    // Application Preparation Form (scheme-specific sample application)
    labelGender: { 'hi-IN': 'लिंग', 'mr-IN': 'लिंग', 'en-IN': 'Gender' } as Str,
    labelDistrict: { 'hi-IN': 'ज़िला', 'mr-IN': 'जिल्हा', 'en-IN': 'District' } as Str,
    labelMobile: { 'hi-IN': 'मोबाइल नंबर', 'mr-IN': 'मोबाइल क्रमांक', 'en-IN': 'Mobile Number' } as Str,
    labelAadhaarBankLinked: { 'hi-IN': 'आधार-बैंक लिंक स्थिति', 'mr-IN': 'आधार-बँक लिंक स्थिती', 'en-IN': 'Aadhaar-Linked Bank Status' } as Str,
    labelFarmerCategory: { 'hi-IN': 'किसान श्रेणी', 'mr-IN': 'शेतकरी प्रवर्ग', 'en-IN': 'Farmer Category' } as Str,
    labelLandOwnership: { 'hi-IN': 'ज़मीन स्वामित्व स्थिति', 'mr-IN': 'जमीन मालकी स्थिती', 'en-IN': 'Land Ownership Status' } as Str,
    labelLandArea: { 'hi-IN': 'ज़मीन का क्षेत्रफल (एकड़ में)', 'mr-IN': 'जमिनीचे क्षेत्रफळ (एकरमध्ये)', 'en-IN': 'Land Area (in acres)' } as Str,
    labelSurveyNumber: { 'hi-IN': 'सर्वे / गट नंबर', 'mr-IN': 'सर्वे / गट क्रमांक', 'en-IN': 'Survey / Gat Number' } as Str,
    labelBankName: { 'hi-IN': 'बैंक का नाम', 'mr-IN': 'बँकेचे नाव', 'en-IN': 'Bank Name' } as Str,
    labelAccountNumber: { 'hi-IN': 'खाता संख्या', 'mr-IN': 'खाते क्रमांक', 'en-IN': 'Account Number' } as Str,
    labelIfsc: { 'hi-IN': 'IFSC कोड', 'mr-IN': 'IFSC कोड', 'en-IN': 'IFSC Code' } as Str,

    genderMale: { 'hi-IN': 'पुरुष', 'mr-IN': 'पुरुष', 'en-IN': 'Male' } as Str,
    genderFemale: { 'hi-IN': 'महिला', 'mr-IN': 'महिला', 'en-IN': 'Female' } as Str,
    genderOther: { 'hi-IN': 'अन्य', 'mr-IN': 'इतर', 'en-IN': 'Other' } as Str,

    farmerCategoryMarginal: { 'hi-IN': 'सीमांत किसान (1 हेक्टेयर से कम)', 'mr-IN': 'सीमांत शेतकरी (1 हेक्टरपेक्षा कमी)', 'en-IN': 'Marginal Farmer (below 1 hectare)' } as Str,
    farmerCategorySmall: { 'hi-IN': 'लघु किसान (1–2 हेक्टेयर)', 'mr-IN': 'अल्पभूधारक शेतकरी (1–2 हेक्टर)', 'en-IN': 'Small Farmer (1–2 hectares)' } as Str,
    farmerCategoryOther: { 'hi-IN': 'अन्य किसान (2 हेक्टेयर से अधिक)', 'mr-IN': 'इतर शेतकरी (2 हेक्टरपेक्षा जास्त)', 'en-IN': 'Other Farmer (above 2 hectares)' } as Str,

    landOwnershipOwned: { 'hi-IN': 'स्वयं के स्वामित्व में', 'mr-IN': 'स्वतःच्या मालकीची', 'en-IN': 'Owned' } as Str,
    landOwnershipJoint: { 'hi-IN': 'संयुक्त स्वामित्व', 'mr-IN': 'संयुक्त मालकी', 'en-IN': 'Joint Ownership' } as Str,
    landOwnershipLeased: { 'hi-IN': 'पट्टे पर ली गई', 'mr-IN': 'भाड्याने घेतलेली', 'en-IN': 'Leased' } as Str,

    yesOption: { 'hi-IN': 'हाँ', 'mr-IN': 'हो', 'en-IN': 'Yes' } as Str,
    noOption: { 'hi-IN': 'नहीं', 'mr-IN': 'नाही', 'en-IN': 'No' } as Str,
    selectPlaceholder: { 'hi-IN': 'चुनें', 'mr-IN': 'निवडा', 'en-IN': 'Select' } as Str,

    formSectionPersonal: { 'hi-IN': 'व्यक्तिगत जानकारी', 'mr-IN': 'वैयक्तिक माहिती', 'en-IN': 'Personal Details' } as Str,
    formSectionLand: { 'hi-IN': 'ज़मीन का विवरण', 'mr-IN': 'जमिनीचा तपशील', 'en-IN': 'Land Details' } as Str,
    formSectionBank: { 'hi-IN': 'बैंक विवरण', 'mr-IN': 'बँक तपशील', 'en-IN': 'Bank Details' } as Str,

    validationRequired: { 'hi-IN': 'यह जानकारी आवश्यक है', 'mr-IN': 'ही माहिती आवश्यक आहे', 'en-IN': 'This field is required' } as Str,
    validationMobile: { 'hi-IN': 'कृपया 10 अंकों का सही मोबाइल नंबर डालें', 'mr-IN': 'कृपया 10 अंकी योग्य मोबाइल क्रमांक टाका', 'en-IN': 'Please enter a valid 10-digit mobile number' } as Str,
    validationIfsc: { 'hi-IN': 'कृपया सही IFSC कोड डालें (जैसे SBIN0001234)', 'mr-IN': 'कृपया योग्य IFSC कोड टाका (उदा. SBIN0001234)', 'en-IN': 'Please enter a valid IFSC code (e.g. SBIN0001234)' } as Str,
    validationLandArea: { 'hi-IN': 'कृपया ज़मीन का क्षेत्रफल संख्या में डालें', 'mr-IN': 'कृपया जमिनीचे क्षेत्रफळ संख्येत टाका', 'en-IN': 'Please enter the land area as a number' } as Str,
    validationFixErrors: { 'hi-IN': 'आगे बढ़ने से पहले ऊपर दी गई गलतियों को ठीक करें।', 'mr-IN': 'पुढे जाण्यापूर्वी वरील चुका दुरुस्त करा.', 'en-IN': 'Please fix the errors above before continuing.' } as Str,

    applicationFormTitle: { 'hi-IN': 'आवेदन फॉर्म', 'mr-IN': 'अर्ज फॉर्म', 'en-IN': 'Application Form' } as Str,
    applicationFormSubtitle: {
      'hi-IN': 'यह जानकारी दस्तावेज़ जाँच के दौरान आपके नाम से मिलान करने में मदद करेगी।',
      'mr-IN': 'ही माहिती कागदपत्र तपासणी दरम्यान तुमच्या नावाशी जुळवण्यास मदत करेल.',
      'en-IN': 'This information will help match your name during the document check.',
    } as Str,
    requiredDocumentsForScheme: { 'hi-IN': 'इस योजना के लिए आवश्यक दस्तावेज़', 'mr-IN': 'या योजनेसाठी आवश्यक कागदपत्रे', 'en-IN': 'Required Documents for this Scheme' } as Str,
    iHaveThisDocument: { 'hi-IN': 'मेरे पास यह दस्तावेज़ है', 'mr-IN': 'माझ्याकडे हे कागदपत्र आहे', 'en-IN': 'I have this document' } as Str,
    checkDocumentReadinessBtn: { 'hi-IN': 'दस्तावेज़ तैयारी जाँचें', 'mr-IN': 'कागदपत्र तयारी तपासा', 'en-IN': 'Check Document Readiness' } as Str,
    backToOverview: { 'hi-IN': '← अवलोकन पर वापस जाएं', 'mr-IN': '← आढाव्याकडे परत जा', 'en-IN': '← Back to Overview' } as Str,
  },

  // ── LANDING PAGE ────────────────────────────────────────────
  landing: {
    navSchemes: { 'hi-IN': 'योजनाएं', 'mr-IN': 'योजना', 'en-IN': 'Schemes' } as Str,
    navHow: { 'hi-IN': 'यह कैसे काम करता है', 'mr-IN': 'हे कसे कार्य करते', 'en-IN': 'How it Works' } as Str,
    navAbout: { 'hi-IN': 'हमारे बारे में', 'mr-IN': 'आमच्याबद्दल', 'en-IN': 'About' } as Str,
    navHelp: { 'hi-IN': 'मदद', 'mr-IN': 'मदत', 'en-IN': 'Help' } as Str,
    login: { 'hi-IN': 'लॉगिन', 'mr-IN': 'लॉगिन', 'en-IN': 'Login' } as Str,
    tagline: { 'hi-IN': 'सरकारी योजना खोजक', 'mr-IN': 'सरकारी योजना शोधक', 'en-IN': 'Government Scheme Finder' } as Str,

    badgeAccurate: { 'hi-IN': 'सटीक', 'mr-IN': 'अचूक', 'en-IN': 'Accurate' } as Str,
    badgeFree: { 'hi-IN': 'मुफ्त', 'mr-IN': 'मोफत', 'en-IN': 'Free' } as Str,
    badgeLanguage: { 'hi-IN': 'आपकी भाषा में', 'mr-IN': 'तुमच्या भाषेत', 'en-IN': 'In your language' } as Str,

    headlineHi: { 'hi-IN': 'सुविधा सबके लिए।', 'mr-IN': 'सुविधा सबके लिए।', 'en-IN': 'सुविधा सबके लिए।' } as Str,
    headlineEn: { 'hi-IN': 'सभी के लिए कल्याण।', 'mr-IN': 'सर्वांसाठी कल्याण।', 'en-IN': 'Welfare for all.' } as Str,
    subline: {
      'hi-IN': 'अपनी स्थिति सरल शब्दों में बताएं — किसी भी भारतीय भाषा में। हम आपको हर उस योजना से जोड़ते हैं जिसके आप पात्र हैं और दिखाते हैं कि उसका दावा कैसे करें।',
      'mr-IN': 'तुमची परिस्थिती सोप्या शब्दांत सांगा — कोणत्याही भारतीय भाषेत. आम्ही तुम्हाला तुम्ही पात्र असलेल्या प्रत्येक योजनेशी जोडतो आणि ती कशी मिळवायची ते दाखवतो.',
      'en-IN': 'Tell us your situation in simple words — in any Indian language. We match you to every scheme you qualify for and show you exactly how to claim it.',
    } as Str,
    searchPlaceholder: {
      'hi-IN': 'मैं 45 साल का किसान हूं... / मैं 60 साल की विधवा हूं...',
      'mr-IN': 'मी 45 वर्षांचा शेतकरी आहे... / मी 60 वर्षांची विधवा आहे...',
      'en-IN': 'I am a 45-year-old farmer... / I am a 60-year-old widow...',
    } as Str,
    findSchemes: { 'hi-IN': 'योजनाएं खोजें →', 'mr-IN': 'योजना शोधा →', 'en-IN': 'Find Schemes →' } as Str,
    chipFarmer: { 'hi-IN': 'किसान', 'mr-IN': 'शेतकरी', 'en-IN': 'Farmer' } as Str,
    chipSenior: { 'hi-IN': 'वरिष्ठ नागरिक', 'mr-IN': 'ज्येष्ठ नागरिक', 'en-IN': 'Senior Citizen' } as Str,
    chipWoman: { 'hi-IN': 'अकेली महिला', 'mr-IN': 'एकल महिला', 'en-IN': 'Single Woman' } as Str,
    chipStudent: { 'hi-IN': 'छात्र', 'mr-IN': 'विद्यार्थी', 'en-IN': 'Student' } as Str,
    chipWage: { 'hi-IN': 'दिहाड़ी मजदूर', 'mr-IN': 'रोजंदारी कामगार', 'en-IN': 'Daily Wage Worker' } as Str,
    chipHousing: { 'hi-IN': 'घर चाहिए', 'mr-IN': 'घर हवे', 'en-IN': 'Need Housing' } as Str,
    speakLang: { 'hi-IN': 'अपनी भाषा में बोलें', 'mr-IN': 'तुमच्या भाषेत बोला', 'en-IN': 'Speak in your language' } as Str,
    langList: { 'hi-IN': 'हिंदी · अंग्रेज़ी · मराठी + 9 और', 'mr-IN': 'हिंदी · इंग्रजी · मराठी + 9 अधिक', 'en-IN': 'Hindi · English · Marathi + 9 more' } as Str,
    trust1: { 'hi-IN': '500+ योजनाएं शामिल', 'mr-IN': '500+ योजना समाविष्ट', 'en-IN': '500+ schemes covered' } as Str,
    trust2: { 'hi-IN': 'केंद्र और राज्य सरकारें', 'mr-IN': 'केंद्र आणि राज्य सरकारे', 'en-IN': 'Central and state governments' } as Str,
    trust3: { 'hi-IN': 'आधिकारिक स्रोतों से अद्यतन', 'mr-IN': 'अधिकृत स्रोतांकडून अद्ययावत', 'en-IN': 'Updated from official sources' } as Str,

    citizenCenter: { 'hi-IN': 'नागरिक', 'mr-IN': 'नागरिक', 'en-IN': 'The Citizen' } as Str,
    citizenSub: { 'hi-IN': 'आप केंद्र में हैं', 'mr-IN': 'तुम्ही केंद्रस्थानी आहात', 'en-IN': 'You are at the center' } as Str,

    statSchemes: { 'hi-IN': 'सरकारी योजनाएं', 'mr-IN': 'सरकारी योजना', 'en-IN': 'Government schemes' } as Str,
    statLanguages: { 'hi-IN': 'भारतीय भाषाएं', 'mr-IN': 'भारतीय भाषा', 'en-IN': 'Indian languages' } as Str,
    statTime: { 'hi-IN': 'औसत खोज समय', 'mr-IN': 'सरासरी शोध वेळ', 'en-IN': 'Average search time' } as Str,
    statFree: { 'hi-IN': 'हर नागरिक के लिए', 'mr-IN': 'प्रत्येक नागरिकासाठी', 'en-IN': 'For every citizen' } as Str,
    statFreeNum: { 'hi-IN': 'मुफ्त', 'mr-IN': 'मोफत', 'en-IN': 'Free' } as Str,
    statTimeNum: { 'hi-IN': '3 मिनट', 'mr-IN': '3 मिनिटे', 'en-IN': '3 min' } as Str,

    dualModeTag: { 'hi-IN': 'SuvidhaAI उपयोग करने के दो तरीके', 'mr-IN': 'SuvidhaAI वापरण्याचे दोन मार्ग', 'en-IN': 'Two ways to use SuvidhaAI' } as Str,
    dualModeHeading: { 'hi-IN': 'चुनें आप कैसे खोजना चाहते हैं', 'mr-IN': 'तुम्हाला कसे शोधायचे ते निवडा', 'en-IN': 'Choose how you want to search' } as Str,
    dualModeSub: {
      'hi-IN': 'हर नागरिक के लिए एक मंच — ग्रामीण उपयोगकर्ताओं के लिए सरल आवाज़ मार्गदर्शन, पारिवारिक सहायकों और CSC संचालकों के लिए पूर्ण आवेदन उपकरण।',
      'mr-IN': 'प्रत्येक नागरिकासाठी एक व्यासपीठ — ग्रामीण वापरकर्त्यांसाठी सोपे आवाज मार्गदर्शन, कौटुंबिक मदतनीस आणि CSC ऑपरेटरसाठी संपूर्ण अर्ज साधने.',
      'en-IN': 'One platform for every citizen — simple voice guidance for rural users, complete application tools for family helpers and CSC operators.',
    } as Str,
    simpleModeBadge: { 'hi-IN': 'सरल मोड', 'mr-IN': 'सोपी पद्धत', 'en-IN': 'Simple Mode' } as Str,
    simpleModeTitle: { 'hi-IN': 'सरल मोड — सीधे नागरिकों के लिए', 'mr-IN': 'सोपी पद्धत — थेट नागरिकांसाठी', 'en-IN': 'Simple Mode — For Citizens Directly' } as Str,
    simpleModeDesc: {
      'hi-IN': 'आवाज़-पहला, हिंदी और मराठी, परिणाम बोलकर सुनाए जाते हैं। किसानों, वरिष्ठ नागरिकों और ग्रामीण उपयोगकर्ताओं के लिए बनाया गया — कम से कम पाठ, अधिकतम स्पष्टता।',
      'mr-IN': 'आवाज-प्रथम, हिंदी आणि मराठी, निकाल बोलून सांगितले जातात. शेतकरी, ज्येष्ठ नागरिक आणि ग्रामीण वापरकर्त्यांसाठी तयार — कमीत कमी मजकूर, जास्तीत जास्त स्पष्टता.',
      'en-IN': 'Voice-first, Hindi and Marathi, results spoken aloud. Designed for farmers, senior citizens, and rural users — minimal text, maximum clarity.',
    } as Str,
    simpleFeat1: { 'hi-IN': 'अपनी स्थिति बोलें — टाइप करने की ज़रूरत नहीं', 'mr-IN': 'तुमची परिस्थिती बोला — टाइप करण्याची गरज नाही', 'en-IN': 'Speak your situation — no typing needed' } as Str,
    simpleFeat2: { 'hi-IN': 'परिणाम हिंदी या मराठी में बोलकर सुनाए जाते हैं', 'mr-IN': 'निकाल हिंदी किंवा मराठीत बोलून सांगितले जातात', 'en-IN': 'Results read aloud in Hindi or Marathi' } as Str,
    simpleFeat3: { 'hi-IN': 'एक-टैप WhatsApp शेयर और हेल्पलाइन कॉल', 'mr-IN': 'एक-टॅप WhatsApp शेअर आणि हेल्पलाइन कॉल', 'en-IN': 'One-tap WhatsApp share and helpline call' } as Str,
    simpleFeat4: { 'hi-IN': 'कोई लॉगिन या पंजीकरण आवश्यक नहीं', 'mr-IN': 'कोणतेही लॉगिन किंवा नोंदणी आवश्यक नाही', 'en-IN': 'No login or registration needed' } as Str,
    useSimpleMode: { 'hi-IN': 'सरल मोड उपयोग करें — बोलकर खोजें', 'mr-IN': 'सोपी पद्धत वापरा — बोलून शोधा', 'en-IN': 'Use Simple Mode — Speak to Search' } as Str,

    fullModeBadge: { 'hi-IN': 'पूर्ण सुविधा', 'mr-IN': 'पूर्ण सुविधा', 'en-IN': 'Full Mode' } as Str,
    fullModeTitle: { 'hi-IN': 'फुल मोड — सहायकों और CSC संचालकों के लिए', 'mr-IN': 'फुल मोड — मदतनीस आणि CSC ऑपरेटरसाठी', 'en-IN': 'Full Mode — For Helpers & CSC Operators' } as Str,
    fullModeDesc: {
      'hi-IN': 'पूर्ण पात्रता विश्लेषण, अस्वीकृति रोकथाम, पहले से भरे आवेदन दस्तावेज़, और शिक्षित परिवार के सदस्यों और सरकारी संचालकों के लिए स्थिति ट्रैकिंग।',
      'mr-IN': 'संपूर्ण पात्रता विश्लेषण, नकार प्रतिबंध, आधीच भरलेली अर्ज कागदपत्रे, आणि शिक्षित कुटुंब सदस्य व सरकारी ऑपरेटरसाठी स्थिती ट्रॅकिंग.',
      'en-IN': 'Complete eligibility analysis, rejection prevention, pre-filled application documents, and status tracking for educated family members and government operators.',
    } as Str,
    fullFeat1: { 'hi-IN': 'प्रत्येक योजना के लिए विस्तृत पात्रता जाँच', 'mr-IN': 'प्रत्येक योजनेसाठी सविस्तर पात्रता तपासणी', 'en-IN': 'Detailed eligibility check per scheme' } as Str,
    fullFeat2: { 'hi-IN': 'अस्वीकृति रोकथाम चेतावनियां', 'mr-IN': 'नकार प्रतिबंध इशारे', 'en-IN': 'Rejection prevention warnings' } as Str,
    fullFeat3: { 'hi-IN': 'प्रिंट करने योग्य पहले से भरा आवेदन सारांश', 'mr-IN': 'छापण्यायोग्य आधीच भरलेला अर्ज सारांश', 'en-IN': 'Printable pre-filled application summary' } as Str,
    fullFeat4: { 'hi-IN': 'प्रोफ़ाइल में आवेदन स्थिति ट्रैकर', 'mr-IN': 'प्रोफाइलमध्ये अर्ज स्थिती ट्रॅकर', 'en-IN': 'Application status tracker in profile' } as Str,
    useFullMode: { 'hi-IN': 'फुल मोड उपयोग करें — पूर्ण सुविधा', 'mr-IN': 'फुल मोड वापरा — पूर्ण सुविधा', 'en-IN': 'Use Full Mode — Complete Toolkit' } as Str,

    problemTag: { 'hi-IN': 'असली समस्या', 'mr-IN': 'खरी समस्या', 'en-IN': 'The real problem' } as Str,
    problemHeading: { 'hi-IN': '₹12 लाख करोड़ का कल्याण। ज़्यादातर दावा नहीं किया गया।', 'mr-IN': '₹12 लाख कोटींचे कल्याण. बहुतांश दावा केलेला नाही.', 'en-IN': '₹12 lakh crore in welfare. Most of it unclaimed.' } as Str,
    problemSub: {
      'hi-IN': 'भारत अधिकांश विकासशील देशों की तुलना में प्रति नागरिक अधिक आवंटित करता है। समस्या बजट नहीं है — यह योजनाओं के अस्तित्व और नागरिकों को वास्तव में मिलने के बीच का अंतर है।',
      'mr-IN': 'भारत बहुतेक विकसनशील देशांपेक्षा प्रति नागरिक जास्त वाटप करतो. समस्या बजेट नाही — योजना अस्तित्वात असणे आणि नागरिकांना प्रत्यक्ष मिळणे यामधील ही तफावत आहे.',
      'en-IN': 'India allocates more per citizen than most developing nations. The problem is not the budget — it is the gap between schemes existing and citizens actually receiving them.',
    } as Str,
    statAwareness: { 'hi-IN': 'पात्र नागरिक जो कभी आवेदन नहीं करते', 'mr-IN': 'पात्र नागरिक जे कधीच अर्ज करत नाहीत', 'en-IN': 'Eligible citizens who never apply' } as Str,
    statUsability: { 'hi-IN': 'सरकारी डिजिटल पोर्टल को उपयोग करना बहुत कठिन पाते हैं', 'mr-IN': 'सरकारी डिजिटल पोर्टल वापरणे खूप कठीण वाटते', 'en-IN': 'Find government digital portals too difficult to use' } as Str,
    statLanguage: { 'hi-IN': 'भारतीय भाषाएं पसंद करते हैं — अधिकांश पोर्टल केवल अंग्रेज़ी में', 'mr-IN': 'भारतीय भाषा पसंत करतात — बहुतेक पोर्टल फक्त इंग्रजीत', 'en-IN': 'Prefer Indic languages — most portals are English only' } as Str,
    statGuidance: { 'hi-IN': 'गुम या गलत दस्तावेज़ों के कारण आवेदन अस्वीकृत', 'mr-IN': 'हरवलेल्या किंवा चुकीच्या कागदपत्रांमुळे अर्ज नाकारले', 'en-IN': 'Applications rejected due to missing or incorrect documents' } as Str,
    badgeAwareness: { 'hi-IN': 'जागरूकता की कमी', 'mr-IN': 'जागरूकतेची कमतरता', 'en-IN': 'Awareness gap' } as Str,
    badgeUsability: { 'hi-IN': 'उपयोगिता की कमी', 'mr-IN': 'वापरण्यायोग्यतेची कमतरता', 'en-IN': 'Usability gap' } as Str,
    badgeLanguageGap: { 'hi-IN': 'भाषा की कमी', 'mr-IN': 'भाषेची कमतरता', 'en-IN': 'Language gap' } as Str,
    badgeGuidance: { 'hi-IN': 'मार्गदर्शन की कमी', 'mr-IN': 'मार्गदर्शनाची कमतरता', 'en-IN': 'Guidance gap' } as Str,
    barrier1Title: { 'hi-IN': 'अंग्रेज़ी इंटरफेस नेविगेट नहीं कर सकते', 'mr-IN': 'इंग्रजी इंटरफेस वापरता येत नाही', 'en-IN': 'Cannot navigate English interfaces' } as Str,
    barrier1Desc: { 'hi-IN': 'अधिकांश पोर्टल में बुनियादी योजनाएं खोजने के लिए अंग्रेज़ी साक्षरता चाहिए', 'mr-IN': 'बहुतेक पोर्टलमध्ये मूलभूत योजना शोधण्यासाठी इंग्रजी साक्षरता आवश्यक आहे', 'en-IN': 'Most portals require English literacy to find basic schemes' } as Str,
    barrier2Title: { 'hi-IN': 'पोर्टल जो हिंदी में परिणाम बोलते हैं', 'mr-IN': 'पोर्टल जे हिंदीत निकाल सांगतात', 'en-IN': 'Portals that speak results in Hindi' } as Str,
    barrier2Desc: { 'hi-IN': '14 करोड़ भारतीय रोज़ आवाज़ का उपयोग करते हैं — कोई पोर्टल इसे समर्थन नहीं करता', 'mr-IN': '14 कोटी भारतीय दररोज आवाज वापरतात — कोणताही पोर्टल याला समर्थन देत नाही', 'en-IN': '140M Indians use voice daily — no portal supports it' } as Str,
    barrier3Title: { 'hi-IN': 'ग्रामीण उपयोगकर्ता आवाज़ इंटरफेस पसंद करते हैं', 'mr-IN': 'ग्रामीण वापरकर्ते आवाज इंटरफेस पसंत करतात', 'en-IN': 'Rural users prefer voice interfaces' } as Str,
    barrier3Desc: { 'hi-IN': 'समाधान मौजूद है — इसे कल्याण पर लागू नहीं किया गया', 'mr-IN': 'उपाय अस्तित्वात आहे — तो कल्याणासाठी वापरला गेला नाही', 'en-IN': 'The solution exists — it just hasn\'t been applied to welfare' } as Str,
    chartTitle: { 'hi-IN': 'मौजूदा कल्याण पोर्टल वास्तव में किन तक पहुंचते हैं?', 'mr-IN': 'सध्याचे कल्याण पोर्टल प्रत्यक्षात कोणापर्यंत पोहोचतात?', 'en-IN': 'Who do existing welfare portals actually reach?' } as Str,
    chartSub: { 'hi-IN': 'पात्र जनसंख्या का % सक्रिय मासिक उपयोगकर्ता · भारत 2024', 'mr-IN': 'पात्र लोकसंख्येच्या % सक्रिय मासिक वापरकर्ते · भारत 2024', 'en-IN': 'Active monthly users as % of eligible population · India 2024' } as Str,
    barUrban: { 'hi-IN': 'शहरी शिक्षित उपयोगकर्ता', 'mr-IN': 'शहरी सुशिक्षित वापरकर्ते', 'en-IN': 'Urban educated users' } as Str,
    barSemiUrban: { 'hi-IN': 'अर्ध-शहरी उपयोगकर्ता', 'mr-IN': 'निमशहरी वापरकर्ते', 'en-IN': 'Semi-urban users' } as Str,
    barRural: { 'hi-IN': 'ग्रामीण उपयोगकर्ता — मुख्य लाभार्थी', 'mr-IN': 'ग्रामीण वापरकर्ते — प्रमुख लाभार्थी', 'en-IN': 'Rural users — primary beneficiaries' } as Str,
    barRuralVoice: { 'hi-IN': 'आवाज़ से सहज ग्रामीण उपयोगकर्ता', 'mr-IN': 'आवाजाने सोयीस्कर ग्रामीण वापरकर्ते', 'en-IN': 'Rural users comfortable with voice' } as Str,
    barVoiceSearch: { 'hi-IN': 'रोज़ आवाज़ खोज उपयोग करने वाले भारतीय', 'mr-IN': 'दररोज आवाज शोध वापरणारे भारतीय', 'en-IN': 'Indians using voice search daily' } as Str,
    calloutTitle: { 'hi-IN': 'सीधे शब्दों में अंतर', 'mr-IN': 'सोप्या शब्दांत तफावत', 'en-IN': 'The gap in plain terms' } as Str,
    calloutBoldPart: { 'hi-IN': 'ग्रामीण नागरिक अधिकांश कल्याण योजनाओं के मुख्य इच्छित लाभार्थी हैं', 'mr-IN': 'ग्रामीण नागरिक बहुतेक कल्याण योजनांचे मुख्य इच्छित लाभार्थी आहेत', 'en-IN': 'Rural citizens are the primary intended beneficiaries of most welfare schemes' } as Str,
    calloutRest: { 'hi-IN': '— फिर भी मौजूदा डिजिटल पोर्टल उनमें से केवल 9% तक पहुंचते हैं। SuvidhaAI उस 91% के लिए बनाया गया है जिन तक मौजूदा उपकरण नहीं पहुंचे।', 'mr-IN': '— तरीही सध्याचे डिजिटल पोर्टल त्यांच्यापैकी फक्त 9% पर्यंत पोहोचतात. SuvidhaAI त्या 91% साठी बनवले आहे ज्यांच्यापर्यंत सध्याची साधने पोहोचली नाहीत.', 'en-IN': '— yet existing digital portals reach only 9% of them. SuvidhaAI is built for the 91% that existing tools have not reached.' } as Str,

    howTag: { 'hi-IN': 'चरण दर चरण', 'mr-IN': 'टप्प्याटप्प्याने', 'en-IN': 'Step by step' } as Str,
    howHeading: { 'hi-IN': '3 मिनट से कम में भ्रम से स्पष्टता तक', 'mr-IN': '3 मिनिटांपेक्षा कमी वेळात गोंधळापासून स्पष्टतेपर्यंत', 'en-IN': 'From confusion to clarity in under 3 minutes' } as Str,
    howSub: {
      'hi-IN': 'SuvidhaAI आपको हर चरण में मार्गदर्शन करता है — यह न जानने से कि आप किस के लिए पात्र हैं, पूरी तरह तैयार होकर CSC में जाने तक।',
      'mr-IN': 'SuvidhaAI तुम्हाला प्रत्येक टप्प्यात मार्गदर्शन करते — तुम्ही कशासाठी पात्र आहात हे माहीत नसण्यापासून, पूर्ण तयारीनिशी CSC मध्ये जाण्यापर्यंत.',
      'en-IN': 'SuvidhaAI guides you through every step — from not knowing what you qualify for, to walking into a CSC fully prepared.',
    } as Str,
    step1Title: { 'hi-IN': 'बोलें या टाइप करें', 'mr-IN': 'बोला किंवा टाइप करा', 'en-IN': 'Speak or Type' } as Str,
    step1Desc: { 'hi-IN': 'हिंदी, मराठी, या अंग्रेज़ी में बताएं कि आप कौन हैं। कोई ड्रॉपडाउन नहीं, कोई फॉर्म नहीं। बस स्वाभाविक रूप से बोलें।', 'mr-IN': 'हिंदी, मराठी किंवा इंग्रजीत सांगा तुम्ही कोण आहात. कोणतेही ड्रॉपडाउन नाही, फॉर्म नाही. फक्त नैसर्गिकपणे बोला.', 'en-IN': 'Say who you are in Hindi, Marathi, or English. No dropdowns, no forms. Just speak naturally.' } as Str,
    step2Title: { 'hi-IN': 'AI 500+ योजनाएं स्कैन करता है', 'mr-IN': 'AI 500+ योजना स्कॅन करते', 'en-IN': 'AI Scans 500+ Schemes' } as Str,
    step2Desc: { 'hi-IN': 'हम आपकी प्रोफ़ाइल स्वचालित रूप से निकालते हैं और आपको हर केंद्र और राज्य सरकार योजना से मिलाते हैं।', 'mr-IN': 'आम्ही तुमची प्रोफाइल आपोआप काढतो आणि तुम्हाला प्रत्येक केंद्र आणि राज्य सरकार योजनेशी जुळवतो.', 'en-IN': 'We extract your profile automatically and match you against every central and state government scheme.' } as Str,
    step3Title: { 'hi-IN': 'देखें आप किसके लिए पात्र हैं', 'mr-IN': 'तुम्ही कशासाठी पात्र आहात ते पहा', 'en-IN': 'See What You Qualify For' } as Str,
    step3Desc: { 'hi-IN': 'हर परिणाम स्पष्ट रूप से बताता है: पात्र, संभवतः पात्र, या अपात्र — सरल-भाषा स्पष्टीकरण के साथ।', 'mr-IN': 'प्रत्येक निकाल स्पष्टपणे सांगतो: पात्र, कदाचित पात्र, किंवा अपात्र — सोप्या भाषेतील स्पष्टीकरणासह.', 'en-IN': 'Each result tells you clearly: Eligible, Maybe Eligible, or Not Eligible — with a plain-language explanation.' } as Str,
    step4Title: { 'hi-IN': 'आवेदन करने से पहले चेतावनी पाएं', 'mr-IN': 'अर्ज करण्यापूर्वी इशारा मिळवा', 'en-IN': 'Get Warned Before You Apply' } as Str,
    step4Desc: { 'hi-IN': 'हम सामान्य अस्वीकृति कारण दिखाते हैं ताकि आप आवेदन करने से पहले उन्हें ठीक करें — व्यर्थ यात्राओं की बचत।', 'mr-IN': 'आम्ही सामान्य नकार कारणे दाखवतो जेणेकरून तुम्ही अर्ज करण्यापूर्वी ती दुरुस्त करू शकाल — वाया जाणाऱ्या फेऱ्या वाचतील.', 'en-IN': 'We show common rejection reasons so you fix them before applying — saving wasted trips.' } as Str,
    step5Title: { 'hi-IN': 'अपना तैयारी दस्तावेज़ पाएं', 'mr-IN': 'तुमचा तयारी दस्तऐवज मिळवा', 'en-IN': 'Get Your Preparation Document' } as Str,
    step5Desc: { 'hi-IN': 'आपके विवरण के साथ पहले से भरा एक प्रिंट करने योग्य सारांश, ले जाने वाले दस्तावेज़, और कहाँ जाना है — आपकी भाषा में।', 'mr-IN': 'तुमच्या तपशिलांसह आधीच भरलेला छापण्यायोग्य सारांश, सोबत न्यायची कागदपत्रे, आणि कुठे जायचे — तुमच्या भाषेत.', 'en-IN': 'A printable summary with your details pre-filled, documents to carry, and where to go — in your language.' } as Str,
    step6Title: { 'hi-IN': 'WhatsApp पर शेयर करें', 'mr-IN': 'WhatsApp वर शेअर करा', 'en-IN': 'Share on WhatsApp' } as Str,
    step6Desc: { 'hi-IN': 'एक टैप आपकी सभी मिलान योजनाओं को WhatsApp पर भेजता है ताकि आपका परिवार या CSC संचालक आवेदन करने में मदद कर सके।', 'mr-IN': 'एक टॅप तुमच्या सर्व जुळलेल्या योजना WhatsApp वर पाठवतो जेणेकरून तुमचे कुटुंब किंवा CSC ऑपरेटर अर्ज करण्यास मदत करू शकेल.', 'en-IN': 'One tap sends all your matched schemes to WhatsApp so your family or CSC operator can help you apply.' } as Str,

    audienceTag: { 'hi-IN': 'आप कौन हैं उसके आधार पर खोजें', 'mr-IN': 'तुम्ही कोण आहात त्यानुसार शोधा', 'en-IN': 'Find by who you are' } as Str,
    audienceHeading: { 'hi-IN': 'हर नागरिक। हर योजना।', 'mr-IN': 'प्रत्येक नागरिक. प्रत्येक योजना.', 'en-IN': 'Every citizen. Every scheme.' } as Str,
    audienceSub: { 'hi-IN': 'अपनी स्थिति चुनें — हम आपको हर योजना दिखाते हैं जिसके आप पात्र हैं, दावा करने के पूर्ण मार्गदर्शन के साथ।', 'mr-IN': 'तुमची परिस्थिती निवडा — आम्ही तुम्हाला तुम्ही पात्र असलेली प्रत्येक योजना संपूर्ण मार्गदर्शनासह दाखवतो.', 'en-IN': 'Select your situation — we show every scheme you qualify for with full guidance to claim it.' } as Str,
    schemesCount: { 'hi-IN': (n: number) => `${n} योजनाएं`, 'mr-IN': (n: number) => `${n} योजना`, 'en-IN': (n: number) => `${n} SCHEMES` } as StrFn1,
    viewAll: { 'hi-IN': 'सभी योजनाएं देखें', 'mr-IN': 'सर्व योजना पहा', 'en-IN': 'View all schemes' } as Str,
    audFarmers: { 'hi-IN': 'किसान', 'mr-IN': 'शेतकरी', 'en-IN': 'Farmers' } as Str,
    audFarmersDesc: { 'hi-IN': 'फसल बीमा, आय सहायता, सोलर पंप, कर्ज़', 'mr-IN': 'पीक विमा, उत्पन्न सहाय्य, सोलर पंप, कर्ज', 'en-IN': 'Crop insurance, income support, solar pumps, credit' } as Str,
    audWomen: { 'hi-IN': 'महिलाएं', 'mr-IN': 'महिला', 'en-IN': 'Women' } as Str,
    audWomenDesc: { 'hi-IN': 'मातृत्व, विधवा पेंशन, LPG, उद्यमिता ऋण', 'mr-IN': 'मातृत्व, विधवा निवृत्तीवेतन, LPG, उद्योजकता कर्ज', 'en-IN': 'Maternity, widow pension, LPG, entrepreneurship loans' } as Str,
    audSeniors: { 'hi-IN': 'वरिष्ठ नागरिक', 'mr-IN': 'ज्येष्ठ नागरिक', 'en-IN': 'Senior Citizens' } as Str,
    audSeniorsDesc: { 'hi-IN': 'वृद्धावस्था पेंशन, आयुष्मान स्वास्थ्य कवर, बचत', 'mr-IN': 'वृद्धापकाळ निवृत्तीवेतन, आयुष्मान आरोग्य कवच, बचत', 'en-IN': 'Old age pension, Ayushman health cover, savings' } as Str,
    audStudents: { 'hi-IN': 'छात्र और युवा', 'mr-IN': 'विद्यार्थी आणि युवक', 'en-IN': 'Students & Youth' } as Str,
    audStudentsDesc: { 'hi-IN': 'छात्रवृत्ति, कौशल प्रशिक्षण, इंटर्नशिप, ऋण', 'mr-IN': 'शिष्यवृत्ती, कौशल्य प्रशिक्षण, इंटर्नशिप, कर्ज', 'en-IN': 'Scholarships, skill training, internships, loans' } as Str,
    audBusiness: { 'hi-IN': 'व्यापार और स्व-रोज़गार', 'mr-IN': 'व्यवसाय आणि स्वयंरोजगार', 'en-IN': 'Business & Self-Employed' } as Str,
    audBusinessDesc: { 'hi-IN': 'मुद्रा ऋण, विक्रेता ऋण, PMEGP अनुदान', 'mr-IN': 'मुद्रा कर्ज, विक्रेता कर्ज, PMEGP अनुदान', 'en-IN': 'Mudra loans, vendor credit, PMEGP grants' } as Str,
    audHealth: { 'hi-IN': 'स्वास्थ्य और आवास', 'mr-IN': 'आरोग्य आणि गृहनिर्माण', 'en-IN': 'Health & Housing' } as Str,
    audHealthDesc: { 'hi-IN': 'आयुष्मान स्वास्थ्य कवर, PM आवास योजना, स्वच्छता', 'mr-IN': 'आयुष्मान आरोग्य कवच, PM आवास योजना, स्वच्छता', 'en-IN': 'Ayushman health cover, PM Awas Yojana, sanitation' } as Str,

    footerInfo: { 'hi-IN': 'भारत सरकार के आधिकारिक पोर्टल से प्राप्त डेटा · हर नागरिक के लिए मुफ्त', 'mr-IN': 'भारत सरकारच्या अधिकृत पोर्टलवरून घेतलेला डेटा · प्रत्येक नागरिकासाठी मोफत', 'en-IN': 'Data sourced from official Government of India portals · Free for every citizen' } as Str,
    footerAbout: { 'hi-IN': 'हमारे बारे में', 'mr-IN': 'आमच्याबद्दल', 'en-IN': 'About' } as Str,
    footerHelp: { 'hi-IN': 'मदद', 'mr-IN': 'मदत', 'en-IN': 'Help' } as Str,
    footerPrivacy: { 'hi-IN': 'गोपनीयता', 'mr-IN': 'गोपनीयता', 'en-IN': 'Privacy' } as Str,
    footerContact: { 'hi-IN': 'संपर्क करें', 'mr-IN': 'संपर्क', 'en-IN': 'Contact' } as Str,
  },
}
