"""add email login support

Revision ID: b997800061c5
Revises: 3d8530313aaf
Create Date: 2026-08-16 20:30:19.767395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b997800061c5'
down_revision: Union[str, Sequence[str], None] = '3d8530313aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('otp_requests', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_index('ix_otp_requests_email_expiry', 'otp_requests', ['email', 'expires_at'], unique=False)
    # DISABLED: 'warning' and 'rejection_risks' already created by 2ac3a903d489.
    # op.add_column('schemes', sa.Column('warning', sa.Text(), nullable=True))
    # op.add_column('schemes', sa.Column('rejection_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # DISABLED: users.email + ix_users_email already created by the modified
    # a82a2f043315 (add identity and access tables) migration.
    # op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # op.drop_column('users', 'email')
    # op.drop_column('schemes', 'rejection_risks')
    # op.drop_column('schemes', 'warning')
    op.drop_index('ix_otp_requests_email_expiry', table_name='otp_requests')
    op.alter_column('otp_requests', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('otp_requests', 'email')
    # ### end Alembic commands ###

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('users', 'email')
    # DISABLED: see upgrade() — these columns belong to 2ac3a903d489, not here.
    # op.drop_column('schemes', 'rejection_risks')
    # op.drop_column('schemes', 'warning')
    op.drop_index('ix_otp_requests_email_expiry', table_name='otp_requests')
    op.alter_column('otp_requests', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('otp_requests', 'email')
    # ### end Alembic commands ###


    