// All 10 backend-supported languages. S.landing (the home page) is
// authored for all 10; S.full (the Full Mode dashboard) is currently
// authored only for hi/mr/en and falls back to English for the rest via
// the `?? obj['en-IN']` lookups below — Str/StrFn1 are Partial so a
// bundle doesn't have to define every language to type-check.
export type Lang = 'hi-IN' | 'mr-IN' | 'en-IN' | 'ta-IN' | 'te-IN' | 'kn-IN' | 'ml-IN' | 'bn-IN' | 'gu-IN' | 'pa-IN'

type Str = Partial<Record<Lang, string>>
type StrFn1 = Partial<Record<Lang, (a: string | number) => string>>

function pick<T>(obj: Partial<Record<Lang, T>>, lang: Lang): T {
  return (obj[lang] ?? obj['en-IN']) as T
}

// Helper: get a plain string for the current language
export function g(obj: Str, lang: Lang): string {
  return obj[lang] ?? obj['en-IN'] ?? ''
}

// Helper: get + call a templated string for the current language
export function gf(obj: StrFn1, lang: Lang, arg: string | number): string {
  const fn = obj[lang] ?? obj['en-IN']
  return fn ? fn(arg) : ''
}

export const S = {
  // ── FULL MODE ─────────────────────────────────────────────
  full: {
    brandTag: { 'hi-IN': 'सरकारी योजना खोजक', 'mr-IN': 'सरकारी योजना शोधक', 'en-IN': 'GOVERNMENT SCHEME FINDER' } as Str,
    farmerMaharashtra: { 'hi-IN': 'किसान · महाराष्ट्र', 'mr-IN': 'शेतकरी · महाराष्ट्र', 'en-IN': 'Farmer · Maharashtra' } as Str,

    navSchemes: { 'hi-IN': 'योजना खोज', 'mr-IN': 'योजना शोध', 'en-IN': 'Scheme Search' } as Str,
    navCompare: { 'hi-IN': 'योजनाओं की तुलना', 'mr-IN': 'योजनांची तुलना', 'en-IN': 'Compare Schemes' } as Str,
    navPrep: { 'hi-IN': 'आवेदन तैयारी', 'mr-IN': 'अर्ज तयारी', 'en-IN': 'Application Prep' } as Str,
    navTracker: { 'hi-IN': 'आवेदन ट्रैकर', 'mr-IN': 'अर्ज ट्रॅकर', 'en-IN': 'Application Tracker' } as Str,
    navCSC: { 'hi-IN': 'CSC खोजें', 'mr-IN': 'CSC शोधा', 'en-IN': 'CSC Locator' } as Str,
    navHelpline: { 'hi-IN': 'हेल्पलाइन', 'mr-IN': 'हेल्पलाइन', 'en-IN': 'Helpline' } as Str,
    navMain: { 'hi-IN': 'मुख्य', 'mr-IN': 'मुख्य', 'en-IN': 'MAIN' } as Str,

    searchLabel: { 'hi-IN': 'अपनी स्थिति बताएं', 'mr-IN': 'तुमची परिस्थिती सांगा', 'en-IN': 'Describe Your Situation' } as Str,
    searchPlaceholder: { 'hi-IN': 'मैं 45 साल का किसान हूँ...', 'mr-IN': 'मी 45 वर्षांचा शेतकरी आहे...', 'en-IN': 'I am a 45 year old farmer from Maharashtra...' } as Str,
    searchBtn: { 'hi-IN': 'खोजें', 'mr-IN': 'शोधा', 'en-IN': 'Search' } as Str,
    showingAll: { 'hi-IN': (n) => `सभी ${n} योजनाएं दिखाई जा रही हैं`, 'mr-IN': (n) => `सर्व ${n} योजना दाखवत आहे`, 'en-IN': (n) => `Showing all ${n} schemes` } as StrFn1,
    schemesFound: { 'hi-IN': (n) => `${n} योजनाएं मिलीं`, 'mr-IN': (n) => `${n} योजना सापडल्या`, 'en-IN': (n) => `${n} schemes found` } as StrFn1,
    filterState: { 'hi-IN': 'राज्य: महाराष्ट्र', 'mr-IN': 'राज्य: महाराष्ट्र', 'en-IN': 'State: Maharashtra' } as Str,
    filterAge: { 'hi-IN': 'आयु: 45', 'mr-IN': 'वय: 45', 'en-IN': 'Age: 45' } as Str,
    filterOccupation: { 'hi-IN': 'व्यवसाय: किसान', 'mr-IN': 'व्यवसाय: शेतकरी', 'en-IN': 'Occupation: Farmer' } as Str,
    filterIncome: { 'hi-IN': 'आय: कम', 'mr-IN': 'उत्पन्न: कमी', 'en-IN': 'Income: Low' } as Str,

    bestMatch: { 'hi-IN': 'सर्वश्रेष्ठ मिलान', 'mr-IN': 'सर्वोत्तम जुळणी', 'en-IN': 'Best Match' } as Str,
    highestBenefit: { 'hi-IN': 'सर्वाधिक लाभ', 'mr-IN': 'सर्वाधिक लाभ', 'en-IN': 'Highest Benefit' } as Str,
    easiest: { 'hi-IN': 'सबसे आसान', 'mr-IN': 'सर्वात सोपे', 'en-IN': 'Easiest' } as Str,

    eligible: { 'hi-IN': '✓ पात्र', 'mr-IN': '✓ पात्र', 'en-IN': '✓ Eligible' } as Str,
    partial: { 'hi-IN': '⚠ आंशिक', 'mr-IN': '⚠ आंशिक', 'en-IN': '⚠ Partial' } as Str,
    ineligible: { 'hi-IN': '✗ अपात्र', 'mr-IN': '✗ अपात्र', 'en-IN': '✗ Ineligible' } as Str,
    highMatch: { 'hi-IN': 'उच्च मिलान', 'mr-IN': 'उच्च जुळणी', 'en-IN': 'High Match' } as Str,
    partialMatch: { 'hi-IN': 'आंशिक मिलान', 'mr-IN': 'आंशिक जुळणी', 'en-IN': 'Partial Match' } as Str,
    matchPercent: { 'hi-IN': (n) => `${n}% मिलान`, 'mr-IN': (n) => `${n}% जुळणी`, 'en-IN': (n) => `${n}% match` } as StrFn1,
    viewDetails: { 'hi-IN': 'विवरण देखें', 'mr-IN': 'तपशील पहा', 'en-IN': 'View Details' } as Str,
    fixArrow: { 'hi-IN': 'समाधान →', 'mr-IN': 'उपाय →', 'en-IN': 'Fix →' } as Str,

    eligibilityCheck: { 'hi-IN': 'पात्रता जाँच', 'mr-IN': 'पात्रता तपासणी', 'en-IN': 'Eligibility Check' } as Str,
    rejectionRisks: { 'hi-IN': 'अस्वीकृति के जोखिम', 'mr-IN': 'नकार जोखीम', 'en-IN': 'Rejection Risks' } as Str,
    howToApply: { 'hi-IN': 'आवेदन कैसे करें', 'mr-IN': 'अर्ज कसा करावा', 'en-IN': 'How to Apply' } as Str,
    docsRequired: { 'hi-IN': 'आवश्यक दस्तावेज़', 'mr-IN': 'आवश्यक कागदपत्रे', 'en-IN': 'Documents Required' } as Str,

    eligRow1: { 'hi-IN': 'ज़मीन का स्वामित्व सत्यापित', 'mr-IN': 'जमीन मालकी सत्यापित', 'en-IN': 'Land holding verified' } as Str,
    eligRow2: { 'hi-IN': 'व्यवसाय और राज्य पुष्टि', 'mr-IN': 'व्यवसाय आणि राज्य पुष्टी', 'en-IN': 'Occupation and state confirmed' } as Str,
    eligRow3: { 'hi-IN': 'आय पात्रता सीमा के भीतर', 'mr-IN': 'उत्पन्न पात्रता मर्यादेत', 'en-IN': 'Income within eligibility limit' } as Str,
    eligRow4: { 'hi-IN': 'सभी मानदंड पूरे', 'mr-IN': 'सर्व निकष पूर्ण', 'en-IN': 'All criteria met' } as Str,
    eligRow4Partial: { 'hi-IN': 'कुछ मानदंडों की पुष्टि बाकी', 'mr-IN': 'काही निकषांची पडताळणी बाकी', 'en-IN': 'Some criteria need verification' } as Str,

    modeOnline: { 'hi-IN': 'ऑनलाइन', 'mr-IN': 'ऑनलाइन', 'en-IN': 'online' } as Str,
    modeOffline: { 'hi-IN': 'ऑफलाइन', 'mr-IN': 'ऑफलाइन', 'en-IN': 'offline' } as Str,
    modeCSC: { 'hi-IN': 'CSC', 'mr-IN': 'CSC', 'en-IN': 'csc' } as Str,

    annual: { 'hi-IN': 'सालाना', 'mr-IN': 'वार्षिक', 'en-IN': 'Annual' } as Str,
    installments: { 'hi-IN': 'किस्तें', 'mr-IN': 'हप्ते', 'en-IN': 'Installments' } as Str,
    payments: { 'hi-IN': 'भुगतान', 'mr-IN': 'देयके', 'en-IN': 'Payments' } as Str,
    direct: { 'hi-IN': 'सीधे', 'mr-IN': 'थेट', 'en-IN': 'Direct' } as Str,
    bankTransfer: { 'hi-IN': 'बैंक ट्रांसफर', 'mr-IN': 'बँक हस्तांतरण', 'en-IN': 'Bank Transfer' } as Str,

    generateDoc: { 'hi-IN': '📋 तैयारी दस्तावेज़ बनाएं', 'mr-IN': '📋 तयारी दस्तऐवज बनवा', 'en-IN': '📋 Generate Preparation Doc' } as Str,
    saveScheme: { 'hi-IN': '⭐ योजना सहेजें', 'mr-IN': '⭐ योजना जतन करा', 'en-IN': '⭐ Save Scheme' } as Str,
    schemeSaved: { 'hi-IN': '✓ योजना सहेजी गई', 'mr-IN': '✓ योजना जतन केली', 'en-IN': '✓ Scheme Saved' } as Str,
    shareWA: { 'hi-IN': '💬 WhatsApp पर भेजें', 'mr-IN': '💬 WhatsApp वर पाठवा', 'en-IN': '💬 Share via WhatsApp' } as Str,
    officialSite: { 'hi-IN': '🔗 आधिकारिक वेबसाइट →', 'mr-IN': '🔗 अधिकृत वेबसाइट →', 'en-IN': '🔗 Official Website →' } as Str,

    comparing: { 'hi-IN': 'तुलना कर रहे हैं:', 'mr-IN': 'तुलना करत आहे:', 'en-IN': 'Comparing:' } as Str,
    compareNow: { 'hi-IN': 'अभी तुलना करें →', 'mr-IN': 'आता तुलना करा →', 'en-IN': 'Compare Now →' } as Str,
    clearAll: { 'hi-IN': 'सब हटाएं', 'mr-IN': 'सर्व काढा', 'en-IN': 'Clear all' } as Str,
    maxCompare: { 'hi-IN': 'अधिकतम 3 योजनाओं की तुलना की जा सकती है', 'mr-IN': 'जास्तीत जास्त 3 योजनांची तुलना करता येते', 'en-IN': 'Maximum 3 schemes can be compared' } as Str,

    noSchemesCompare: { 'hi-IN': 'तुलना के लिए कोई योजना नहीं चुनी गई', 'mr-IN': 'तुलनेसाठी कोणतीही योजना निवडली नाही', 'en-IN': 'No schemes selected for comparison' } as Str,
    compareHint: { 'hi-IN': 'योजना खोज में जाएं और किसी भी कार्ड पर +C बटन दबाएं। 3 योजनाओं तक तुलना करें।', 'mr-IN': 'योजना शोधमध्ये जा आणि कोणत्याही कार्डवर +C दाबा. 3 योजनांपर्यंत तुलना करा.', 'en-IN': 'Go to Scheme Search and click +C button on any card. Compare up to 3 schemes.' } as Str,
    goToSearch: { 'hi-IN': '← योजना खोज पर जाएं', 'mr-IN': '← योजना शोधावर जा', 'en-IN': '← Go to Scheme Search' } as Str,
    startPrep: { 'hi-IN': 'तैयारी शुरू करें →', 'mr-IN': 'तयारी सुरू करा →', 'en-IN': 'Start Preparation →' } as Str,
    compareCol: { 'hi-IN': 'तुलना', 'mr-IN': 'तुलना', 'en-IN': 'Compare' } as Str,

    cmpEligibility: { 'hi-IN': 'पात्रता', 'mr-IN': 'पात्रता', 'en-IN': 'Eligibility' } as Str,
    cmpMatchScore: { 'hi-IN': 'मिलान स्कोर', 'mr-IN': 'जुळणी स्कोअर', 'en-IN': 'Match Score' } as Str,
    cmpBenefit: { 'hi-IN': 'लाभ राशि', 'mr-IN': 'लाभाची रक्कम', 'en-IN': 'Benefit Amount' } as Str,
    cmpHowApply: { 'hi-IN': 'आवेदन कैसे करें', 'mr-IN': 'अर्ज कसा करावा', 'en-IN': 'How to Apply' } as Str,
    cmpDocuments: { 'hi-IN': 'दस्तावेज़', 'mr-IN': 'कागदपत्रे', 'en-IN': 'Documents' } as Str,
    cmpProcessing: { 'hi-IN': 'प्रसंस्करण समय', 'mr-IN': 'प्रक्रिया वेळ', 'en-IN': 'Processing Time' } as Str,
    cmpRejection: { 'hi-IN': 'अस्वीकृति जोखिम', 'mr-IN': 'नकार जोखीम', 'en-IN': 'Rejection Risk' } as Str,
    cmpRecommended: { 'hi-IN': 'अनुशंसित', 'mr-IN': 'शिफारस केलेले', 'en-IN': 'Recommended' } as Str,
    cmpAction: { 'hi-IN': 'कार्रवाई', 'mr-IN': 'कृती', 'en-IN': 'Action' } as Str,
    cmpStartHere: { 'hi-IN': '✓ यहाँ से शुरू करें', 'mr-IN': '✓ येथून सुरू करा', 'en-IN': '✓ Start Here' } as Str,
    cmpApplyNth: { 'hi-IN': (n) => `${n}. आवेदन करें`, 'mr-IN': (n) => `${n}. अर्ज करा`, 'en-IN': (n) => `Apply ${n}` } as StrFn1,
    cmpDocsCount: { 'hi-IN': (n) => `${n} दस्तावेज़`, 'mr-IN': (n) => `${n} कागदपत्रे`, 'en-IN': (n) => `${n} documents` } as StrFn1,
    lowRisk: { 'hi-IN': 'कम', 'mr-IN': 'कमी', 'en-IN': 'Low' } as Str,
    mediumRisk: { 'hi-IN': 'मध्यम', 'mr-IN': 'मध्यम', 'en-IN': 'Medium' } as Str,
    highRisk: { 'hi-IN': 'उच्च', 'mr-IN': 'उच्च', 'en-IN': 'High' } as Str,

    prepSubHead: { 'hi-IN': 'अपनी जानकारी भरें', 'mr-IN': 'तुमची माहिती भरा', 'en-IN': 'Create Your Profile' } as Str,
    prepSubDesc: { 'hi-IN': 'व्यक्तिगत आवेदन दस्तावेज़ बनाने के लिए हमें आपकी बुनियादी जानकारी चाहिए। इसमें 2 मिनट से कम समय लगेगा।', 'mr-IN': 'वैयक्तिक अर्ज दस्तऐवज तयार करण्यासाठी आम्हाला तुमची मूलभूत माहिती हवी आहे. यासाठी 2 मिनिटांपेक्षा कमी वेळ लागेल.', 'en-IN': 'To generate a personalised application document, we need your basic details. This takes less than 2 minutes.' } as Str,
    weNeed: { 'hi-IN': 'हमें चाहिए: ', 'mr-IN': 'आम्हाला हवे: ', 'en-IN': 'We need: ' } as Str,
    fillAndGenerate: { 'hi-IN': 'भरें और दस्तावेज़ बनाएं →', 'mr-IN': 'भरा आणि दस्तऐवज बनवा →', 'en-IN': 'Fill Details and Generate →' } as Str,
    useDemo: { 'hi-IN': 'डेमो प्रोफ़ाइल उपयोग करें (राजेश पाटिल — किसान)', 'mr-IN': 'डेमो प्रोफाइल वापरा (राजेश पाटील — शेतकरी)', 'en-IN': 'Use Demo Profile (Rajesh Patil — Farmer)' } as Str,

    trackerTitle: { 'hi-IN': 'आवेदन ट्रैकर', 'mr-IN': 'अर्ज ट्रॅकर', 'en-IN': 'Application Tracker' } as Str,
    trackerSub: { 'hi-IN': 'अपने आवेदनों की स्थिति देखें', 'mr-IN': 'तुमच्या अर्जांची स्थिती पहा', 'en-IN': 'Track status of your applications' } as Str,
    filterAll: { 'hi-IN': 'सभी', 'mr-IN': 'सर्व', 'en-IN': 'All' } as Str,
    filterPending: { 'hi-IN': 'लंबित', 'mr-IN': 'प्रलंबित', 'en-IN': 'Pending' } as Str,
    filterApproved: { 'hi-IN': 'स्वीकृत', 'mr-IN': 'मंजूर', 'en-IN': 'Approved' } as Str,
    filterAction: { 'hi-IN': 'कार्रवाई ज़रूरी', 'mr-IN': 'कृती आवश्यक', 'en-IN': 'Action Needed' } as Str,
    stepApplied: { 'hi-IN': 'आवेदन किया', 'mr-IN': 'अर्ज केला', 'en-IN': 'Applied' } as Str,
    stepReview: { 'hi-IN': 'समीक्षा में', 'mr-IN': 'समीक्षेत', 'en-IN': 'Under Review' } as Str,
    stepVerified: { 'hi-IN': 'सत्यापित', 'mr-IN': 'सत्यापित', 'en-IN': 'Verified' } as Str,
    stepDisbursed: { 'hi-IN': 'वितरित', 'mr-IN': 'वितरित', 'en-IN': 'Disbursed' } as Str,
    statusApproved: { 'hi-IN': '✓ स्वीकृत', 'mr-IN': '✓ मंजूर', 'en-IN': '✓ APPROVED' } as Str,
    statusDocs: { 'hi-IN': '⚠ दस्तावेज़ चाहिए', 'mr-IN': '⚠ कागदपत्रे हवीत', 'en-IN': '⚠ DOCS NEEDED' } as Str,
    statusPending: { 'hi-IN': '⏳ लंबित', 'mr-IN': '⏳ प्रलंबित', 'en-IN': '⏳ PENDING' } as Str,
    statusRejected: { 'hi-IN': '✗ अस्वीकृत', 'mr-IN': '✗ नाकारले', 'en-IN': '✗ REJECTED' } as Str,
    noRefYet: { 'hi-IN': 'अभी कोई संदर्भ नंबर नहीं', 'mr-IN': 'अद्याप संदर्भ क्रमांक नाही', 'en-IN': 'No reference number yet' } as Str,
    updateBtn: { 'hi-IN': 'अपडेट करें', 'mr-IN': 'अपडेट करा', 'en-IN': 'Update' } as Str,
    findCSCArrow: { 'hi-IN': 'CSC खोजें →', 'mr-IN': 'CSC शोधा →', 'en-IN': 'Find CSC →' } as Str,
    shareCheck: { 'hi-IN': 'भेजें ✓', 'mr-IN': 'पाठवा ✓', 'en-IN': 'Share ✓' } as Str,
    approvedShare: { 'hi-IN': (name) => `${name} — आवेदन स्वीकृत!`, 'mr-IN': (name) => `${name} — अर्ज मंजूर!`, 'en-IN': (name) => `${name} — Application APPROVED!` } as StrFn1,

    cscTitle: { 'hi-IN': 'CSC लोकेटर', 'mr-IN': 'CSC लोकेटर', 'en-IN': 'CSC Locator' } as Str,
    cscSearchPlaceholder: { 'hi-IN': 'क्षेत्र या पिनकोड से खोजें...', 'mr-IN': 'क्षेत्र किंवा पिनकोडने शोधा...', 'en-IN': 'Search by area or pincode...' } as Str,
    cscOpen: { 'hi-IN': 'खुला', 'mr-IN': 'उघडे', 'en-IN': 'Open' } as Str,
    cscClosed: { 'hi-IN': 'बंद', 'mr-IN': 'बंद', 'en-IN': 'Closed' } as Str,
    directions: { 'hi-IN': '📍 रास्ता', 'mr-IN': '📍 दिशा', 'en-IN': '📍 Directions' } as Str,
    callBtn: { 'hi-IN': '📞 कॉल', 'mr-IN': '📞 कॉल', 'en-IN': '📞 Call' } as Str,
    waBtn: { 'hi-IN': '💬 WhatsApp', 'mr-IN': '💬 WhatsApp', 'en-IN': '💬 WhatsApp' } as Str,
    waHelpText: { 'hi-IN': 'मुझे सरकारी योजना आवेदन में मदद चाहिए', 'mr-IN': 'मला सरकारी योजना अर्जासाठी मदत हवी आहे', 'en-IN': 'I need help with government scheme application' } as Str,
    openInMaps: { 'hi-IN': 'Google Maps में खोलें', 'mr-IN': 'Google Maps मध्ये उघडा', 'en-IN': 'Open in Google Maps' } as Str,
    mapsHint: { 'hi-IN': 'अपने वर्तमान स्थान के पास सभी CSC केंद्र खोजने के लिए नीचे बटन दबाएं।', 'mr-IN': 'तुमच्या सध्याच्या स्थानाजवळील सर्व CSC केंद्रे शोधण्यासाठी खालील बटण दाबा.', 'en-IN': 'Click button below to find all CSC centres near your current location on Google Maps.' } as Str,
    openMaps: { 'hi-IN': '📍 नज़दीकी CSC केंद्र खोजें →', 'mr-IN': '📍 जवळचे CSC केंद्र शोधा →', 'en-IN': '📍 Find CSC Centres Near Me →' } as Str,
    mapsAltHint: { 'hi-IN': 'या क्षेत्र या पिनकोड से खोजने के लिए बाईं ओर की सूची का उपयोग करें।', 'mr-IN': 'किंवा क्षेत्र किंवा पिनकोडने शोधण्यासाठी डावीकडील यादी वापरा.', 'en-IN': 'Or use list on the left to find by area or pincode.' } as Str,

    helplineTitle: { 'hi-IN': 'सरकारी हेल्पलाइन', 'mr-IN': 'सरकारी हेल्पलाइन', 'en-IN': 'Government Helplines' } as Str,
    helplineSub: { 'hi-IN': 'सभी केंद्र सरकार योजनाओं के लिए आधिकारिक संपर्क नंबर', 'mr-IN': 'सर्व केंद्र सरकार योजनांसाठी अधिकृत संपर्क क्रमांक', 'en-IN': 'Official contact numbers for all central government schemes' } as Str,
    callNow: { 'hi-IN': '📞 अभी कॉल करें', 'mr-IN': '📞 आता कॉल करा', 'en-IN': '📞 Call Now' } as Str,

    backHome: { 'hi-IN': 'होम पर वापस जाएं', 'mr-IN': 'मुख्यपृष्ठावर परत जा', 'en-IN': 'Back to Home' } as Str,
    loginSave: { 'hi-IN': 'लॉगिन / प्रोफ़ाइल सहेजें', 'mr-IN': 'लॉगिन / प्रोफाइल जतन करा', 'en-IN': 'Login / Save Profile' } as Str,
    profileSaved: { 'hi-IN': (n) => `✓ ${n} की प्रोफ़ाइल`, 'mr-IN': (n) => `✓ ${n} ची प्रोफाइल`, 'en-IN': (n) => `✓ ${n}'s Profile` } as StrFn1,
    profileSavedAlert: { 'hi-IN': 'प्रोफ़ाइल सहेजी गई!', 'mr-IN': 'प्रोफाइल जतन केली!', 'en-IN': 'Profile saved!' } as Str,
    simpleMode: { 'hi-IN': 'सरल', 'mr-IN': 'सोपे', 'en-IN': 'Simple' } as Str,
    fullMode: { 'hi-IN': 'फुल मोड', 'mr-IN': 'फुल मोड', 'en-IN': 'Full Mode' } as Str,

    panelTitles: {
      schemes: { 'hi-IN': 'योजना खोज', 'mr-IN': 'योजना शोध', 'en-IN': 'Scheme Search' } as Str,
      compare: { 'hi-IN': 'योजनाओं की तुलना', 'mr-IN': 'योजनांची तुलना', 'en-IN': 'Compare Schemes' } as Str,
      prep: { 'hi-IN': 'आवेदन तैयारी', 'mr-IN': 'अर्ज तयारी', 'en-IN': 'Application Preparation' } as Str,
      tracker: { 'hi-IN': 'आवेदन ट्रैकर', 'mr-IN': 'अर्ज ट्रॅकर', 'en-IN': 'Application Tracker' } as Str,
      csc: { 'hi-IN': 'CSC लोकेटर', 'mr-IN': 'CSC लोकेटर', 'en-IN': 'CSC Locator' } as Str,
      helpline: { 'hi-IN': 'हेल्पलाइन', 'mr-IN': 'हेल्पलाइन', 'en-IN': 'Helplines' } as Str,
    },
    panelSubs: {
      schemes: { 'hi-IN': 'सक्रिय', 'mr-IN': 'सक्रिय', 'en-IN': 'Active' } as Str,
      tracker: { 'hi-IN': 'आवेदन', 'mr-IN': 'अर्ज', 'en-IN': 'applications' } as Str,
      csc: { 'hi-IN': 'पुणे, महाराष्ट्र के पास', 'mr-IN': 'पुणे, महाराष्ट्र जवळ', 'en-IN': 'Near Pune, Maharashtra' } as Str,
      helpline: { 'hi-IN': 'अखिल भारत', 'mr-IN': 'संपूर्ण भारत', 'en-IN': 'All India' } as Str,
      compare: { 'hi-IN': (n: number) => `${n} योजनाएं चुनी गईं`, 'mr-IN': (n: number) => `${n} योजना निवडल्या`, 'en-IN': (n: number) => `${n} schemes selected` } as StrFn1,
    },

    labelName: { 'hi-IN': 'पूरा नाम', 'mr-IN': 'पूर्ण नाव', 'en-IN': 'Full Name' } as Str,
    labelAge: { 'hi-IN': 'आयु', 'mr-IN': 'वय', 'en-IN': 'Age' } as Str,
    labelState: { 'hi-IN': 'राज्य', 'mr-IN': 'राज्य', 'en-IN': 'State' } as Str,
    labelOccupation: { 'hi-IN': 'व्यवसाय', 'mr-IN': 'व्यवसाय', 'en-IN': 'Occupation' } as Str,
    labelIncome: { 'hi-IN': 'वार्षिक आय', 'mr-IN': 'वार्षिक उत्पन्न', 'en-IN': 'Annual Income' } as Str,
    labelLand: { 'hi-IN': 'ज़मीन का आकार', 'mr-IN': 'जमिनीचा आकार', 'en-IN': 'Land Size' } as Str,

    // Application Preparation Form (scheme-specific sample application)
    labelGender: { 'hi-IN': 'लिंग', 'mr-IN': 'लिंग', 'en-IN': 'Gender' } as Str,
    labelDistrict: { 'hi-IN': 'ज़िला', 'mr-IN': 'जिल्हा', 'en-IN': 'District' } as Str,
    labelMobile: { 'hi-IN': 'मोबाइल नंबर', 'mr-IN': 'मोबाइल क्रमांक', 'en-IN': 'Mobile Number' } as Str,
    labelAadhaarBankLinked: { 'hi-IN': 'आधार-बैंक लिंक स्थिति', 'mr-IN': 'आधार-बँक लिंक स्थिती', 'en-IN': 'Aadhaar-Linked Bank Status' } as Str,
    labelFarmerCategory: { 'hi-IN': 'किसान श्रेणी', 'mr-IN': 'शेतकरी प्रवर्ग', 'en-IN': 'Farmer Category' } as Str,
    labelLandOwnership: { 'hi-IN': 'ज़मीन स्वामित्व स्थिति', 'mr-IN': 'जमीन मालकी स्थिती', 'en-IN': 'Land Ownership Status' } as Str,
    labelLandArea: { 'hi-IN': 'ज़मीन का क्षेत्रफल (एकड़ में)', 'mr-IN': 'जमिनीचे क्षेत्रफळ (एकरमध्ये)', 'en-IN': 'Land Area (in acres)' } as Str,
    labelSurveyNumber: { 'hi-IN': 'सर्वे / गट नंबर', 'mr-IN': 'सर्वे / गट क्रमांक', 'en-IN': 'Survey / Gat Number' } as Str,
    labelBankName: { 'hi-IN': 'बैंक का नाम', 'mr-IN': 'बँकेचे नाव', 'en-IN': 'Bank Name' } as Str,
    labelAccountNumber: { 'hi-IN': 'खाता संख्या', 'mr-IN': 'खाते क्रमांक', 'en-IN': 'Account Number' } as Str,
    labelIfsc: { 'hi-IN': 'IFSC कोड', 'mr-IN': 'IFSC कोड', 'en-IN': 'IFSC Code' } as Str,

    genderMale: { 'hi-IN': 'पुरुष', 'mr-IN': 'पुरुष', 'en-IN': 'Male' } as Str,
    genderFemale: { 'hi-IN': 'महिला', 'mr-IN': 'महिला', 'en-IN': 'Female' } as Str,
    genderOther: { 'hi-IN': 'अन्य', 'mr-IN': 'इतर', 'en-IN': 'Other' } as Str,

    farmerCategoryMarginal: { 'hi-IN': 'सीमांत किसान (1 हेक्टेयर से कम)', 'mr-IN': 'सीमांत शेतकरी (1 हेक्टरपेक्षा कमी)', 'en-IN': 'Marginal Farmer (below 1 hectare)' } as Str,
    farmerCategorySmall: { 'hi-IN': 'लघु किसान (1–2 हेक्टेयर)', 'mr-IN': 'अल्पभूधारक शेतकरी (1–2 हेक्टर)', 'en-IN': 'Small Farmer (1–2 hectares)' } as Str,
    farmerCategoryOther: { 'hi-IN': 'अन्य किसान (2 हेक्टेयर से अधिक)', 'mr-IN': 'इतर शेतकरी (2 हेक्टरपेक्षा जास्त)', 'en-IN': 'Other Farmer (above 2 hectares)' } as Str,

    landOwnershipOwned: { 'hi-IN': 'स्वयं के स्वामित्व में', 'mr-IN': 'स्वतःच्या मालकीची', 'en-IN': 'Owned' } as Str,
    landOwnershipJoint: { 'hi-IN': 'संयुक्त स्वामित्व', 'mr-IN': 'संयुक्त मालकी', 'en-IN': 'Joint Ownership' } as Str,
    landOwnershipLeased: { 'hi-IN': 'पट्टे पर ली गई', 'mr-IN': 'भाड्याने घेतलेली', 'en-IN': 'Leased' } as Str,

    yesOption: { 'hi-IN': 'हाँ', 'mr-IN': 'हो', 'en-IN': 'Yes' } as Str,
    noOption: { 'hi-IN': 'नहीं', 'mr-IN': 'नाही', 'en-IN': 'No' } as Str,
    selectPlaceholder: { 'hi-IN': 'चुनें', 'mr-IN': 'निवडा', 'en-IN': 'Select' } as Str,

    formSectionPersonal: { 'hi-IN': 'व्यक्तिगत जानकारी', 'mr-IN': 'वैयक्तिक माहिती', 'en-IN': 'Personal Details' } as Str,
    formSectionLand: { 'hi-IN': 'ज़मीन का विवरण', 'mr-IN': 'जमिनीचा तपशील', 'en-IN': 'Land Details' } as Str,
    formSectionBank: { 'hi-IN': 'बैंक विवरण', 'mr-IN': 'बँक तपशील', 'en-IN': 'Bank Details' } as Str,

    validationRequired: { 'hi-IN': 'यह जानकारी आवश्यक है', 'mr-IN': 'ही माहिती आवश्यक आहे', 'en-IN': 'This field is required' } as Str,
    validationMobile: { 'hi-IN': 'कृपया 10 अंकों का सही मोबाइल नंबर डालें', 'mr-IN': 'कृपया 10 अंकी योग्य मोबाइल क्रमांक टाका', 'en-IN': 'Please enter a valid 10-digit mobile number' } as Str,
    validationIfsc: { 'hi-IN': 'कृपया सही IFSC कोड डालें (जैसे SBIN0001234)', 'mr-IN': 'कृपया योग्य IFSC कोड टाका (उदा. SBIN0001234)', 'en-IN': 'Please enter a valid IFSC code (e.g. SBIN0001234)' } as Str,
    validationLandArea: { 'hi-IN': 'कृपया ज़मीन का क्षेत्रफल संख्या में डालें', 'mr-IN': 'कृपया जमिनीचे क्षेत्रफळ संख्येत टाका', 'en-IN': 'Please enter the land area as a number' } as Str,
    validationFixErrors: { 'hi-IN': 'आगे बढ़ने से पहले ऊपर दी गई गलतियों को ठीक करें।', 'mr-IN': 'पुढे जाण्यापूर्वी वरील चुका दुरुस्त करा.', 'en-IN': 'Please fix the errors above before continuing.' } as Str,

    applicationFormTitle: { 'hi-IN': 'आवेदन फॉर्म', 'mr-IN': 'अर्ज फॉर्म', 'en-IN': 'Application Form' } as Str,
    applicationFormSubtitle: {
      'hi-IN': 'यह जानकारी दस्तावेज़ जाँच के दौरान आपके नाम से मिलान करने में मदद करेगी।',
      'mr-IN': 'ही माहिती कागदपत्र तपासणी दरम्यान तुमच्या नावाशी जुळवण्यास मदत करेल.',
      'en-IN': 'This information will help match your name during the document check.',
    } as Str,
    requiredDocumentsForScheme: { 'hi-IN': 'इस योजना के लिए आवश्यक दस्तावेज़', 'mr-IN': 'या योजनेसाठी आवश्यक कागदपत्रे', 'en-IN': 'Required Documents for this Scheme' } as Str,
    iHaveThisDocument: { 'hi-IN': 'मेरे पास यह दस्तावेज़ है', 'mr-IN': 'माझ्याकडे हे कागदपत्र आहे', 'en-IN': 'I have this document' } as Str,
    checkDocumentReadinessBtn: { 'hi-IN': 'दस्तावेज़ तैयारी जाँचें', 'mr-IN': 'कागदपत्र तयारी तपासा', 'en-IN': 'Check Document Readiness' } as Str,
    backToOverview: { 'hi-IN': '← अवलोकन पर वापस जाएं', 'mr-IN': '← आढाव्याकडे परत जा', 'en-IN': '← Back to Overview' } as Str,
  },

  // ── LANDING PAGE ────────────────────────────────────────────
  landing: {
    navSchemes: { 'hi-IN': 'योजनाएं', 'mr-IN': 'योजना', 'en-IN': 'Schemes', 'ta-IN': 'திட்டங்கள்', 'te-IN': 'పథకాలు', 'kn-IN': 'ಯೋಜನೆಗಳು', 'ml-IN': 'പദ്ധതികൾ', 'bn-IN': 'প্রকল্প', 'gu-IN': 'યોજનાઓ', 'pa-IN': 'ਯੋਜਨਾਵਾਂ' } as Str,
    navHow: { 'hi-IN': 'यह कैसे काम करता है', 'mr-IN': 'हे कसे कार्य करते', 'en-IN': 'How it Works', 'ta-IN': 'இது எப்படி வேலை செய்கிறது', 'te-IN': 'ఇది ఎలా పనిచేస్తుంది', 'kn-IN': 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ', 'ml-IN': 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു', 'bn-IN': 'এটি কীভাবে কাজ করে', 'gu-IN': 'આ કેવી રીતે કાર્ય કરે છે', 'pa-IN': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ' } as Str,
    navAbout: { 'hi-IN': 'हमारे बारे में', 'mr-IN': 'आमच्याबद्दल', 'en-IN': 'About', 'ta-IN': 'எங்களைப் பற்றி', 'te-IN': 'మా గురించి', 'kn-IN': 'ನಮ್ಮ ಬಗ್ಗೆ', 'ml-IN': 'ഞങ്ങളെക്കുറിച്ച്', 'bn-IN': 'আমাদের সম্পর্কে', 'gu-IN': 'અમારા વિશે', 'pa-IN': 'ਸਾਡੇ ਬਾਰੇ' } as Str,
    navHelp: { 'hi-IN': 'मदद', 'mr-IN': 'मदत', 'en-IN': 'Help', 'ta-IN': 'உதவி', 'te-IN': 'సహాయం', 'kn-IN': 'ಸಹಾಯ', 'ml-IN': 'സഹായം', 'bn-IN': 'সাহায্য', 'gu-IN': 'મદદ', 'pa-IN': 'ਮਦਦ' } as Str,
    login: { 'hi-IN': 'लॉगिन', 'mr-IN': 'लॉगिन', 'en-IN': 'Login', 'ta-IN': 'உள்நுழைவு', 'te-IN': 'లాగిన్', 'kn-IN': 'ಲಾಗಿನ್', 'ml-IN': 'ലോഗിൻ', 'bn-IN': 'লগইন', 'gu-IN': 'લોગિન', 'pa-IN': 'ਲਾਗਇਨ' } as Str,
    tagline: { 'hi-IN': 'सरकारी योजना खोजक', 'mr-IN': 'सरकारी योजना शोधक', 'en-IN': 'Government Scheme Finder', 'ta-IN': 'அரசு திட்ட கண்டுபிடிப்பாளர்', 'te-IN': 'ప్రభుత్వ పథక అన్వేషకుడు', 'kn-IN': 'ಸರ್ಕಾರಿ ಯೋಜನೆ ಶೋಧಕ', 'ml-IN': 'സർക്കാർ പദ്ധതി കണ്ടെത്തൽ', 'bn-IN': 'সরকারি প্রকল্প খুঁজুন', 'gu-IN': 'સરકારી યોજના શોધક', 'pa-IN': 'ਸਰਕਾਰੀ ਯੋਜਨਾ ਖੋਜੀ' } as Str,

    badgeAccurate: { 'hi-IN': 'सटीक', 'mr-IN': 'अचूक', 'en-IN': 'Accurate', 'ta-IN': 'துல்லியமான', 'te-IN': 'ఖచ్చితమైన', 'kn-IN': 'ನಿಖರ', 'ml-IN': 'കൃത്യമായ', 'bn-IN': 'নির্ভুল', 'gu-IN': 'સચોટ', 'pa-IN': 'ਸਟੀਕ' } as Str,
    badgeFree: { 'hi-IN': 'मुफ्त', 'mr-IN': 'मोफत', 'en-IN': 'Free', 'ta-IN': 'இலவசம்', 'te-IN': 'ఉచితం', 'kn-IN': 'ಉಚಿತ', 'ml-IN': 'സൗജന്യം', 'bn-IN': 'বিনামূল্যে', 'gu-IN': 'મફત', 'pa-IN': 'ਮੁਫ਼ਤ' } as Str,
    badgeLanguage: { 'hi-IN': 'आपकी भाषा में', 'mr-IN': 'तुमच्या भाषेत', 'en-IN': 'In your language', 'ta-IN': 'உங்கள் மொழியில்', 'te-IN': 'మీ భాషలో', 'kn-IN': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ', 'ml-IN': 'നിങ്ങളുടെ ഭാഷയിൽ', 'bn-IN': 'আপনার ভাষায়', 'gu-IN': 'તમારી ભાષામાં', 'pa-IN': 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ' } as Str,

    headlineHi: { 'hi-IN': 'सुविधा सबके लिए।', 'mr-IN': 'सुविधा सबके लिए।', 'en-IN': 'सुविधा सबके लिए।', 'ta-IN': 'सुविधा सबके लिए।', 'te-IN': 'सुविधा सबके लिए।', 'kn-IN': 'सुविधा सबके लिए।', 'ml-IN': 'सुविधा सबके लिए।', 'bn-IN': 'सुविधा सबके लिए।', 'gu-IN': 'सुविधा सबके लिए।', 'pa-IN': 'सुविधा सबके लिए।' } as Str,
    headlineEn: { 'hi-IN': 'सभी के लिए कल्याण।', 'mr-IN': 'सर्वांसाठी कल्याण।', 'en-IN': 'Welfare for all.', 'ta-IN': 'அனைவருக்கும் நலன்.', 'te-IN': 'అందరికీ సంక్షేమం.', 'kn-IN': 'ಎಲ್ಲರಿಗೂ ಕಲ್ಯಾಣ.', 'ml-IN': 'എല്ലാവർക്കും ക്ഷേമം.', 'bn-IN': 'সবার জন্য কল্যাণ।', 'gu-IN': 'બધા માટે કલ્યાણ.', 'pa-IN': 'ਸਭ ਲਈ ਭਲਾਈ।' } as Str,
    subline: {
      'hi-IN': 'अपनी स्थिति सरल शब्दों में बताएं — किसी भी भारतीय भाषा में। हम आपको हर उस योजना से जोड़ते हैं जिसके आप पात्र हैं और दिखाते हैं कि उसका दावा कैसे करें।',
      'mr-IN': 'तुमची परिस्थिती सोप्या शब्दांत सांगा — कोणत्याही भारतीय भाषेत. आम्ही तुम्हाला तुम्ही पात्र असलेल्या प्रत्येक योजनेशी जोडतो आणि ती कशी मिळवायची ते दाखवतो.',
      'en-IN': 'Tell us your situation in simple words — in any Indian language. We match you to every scheme you qualify for and show you exactly how to claim it.',
      'ta-IN': 'உங்கள் நிலையை எளிய வார்த்தைகளில் சொல்லுங்கள் — எந்த இந்திய மொழியிலும். நீங்கள் தகுதியுள்ள ஒவ்வொரு திட்டத்துடனும் உங்களை இணைத்து, அதை எப்படி பெறுவது என்று காட்டுகிறோம்.',
      'te-IN': 'మీ పరిస్థితిని సరళమైన మాటల్లో చెప్పండి — ఏ భారతీయ భాషలోనైనా. మీరు అర్హత పొందిన ప్రతి పథకంతో మిమ్మల్ని అనుసంధానించి, దానిని ఎలా క్లెయిమ్ చేయాలో చూపిస్తాము.',
      'kn-IN': 'ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯನ್ನು ಸರಳ ಪದಗಳಲ್ಲಿ ಹೇಳಿ — ಯಾವುದೇ ಭಾರತೀಯ ಭಾಷೆಯಲ್ಲಿ. ನೀವು ಅರ್ಹರಾಗಿರುವ ಪ್ರತಿ ಯೋಜನೆಗೆ ನಿಮ್ಮನ್ನು ಹೊಂದಿಸಿ ಅದನ್ನು ಹೇಗೆ ಪಡೆಯುವುದು ಎಂದು ತೋರಿಸುತ್ತೇವೆ.',
      'ml-IN': 'നിങ്ങളുടെ സാഹചര്യം ലളിതമായ വാക്കുകളിൽ പറയൂ — ഏത് ഇന്ത്യൻ ഭാഷയിലും. നിങ്ങൾക്ക് അർഹതയുള്ള എല്ലാ പദ്ധതിയുമായി നിങ്ങളെ ബന്ധിപ്പിച്ച്, അത് എങ്ങനെ നേടാമെന്ന് കാണിക്കുന്നു.',
      'bn-IN': 'আপনার পরিস্থিতি সহজ কথায় বলুন — যেকোনো ভারতীয় ভাষায়। আমরা আপনাকে যোগ্য প্রতিটি প্রকল্পের সাথে যুক্ত করি এবং কীভাবে তা দাবি করবেন তা দেখাই।',
      'gu-IN': 'તમારી પરિસ્થિતિ સરળ શબ્દોમાં જણાવો — કોઈપણ ભારતીય ભાષામાં. અમે તમને તમે પાત્ર છો તે દરેક યોજના સાથે જોડીએ છીએ અને તે કેવી રીતે મેળવવી તે બતાવીએ છીએ.',
      'pa-IN': 'ਆਪਣੀ ਸਥਿਤੀ ਸਧਾਰਨ ਸ਼ਬਦਾਂ ਵਿੱਚ ਦੱਸੋ — ਕਿਸੇ ਵੀ ਭਾਰਤੀ ਭਾਸ਼ਾ ਵਿੱਚ। ਅਸੀਂ ਤੁਹਾਨੂੰ ਹਰ ਉਸ ਯੋਜਨਾ ਨਾਲ ਜੋੜਦੇ ਹਾਂ ਜਿਸ ਲਈ ਤੁਸੀਂ ਯੋਗ ਹੋ ਅਤੇ ਦਿਖਾਉਂਦੇ ਹਾਂ ਕਿ ਇਸਦਾ ਦਾਅਵਾ ਕਿਵੇਂ ਕਰਨਾ ਹੈ।',
    } as Str,
    searchPlaceholder: {
      'hi-IN': 'मैं 45 साल का किसान हूं... / मैं 60 साल की विधवा हूं...',
      'mr-IN': 'मी 45 वर्षांचा शेतकरी आहे... / मी 60 वर्षांची विधवा आहे...',
      'en-IN': 'I am a 45-year-old farmer... / I am a 60-year-old widow...',
      'ta-IN': 'நான் 45 வயது விவசாயி... / நான் 60 வயது விதவை...',
      'te-IN': 'నేను 45 సంవత్సరాల రైతుని... / నేను 60 సంవత్సరాల వితంతువును...',
      'kn-IN': 'ನಾನು 45 ವರ್ಷದ ರೈತ... / ನಾನು 60 ವರ್ಷದ ವಿಧವೆ...',
      'ml-IN': 'ഞാൻ 45 വയസ്സുള്ള കർഷകനാണ്... / ഞാൻ 60 വയസ്സുള്ള വിധവയാണ്...',
      'bn-IN': 'আমি ৪৫ বছর বয়সী একজন কৃষক... / আমি ৬০ বছর বয়সী একজন বিধবা...',
      'gu-IN': 'હું 45 વર્ષનો ખેડૂત છું... / હું 60 વર્ષની વિધવા છું...',
      'pa-IN': 'ਮੈਂ 45 ਸਾਲ ਦਾ ਕਿਸਾਨ ਹਾਂ... / ਮੈਂ 60 ਸਾਲ ਦੀ ਵਿਧਵਾ ਹਾਂ...',
    } as Str,
    findSchemes: { 'hi-IN': 'योजनाएं खोजें →', 'mr-IN': 'योजना शोधा →', 'en-IN': 'Find Schemes →', 'ta-IN': 'திட்டங்களைத் தேடு →', 'te-IN': 'పథకాలు వెతకండి →', 'kn-IN': 'ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ →', 'ml-IN': 'പദ്ധതികൾ കണ്ടെത്തുക →', 'bn-IN': 'প্রকল্প খুঁজুন →', 'gu-IN': 'યોજનાઓ શોધો →', 'pa-IN': 'ਯੋਜਨਾਵਾਂ ਲੱਭੋ →' } as Str,
    chipFarmer: { 'hi-IN': 'किसान', 'mr-IN': 'शेतकरी', 'en-IN': 'Farmer', 'ta-IN': 'விவசாயி', 'te-IN': 'రైతు', 'kn-IN': 'ರೈತ', 'ml-IN': 'കർഷകൻ', 'bn-IN': 'কৃষক', 'gu-IN': 'ખેડૂત', 'pa-IN': 'ਕਿਸਾਨ' } as Str,
    chipSenior: { 'hi-IN': 'वरिष्ठ नागरिक', 'mr-IN': 'ज्येष्ठ नागरिक', 'en-IN': 'Senior Citizen', 'ta-IN': 'மூத்த குடிமகன்', 'te-IN': 'సీనియర్ సిటిజన్', 'kn-IN': 'ಹಿರಿಯ ನಾಗರಿಕ', 'ml-IN': 'മുതിർന്ന പൗരൻ', 'bn-IN': 'প্রবীণ নাগরিক', 'gu-IN': 'વરિષ્ઠ નાગરિક', 'pa-IN': 'ਸੀਨੀਅਰ ਨਾਗਰਿਕ' } as Str,
    chipWoman: { 'hi-IN': 'अकेली महिला', 'mr-IN': 'एकल महिला', 'en-IN': 'Single Woman', 'ta-IN': 'தனி பெண்', 'te-IN': 'ఒంటరి మహిళ', 'kn-IN': 'ಒಂಟಿ ಮಹಿಳೆ', 'ml-IN': 'ഏക സ്ത്രീ', 'bn-IN': 'একক নারী', 'gu-IN': 'એકલી મહિલા', 'pa-IN': 'ਇਕੱਲੀ ਔਰਤ' } as Str,
    chipStudent: { 'hi-IN': 'छात्र', 'mr-IN': 'विद्यार्थी', 'en-IN': 'Student', 'ta-IN': 'மாணவர்', 'te-IN': 'విద్యార్థి', 'kn-IN': 'ವಿದ್ಯಾರ್ಥಿ', 'ml-IN': 'വിദ്യാർത്ഥി', 'bn-IN': 'শিক্ষার্থী', 'gu-IN': 'વિદ્યાર્થી', 'pa-IN': 'ਵਿਦਿਆਰਥੀ' } as Str,
    chipWage: { 'hi-IN': 'दिहाड़ी मजदूर', 'mr-IN': 'रोजंदारी कामगार', 'en-IN': 'Daily Wage Worker', 'ta-IN': 'தினக்கூலி தொழிலாளி', 'te-IN': 'రోజువారీ కూలీ', 'kn-IN': 'ದಿನಗೂಲಿ ಕಾರ್ಮಿಕ', 'ml-IN': 'ദിവസക്കൂലിക്കാരൻ', 'bn-IN': 'দৈনিক মজুর', 'gu-IN': 'રોજમદાર મજૂર', 'pa-IN': 'ਦਿਹਾੜੀਦਾਰ ਮਜ਼ਦੂਰ' } as Str,
    chipHousing: { 'hi-IN': 'घर चाहिए', 'mr-IN': 'घर हवे', 'en-IN': 'Need Housing', 'ta-IN': 'வீடு தேவை', 'te-IN': 'ఇల్లు కావాలి', 'kn-IN': 'ಮನೆ ಬೇಕು', 'ml-IN': 'വീട് വേണം', 'bn-IN': 'বাড়ি প্রয়োজন', 'gu-IN': 'ઘર જોઈએ', 'pa-IN': 'ਘਰ ਚਾਹੀਦਾ' } as Str,
    speakLang: { 'hi-IN': 'अपनी भाषा में बोलें', 'mr-IN': 'तुमच्या भाषेत बोला', 'en-IN': 'Speak in your language', 'ta-IN': 'உங்கள் மொழியில் பேசுங்கள்', 'te-IN': 'మీ భాషలో మాట్లాడండి', 'kn-IN': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ', 'ml-IN': 'നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കൂ', 'bn-IN': 'আপনার ভাষায় বলুন', 'gu-IN': 'તમારી ભાષામાં બોલો', 'pa-IN': 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ' } as Str,
    langList: { 'hi-IN': 'हिंदी · अंग्रेज़ी · मराठी + 9 और', 'mr-IN': 'हिंदी · इंग्रजी · मराठी + 9 अधिक', 'en-IN': 'Hindi · English · Marathi + 9 more', 'ta-IN': 'தமிழ் · ஆங்கிலம் · இந்தி + 9 மேலும்', 'te-IN': 'తెలుగు · ఆంగ్లం · హిందీ + 9 మరిన్ని', 'kn-IN': 'ಕನ್ನಡ · ಇಂಗ್ಲಿಷ್ · ಹಿಂದಿ + 9 ಇನ್ನಷ್ಟು', 'ml-IN': 'മലയാളം · ഇംഗ്ലീഷ് · ഹിന്ദി + 9 കൂടുതൽ', 'bn-IN': 'বাংলা · ইংরেজি · হিন্দি + ৯টি আরও', 'gu-IN': 'ગુજરાતી · અંગ્રેજી · હિન્દી + 9 વધુ', 'pa-IN': 'ਪੰਜਾਬੀ · ਅੰਗਰੇਜ਼ੀ · ਹਿੰਦੀ + 9 ਹੋਰ' } as Str,
    trust1: { 'hi-IN': '500+ योजनाएं शामिल', 'mr-IN': '500+ योजना समाविष्ट', 'en-IN': '500+ schemes covered', 'ta-IN': '500+ திட்டங்கள் உள்ளடக்கம்', 'te-IN': '500+ పథకాలు కవర్ చేయబడ్డాయి', 'kn-IN': '500+ ಯೋಜನೆಗಳು ಒಳಗೊಂಡಿದೆ', 'ml-IN': '500+ പദ്ധതികൾ ഉൾപ്പെടുന്നു', 'bn-IN': '৫০০+ প্রকল্প অন্তর্ভুক্ত', 'gu-IN': '500+ યોજનાઓ આવરી લેવાયેલી', 'pa-IN': '500+ ਯੋਜਨਾਵਾਂ ਸ਼ਾਮਲ' } as Str,
    trust2: { 'hi-IN': 'केंद्र और राज्य सरकारें', 'mr-IN': 'केंद्र आणि राज्य सरकारे', 'en-IN': 'Central and state governments', 'ta-IN': 'மத்திய மற்றும் மாநில அரசுகள்', 'te-IN': 'కేంద్ర మరియు రాష్ట్ర ప్రభుత్వాలు', 'kn-IN': 'ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರಗಳು', 'ml-IN': 'കേന്ദ്ര, സംസ്ഥാന സർക്കാരുകൾ', 'bn-IN': 'কেন্দ্র ও রাজ্য সরকার', 'gu-IN': 'કેન્દ્ર અને રાજ્ય સરકારો', 'pa-IN': 'ਕੇਂਦਰ ਅਤੇ ਰਾਜ ਸਰਕਾਰਾਂ' } as Str,
    trust3: { 'hi-IN': 'आधिकारिक स्रोतों से अद्यतन', 'mr-IN': 'अधिकृत स्रोतांकडून अद्ययावत', 'en-IN': 'Updated from official sources', 'ta-IN': 'அதிகாரப்பூர்வ ஆதாரங்களிலிருந்து புதுப்பிக்கப்பட்டது', 'te-IN': 'అధికారిక వనరుల నుండి నవీకరించబడింది', 'kn-IN': 'ಅಧಿಕೃತ ಮೂಲಗಳಿಂದ ನವೀಕರಿಸಲಾಗಿದೆ', 'ml-IN': 'ഔദ്യോഗിക സ്രോതസ്സുകളിൽ നിന്ന് പുതുക്കിയത്', 'bn-IN': 'সরকারি সূত্র থেকে হালনাগাদ', 'gu-IN': 'સત્તાવાર સ્રોતોમાંથી અપડેટ', 'pa-IN': 'ਅਧਿਕਾਰਤ ਸਰੋਤਾਂ ਤੋਂ ਅੱਪਡੇਟ' } as Str,

    citizenCenter: { 'hi-IN': 'नागरिक', 'mr-IN': 'नागरिक', 'en-IN': 'The Citizen', 'ta-IN': 'குடிமகன்', 'te-IN': 'పౌరుడు', 'kn-IN': 'ನಾಗರಿಕ', 'ml-IN': 'പൗരൻ', 'bn-IN': 'নাগরিক', 'gu-IN': 'નાગરિક', 'pa-IN': 'ਨਾਗਰਿਕ' } as Str,
    citizenSub: { 'hi-IN': 'आप केंद्र में हैं', 'mr-IN': 'तुम्ही केंद्रस्थानी आहात', 'en-IN': 'You are at the center', 'ta-IN': 'நீங்கள் மையத்தில் இருக்கிறீர்கள்', 'te-IN': 'మీరు కేంద్రంలో ఉన్నారు', 'kn-IN': 'ನೀವು ಕೇಂದ್ರದಲ್ಲಿದ್ದೀರಿ', 'ml-IN': 'നിങ്ങൾ കേന്ദ്രത്തിലാണ്', 'bn-IN': 'আপনি কেন্দ্রে আছেন', 'gu-IN': 'તમે કેન્દ્રમાં છો', 'pa-IN': 'ਤੁਸੀਂ ਕੇਂਦਰ ਵਿੱਚ ਹੋ' } as Str,

    statSchemes: { 'hi-IN': 'सरकारी योजनाएं', 'mr-IN': 'सरकारी योजना', 'en-IN': 'Government schemes', 'ta-IN': 'அரசு திட்டங்கள்', 'te-IN': 'ప్రభుత్వ పథకాలు', 'kn-IN': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', 'ml-IN': 'സർക്കാർ പദ്ധതികൾ', 'bn-IN': 'সরকারি প্রকল্প', 'gu-IN': 'સરકારી યોજનાઓ', 'pa-IN': 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ' } as Str,
    statLanguages: { 'hi-IN': 'भारतीय भाषाएं', 'mr-IN': 'भारतीय भाषा', 'en-IN': 'Indian languages', 'ta-IN': 'இந்திய மொழிகள்', 'te-IN': 'భారతీయ భాషలు', 'kn-IN': 'ಭಾರತೀಯ ಭಾಷೆಗಳು', 'ml-IN': 'ഇന്ത്യൻ ഭാഷകൾ', 'bn-IN': 'ভারতীয় ভাষা', 'gu-IN': 'ભારતીય ભાષાઓ', 'pa-IN': 'ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ' } as Str,
    statTime: { 'hi-IN': 'औसत खोज समय', 'mr-IN': 'सरासरी शोध वेळ', 'en-IN': 'Average search time', 'ta-IN': 'சராசரி தேடல் நேரம்', 'te-IN': 'సగటు శోధన సమయం', 'kn-IN': 'ಸರಾಸರಿ ಹುಡುಕಾಟ ಸಮಯ', 'ml-IN': 'ശരാശരി തിരയൽ സമയം', 'bn-IN': 'গড় অনুসন্ধান সময়', 'gu-IN': 'સરેરાશ શોધ સમય', 'pa-IN': 'ਔਸਤ ਖੋਜ ਸਮਾਂ' } as Str,
    statFree: { 'hi-IN': 'हर नागरिक के लिए', 'mr-IN': 'प्रत्येक नागरिकासाठी', 'en-IN': 'For every citizen', 'ta-IN': 'ஒவ்வொரு குடிமகனுக்கும்', 'te-IN': 'ప్రతి పౌరుడికి', 'kn-IN': 'ಪ್ರತಿ ನಾಗರಿಕರಿಗೆ', 'ml-IN': 'എല്ലാ പൗരനും', 'bn-IN': 'প্রতিটি নাগরিকের জন্য', 'gu-IN': 'દરેક નાગરિક માટે', 'pa-IN': 'ਹਰ ਨਾਗਰਿਕ ਲਈ' } as Str,
    statFreeNum: { 'hi-IN': 'मुफ्त', 'mr-IN': 'मोफत', 'en-IN': 'Free', 'ta-IN': 'இலவசம்', 'te-IN': 'ఉచితం', 'kn-IN': 'ಉಚಿತ', 'ml-IN': 'സൗജന്യം', 'bn-IN': 'বিনামূল্যে', 'gu-IN': 'મફત', 'pa-IN': 'ਮੁਫ਼ਤ' } as Str,
    statTimeNum: { 'hi-IN': '3 मिनट', 'mr-IN': '3 मिनिटे', 'en-IN': '3 min', 'ta-IN': '3 நிமிடங்கள்', 'te-IN': '3 నిమిషాలు', 'kn-IN': '3 ನಿಮಿಷಗಳು', 'ml-IN': '3 മിനിറ്റ്', 'bn-IN': '৩ মিনিট', 'gu-IN': '3 મિનિટ', 'pa-IN': '3 ਮਿੰਟ' } as Str,

    dualModeTag: { 'hi-IN': 'SuvidhaAI उपयोग करने के दो तरीके', 'mr-IN': 'SuvidhaAI वापरण्याचे दोन मार्ग', 'en-IN': 'Two ways to use SuvidhaAI', 'ta-IN': 'SuvidhaAI-ஐப் பயன்படுத்த இரண்டு வழிகள்', 'te-IN': 'SuvidhaAI ఉపయోగించడానికి రెండు మార్గాలు', 'kn-IN': 'SuvidhaAI ಬಳಸಲು ಎರಡು ವಿಧಾನಗಳು', 'ml-IN': 'SuvidhaAI ഉപയോഗിക്കാൻ രണ്ട് വഴികൾ', 'bn-IN': 'SuvidhaAI ব্যবহারের দুটি উপায়', 'gu-IN': 'SuvidhaAI વાપરવાની બે રીતો', 'pa-IN': 'SuvidhaAI ਵਰਤਣ ਦੇ ਦੋ ਤਰੀਕੇ' } as Str,
    dualModeHeading: { 'hi-IN': 'चुनें आप कैसे खोजना चाहते हैं', 'mr-IN': 'तुम्हाला कसे शोधायचे ते निवडा', 'en-IN': 'Choose how you want to search', 'ta-IN': 'நீங்கள் எப்படி தேட விரும்புகிறீர்கள் என்பதைத் தேர்வு செய்யுங்கள்', 'te-IN': 'మీరు ఎలా వెతకాలనుకుంటున్నారో ఎంచుకోండి', 'kn-IN': 'ನೀವು ಹೇಗೆ ಹುಡುಕಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ', 'ml-IN': 'നിങ്ങൾ എങ്ങനെ തിരയാൻ ആഗ്രഹിക്കുന്നു എന്ന് തിരഞ്ഞെടുക്കുക', 'bn-IN': 'আপনি কীভাবে খুঁজতে চান তা বেছে নিন', 'gu-IN': 'તમે કેવી રીતે શોધવા માંગો છો તે પસંદ કરો', 'pa-IN': 'ਚੁਣੋ ਤੁਸੀਂ ਕਿਵੇਂ ਖੋਜਣਾ ਚਾਹੁੰਦੇ ਹੋ' } as Str,
    dualModeSub: {
      'hi-IN': 'हर नागरिक के लिए एक मंच — ग्रामीण उपयोगकर्ताओं के लिए सरल आवाज़ मार्गदर्शन, पारिवारिक सहायकों और CSC संचालकों के लिए पूर्ण आवेदन उपकरण।',
      'mr-IN': 'प्रत्येक नागरिकासाठी एक व्यासपीठ — ग्रामीण वापरकर्त्यांसाठी सोपे आवाज मार्गदर्शन, कौटुंबिक मदतनीस आणि CSC ऑपरेटरसाठी संपूर्ण अर्ज साधने.',
      'en-IN': 'One platform for every citizen — simple voice guidance for rural users, complete application tools for family helpers and CSC operators.',
      'ta-IN': 'ஒவ்வொரு குடிமகனுக்கும் ஒரு தளம் — கிராமப்புற பயனர்களுக்கு எளிய குரல் வழிகாட்டல், குடும்ப உதவியாளர்கள் மற்றும் CSC இயக்குநர்களுக்கு முழுமையான விண்ணப்பக் கருவிகள்.',
      'te-IN': 'ప్రతి పౌరుడికి ఒక వేదిక — గ్రామీణ వినియోగదారులకు సరళమైన వాయిస్ మార్గదర్శకత్వం, కుటుంబ సహాయకులు మరియు CSC ఆపరేటర్లకు పూర్తి దరఖాస్తు సాధనాలు.',
      'kn-IN': 'ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕರಿಗೂ ಒಂದು ವೇದಿಕೆ — ಗ್ರಾಮೀಣ ಬಳಕೆದಾರರಿಗೆ ಸರಳ ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ, ಕುಟುಂಬ ಸಹಾಯಕರು ಮತ್ತು CSC ನಿರ್ವಾಹಕರಿಗೆ ಸಂಪೂರ್ಣ ಅರ್ಜಿ ಸಾಧನಗಳು.',
      'ml-IN': 'എല്ലാ പൗരനും ഒരു പ്ലാറ്റ്ഫോം — ഗ്രാമീണ ഉപയോക്താക്കൾക്ക് ലളിതമായ വോയ്സ് മാർഗനിർദേശം, കുടുംബ സഹായികൾക്കും CSC ഓപ്പറേറ്റർമാർക്കും പൂർണ്ണമായ അപേക്ഷാ ഉപകരണങ്ങൾ.',
      'bn-IN': 'প্রতিটি নাগরিকের জন্য একটি প্ল্যাটফর্ম — গ্রামীণ ব্যবহারকারীদের জন্য সহজ ভয়েস গাইডেন্স, পারিবারিক সহায়ক এবং CSC অপারেটরদের জন্য সম্পূর্ণ আবেদন সরঞ্জাম।',
      'gu-IN': 'દરેક નાગરિક માટે એક પ્લેટફોર્મ — ગ્રામીણ વપરાશકર્તાઓ માટે સરળ વૉઇસ માર્ગદર્શન, પારિવારિક સહાયકો અને CSC ઓપરેટરો માટે સંપૂર્ણ અરજી સાધનો.',
      'pa-IN': 'ਹਰ ਨਾਗਰਿਕ ਲਈ ਇੱਕ ਪਲੇਟਫਾਰਮ — ਪੇਂਡੂ ਉਪਭੋਗਤਾਵਾਂ ਲਈ ਸਧਾਰਨ ਆਵਾਜ਼ ਮਾਰਗਦਰਸ਼ਨ, ਪਰਿਵਾਰਕ ਸਹਾਇਕਾਂ ਅਤੇ CSC ਓਪਰੇਟਰਾਂ ਲਈ ਪੂਰੇ ਅਰਜ਼ੀ ਸਾਧਨ।',
    } as Str,
    simpleModeBadge: { 'hi-IN': 'सरल मोड', 'mr-IN': 'सोपी पद्धत', 'en-IN': 'Simple Mode', 'ta-IN': 'எளிய முறை', 'te-IN': 'సరళ మోడ్', 'kn-IN': 'ಸರಳ ಮೋಡ್', 'ml-IN': 'ലളിത മോഡ്', 'bn-IN': 'সহজ মোড', 'gu-IN': 'સરળ મોડ', 'pa-IN': 'ਸਧਾਰਨ ਮੋਡ' } as Str,
    simpleModeTitle: { 'hi-IN': 'सरल मोड — सीधे नागरिकों के लिए', 'mr-IN': 'सोपी पद्धत — थेट नागरिकांसाठी', 'en-IN': 'Simple Mode — For Citizens Directly', 'ta-IN': 'எளிய முறை — நேரடியாக குடிமக்களுக்கு', 'te-IN': 'సరళ మోడ్ — నేరుగా పౌరులకు', 'kn-IN': 'ಸರಳ ಮೋಡ್ — ನೇರವಾಗಿ ನಾಗರಿಕರಿಗೆ', 'ml-IN': 'ലളിത മോഡ് — നേരിട്ട് പൗരന്മാർക്ക്', 'bn-IN': 'সহজ মোড — সরাসরি নাগরিকদের জন্য', 'gu-IN': 'સરળ મોડ — સીધા નાગરિકો માટે', 'pa-IN': 'ਸਧਾਰਨ ਮੋਡ — ਸਿੱਧੇ ਨਾਗਰਿਕਾਂ ਲਈ' } as Str,
    simpleModeDesc: {
      'hi-IN': 'आवाज़-पहला, हिंदी और मराठी, परिणाम बोलकर सुनाए जाते हैं। किसानों, वरिष्ठ नागरिकों और ग्रामीण उपयोगकर्ताओं के लिए बनाया गया — कम से कम पाठ, अधिकतम स्पष्टता।',
      'mr-IN': 'आवाज-प्रथम, हिंदी आणि मराठी, निकाल बोलून सांगितले जातात. शेतकरी, ज्येष्ठ नागरिक आणि ग्रामीण वापरकर्त्यांसाठी तयार — कमीत कमी मजकूर, जास्तीत जास्त स्पष्टता.',
      'en-IN': 'Voice-first, Hindi and Marathi, results spoken aloud. Designed for farmers, senior citizens, and rural users — minimal text, maximum clarity.',
      'ta-IN': 'குரல்-முதன்மை, 10 மொழிகளில், முடிவுகள் பேசிக் கூறப்படும். விவசாயிகள், மூத்த குடிமக்கள் மற்றும் கிராமப்புற பயனர்களுக்காக வடிவமைக்கப்பட்டது — குறைந்த உரை, அதிகபட்ச தெளிவு.',
      'te-IN': 'వాయిస్-ఫస్ట్, 10 భాషల్లో, ఫలితాలు మాట్లాడి వినిపిస్తారు. రైతులు, వృద్ధ పౌరులు మరియు గ్రామీణ వినియోగదారుల కోసం రూపొందించబడింది — కనీస వచనం, గరిష్ట స్పష్టత.',
      'kn-IN': 'ಧ್ವನಿ-ಮೊದಲ, 10 ಭಾಷೆಗಳಲ್ಲಿ, ಫಲಿತಾಂಶಗಳನ್ನು ಮಾತನಾಡಿ ಕೇಳಿಸಲಾಗುತ್ತದೆ. ರೈತರು, ಹಿರಿಯ ನಾಗರಿಕರು ಮತ್ತು ಗ್ರಾಮೀಣ ಬಳಕೆದಾರರಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ — ಕನಿಷ್ಠ ಪಠ್ಯ, ಗರಿಷ್ಠ ಸ್ಪಷ್ಟತೆ.',
      'ml-IN': 'വോയ്സ്-ഫസ്റ്റ്, 10 ഭാഷകളിൽ, ഫലങ്ങൾ സംസാരിച്ച് കേൾപ്പിക്കുന്നു. കർഷകർ, മുതിർന്ന പൗരന്മാർ, ഗ്രാമീണ ഉപയോക്താക്കൾ എന്നിവർക്കായി രൂപകൽപ്പന ചെയ്തത് — കുറഞ്ഞ ടെക്സ്റ്റ്, പരമാവധി വ്യക്തത.',
      'bn-IN': 'ভয়েস-প্রথম, ১০টি ভাষায়, ফলাফল বলে শোনানো হয়। কৃষক, প্রবীণ নাগরিক এবং গ্রামীণ ব্যবহারকারীদের জন্য ডিজাইন করা — ন্যূনতম লেখা, সর্বোচ্চ স্পষ্টতা।',
      'gu-IN': 'વૉઇસ-ફર્સ્ટ, 10 ભાષાઓમાં, પરિણામો બોલીને સંભળાવવામાં આવે છે. ખેડૂતો, વરિષ્ઠ નાગરિકો અને ગ્રામીણ વપરાશકર્તાઓ માટે બનાવેલ — ઓછામાં ઓછું લખાણ, મહત્તમ સ્પષ્ટતા.',
      'pa-IN': 'ਆਵਾਜ਼-ਪਹਿਲਾਂ, 10 ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ, ਨਤੀਜੇ ਬੋਲ ਕੇ ਸੁਣਾਏ ਜਾਂਦੇ ਹਨ। ਕਿਸਾਨਾਂ, ਸੀਨੀਅਰ ਨਾਗਰਿਕਾਂ ਅਤੇ ਪੇਂਡੂ ਉਪਭੋਗਤਾਵਾਂ ਲਈ ਬਣਾਇਆ — ਘੱਟੋ-ਘੱਟ ਲਿਖਤ, ਵੱਧ ਤੋਂ ਵੱਧ ਸਪਸ਼ਟਤਾ।',
    } as Str,
    simpleFeat1: { 'hi-IN': 'अपनी स्थिति बोलें — टाइप करने की ज़रूरत नहीं', 'mr-IN': 'तुमची परिस्थिती बोला — टाइप करण्याची गरज नाही', 'en-IN': 'Speak your situation — no typing needed', 'ta-IN': 'உங்கள் நிலையைப் பேசுங்கள் — தட்டச்சு தேவையில்லை', 'te-IN': 'మీ పరిస్థితిని మాట్లాడండి — టైప్ చేయాల్సిన అవసరం లేదు', 'kn-IN': 'ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯನ್ನು ಮಾತನಾಡಿ — ಟೈಪ್ ಮಾಡುವ ಅಗತ್ಯವಿಲ್ಲ', 'ml-IN': 'നിങ്ങളുടെ സാഹചര്യം സംസാരിക്കുക — ടൈപ്പ് ചെയ്യേണ്ട ആവശ്യമില്ല', 'bn-IN': 'আপনার পরিস্থিতি বলুন — টাইপ করার দরকার নেই', 'gu-IN': 'તમારી પરિસ્થિતિ બોલો — ટાઇપ કરવાની જરૂર નથી', 'pa-IN': 'ਆਪਣੀ ਸਥਿਤੀ ਬੋਲੋ — ਟਾਈਪ ਕਰਨ ਦੀ ਲੋੜ ਨਹੀਂ' } as Str,
    simpleFeat2: { 'hi-IN': 'परिणाम हिंदी या मराठी में बोलकर सुनाए जाते हैं', 'mr-IN': 'निकाल हिंदी किंवा मराठीत बोलून सांगितले जातात', 'en-IN': 'Results read aloud in Hindi or Marathi', 'ta-IN': 'முடிவுகள் உங்கள் மொழியில் பேசிக் கூறப்படும்', 'te-IN': 'ఫలితాలు మీ భాషలో మాట్లాడి వినిపిస్తారు', 'kn-IN': 'ಫಲಿತಾಂಶಗಳನ್ನು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಓದಿ ಕೇಳಿಸಲಾಗುತ್ತದೆ', 'ml-IN': 'ഫലങ്ങൾ നിങ്ങളുടെ ഭാഷയിൽ വായിച്ച് കേൾപ്പിക്കുന്നു', 'bn-IN': 'ফলাফল আপনার ভাষায় পড়ে শোনানো হয়', 'gu-IN': 'પરિણામો તમારી ભાષામાં વાંચીને સંભળાવવામાં આવે છે', 'pa-IN': 'ਨਤੀਜੇ ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਪੜ੍ਹ ਕੇ ਸੁਣਾਏ ਜਾਂਦੇ ਹਨ' } as Str,
    simpleFeat3: { 'hi-IN': 'एक-टैप WhatsApp शेयर और हेल्पलाइन कॉल', 'mr-IN': 'एक-टॅप WhatsApp शेअर आणि हेल्पलाइन कॉल', 'en-IN': 'One-tap WhatsApp share and helpline call', 'ta-IN': 'ஒரு-தட்டு WhatsApp பகிர்வு மற்றும் உதவி எண் அழைப்பு', 'te-IN': 'ఒక-ట్యాప్ WhatsApp షేర్ మరియు హెల్ప్‌లైన్ కాల్', 'kn-IN': 'ಒಂದು-ಟ್ಯಾಪ್ WhatsApp ಹಂಚಿಕೆ ಮತ್ತು ಸಹಾಯವಾಣಿ ಕರೆ', 'ml-IN': 'ഒറ്റ-ടാപ്പ് WhatsApp പങ്കിടലും ഹെൽപ്പ്‌ലൈൻ കോളും', 'bn-IN': 'এক-ট্যাপ WhatsApp শেয়ার এবং হেল্পলাইন কল', 'gu-IN': 'એક-ટેપ WhatsApp શેર અને હેલ્પલાઇન કૉલ', 'pa-IN': 'ਇੱਕ-ਟੈਪ WhatsApp ਸ਼ੇਅਰ ਅਤੇ ਹੈਲਪਲਾਈਨ ਕਾਲ' } as Str,
    simpleFeat4: { 'hi-IN': 'कोई लॉगिन या पंजीकरण आवश्यक नहीं', 'mr-IN': 'कोणतेही लॉगिन किंवा नोंदणी आवश्यक नाही', 'en-IN': 'No login or registration needed', 'ta-IN': 'உள்நுழைவு அல்லது பதிவு தேவையில்லை', 'te-IN': 'లాగిన్ లేదా నమోదు అవసరం లేదు', 'kn-IN': 'ಲಾಗಿನ್ ಅಥವಾ ನೋಂದಣಿ ಅಗತ್ಯವಿಲ್ಲ', 'ml-IN': 'ലോഗിൻ അല്ലെങ്കിൽ രജിസ്ട്രേഷൻ ആവശ്യമില്ല', 'bn-IN': 'কোনো লগইন বা নিবন্ধন প্রয়োজন নেই', 'gu-IN': 'કોઈ લૉગિન અથવા નોંધણી જરૂરી નથી', 'pa-IN': 'ਕੋਈ ਲੌਗਇਨ ਜਾਂ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਲੋੜੀਂਦਾ ਨਹੀਂ' } as Str,
    useSimpleMode: { 'hi-IN': 'सरल मोड उपयोग करें — बोलकर खोजें', 'mr-IN': 'सोपी पद्धत वापरा — बोलून शोधा', 'en-IN': 'Use Simple Mode — Speak to Search', 'ta-IN': 'எளிய முறையைப் பயன்படுத்து — பேசித் தேடு', 'te-IN': 'సరళ మోడ్ ఉపయోగించండి — మాట్లాడి వెతకండి', 'kn-IN': 'ಸರಳ ಮೋಡ್ ಬಳಸಿ — ಮಾತನಾಡಿ ಹುಡುಕಿ', 'ml-IN': 'ലളിത മോഡ് ഉപയോഗിക്കുക — സംസാരിച്ച് തിരയുക', 'bn-IN': 'সহজ মোড ব্যবহার করুন — বলে খুঁজুন', 'gu-IN': 'સરળ મોડ વાપરો — બોલીને શોધો', 'pa-IN': 'ਸਧਾਰਨ ਮੋਡ ਵਰਤੋ — ਬੋਲ ਕੇ ਖੋਜੋ' } as Str,

    fullModeBadge: { 'hi-IN': 'पूर्ण सुविधा', 'mr-IN': 'पूर्ण सुविधा', 'en-IN': 'Full Mode', 'ta-IN': 'முழு முறை', 'te-IN': 'పూర్తి మోడ్', 'kn-IN': 'ಪೂರ್ಣ ಮೋಡ್', 'ml-IN': 'ഫുൾ മോഡ്', 'bn-IN': 'ফুল মোড', 'gu-IN': 'ફુલ મોડ', 'pa-IN': 'ਫੁੱਲ ਮੋਡ' } as Str,
    fullModeTitle: { 'hi-IN': 'फुल मोड — सहायकों और CSC संचालकों के लिए', 'mr-IN': 'फुल मोड — मदतनीस आणि CSC ऑपरेटरसाठी', 'en-IN': 'Full Mode — For Helpers & CSC Operators', 'ta-IN': 'முழு முறை — உதவியாளர்கள் & CSC இயக்குநர்களுக்கு', 'te-IN': 'పూర్తి మోడ్ — సహాయకులు & CSC ఆపరేటర్ల కోసం', 'kn-IN': 'ಪೂರ್ಣ ಮೋಡ್ — ಸಹಾಯಕರು ಮತ್ತು CSC ನಿರ್ವಾಹಕರಿಗೆ', 'ml-IN': 'ഫുൾ മോഡ് — സഹായികൾക്കും CSC ഓപ്പറേറ്റർമാർക്കും', 'bn-IN': 'ফুল মোড — সহায়ক ও CSC অপারেটরদের জন্য', 'gu-IN': 'ફુલ મોડ — સહાયકો અને CSC ઓપરેટરો માટે', 'pa-IN': 'ਫੁੱਲ ਮੋਡ — ਸਹਾਇਕਾਂ ਅਤੇ CSC ਓਪਰੇਟਰਾਂ ਲਈ' } as Str,
    fullModeDesc: {
      'hi-IN': 'पूर्ण पात्रता विश्लेषण, अस्वीकृति रोकथाम, पहले से भरे आवेदन दस्तावेज़, और शिक्षित परिवार के सदस्यों और सरकारी संचालकों के लिए स्थिति ट्रैकिंग।',
      'mr-IN': 'संपूर्ण पात्रता विश्लेषण, नकार प्रतिबंध, आधीच भरलेली अर्ज कागदपत्रे, आणि शिक्षित कुटुंब सदस्य व सरकारी ऑपरेटरसाठी स्थिती ट्रॅकिंग.',
      'en-IN': 'Complete eligibility analysis, rejection prevention, pre-filled application documents, and status tracking for educated family members and government operators.',
      'ta-IN': 'முழுமையான தகுதி பகுப்பாய்வு, நிராகரிப்பு தடுப்பு, முன்பே நிரப்பப்பட்ட விண்ணப்ப ஆவணங்கள், மற்றும் படித்த குடும்ப உறுப்பினர்கள் மற்றும் அரசு இயக்குநர்களுக்கான நிலை கண்காணிப்பு.',
      'te-IN': 'పూర్తి అర్హత విశ్లేషణ, తిరస్కరణ నివారణ, ముందుగా నింపిన దరఖాస్తు పత్రాలు, మరియు విద్యావంతులైన కుటుంబ సభ్యులు మరియు ప్రభుత్వ ఆపరేటర్ల కోసం స్థితి ట్రాకింగ్.',
      'kn-IN': 'ಸಂಪೂರ್ಣ ಅರ್ಹತಾ ವಿಶ್ಲೇಷಣೆ, ತಿರಸ್ಕಾರ ತಡೆಗಟ್ಟುವಿಕೆ, ಮೊದಲೇ ಭರ್ತಿ ಮಾಡಿದ ಅರ್ಜಿ ದಾಖಲೆಗಳು, ಮತ್ತು ವಿದ್ಯಾವಂತ ಕುಟುಂಬ ಸದಸ್ಯರು ಮತ್ತು ಸರ್ಕಾರಿ ನಿರ್ವಾಹಕರಿಗೆ ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕಿಂಗ್.',
      'ml-IN': 'സമ്പൂർണ്ണ യോഗ്യതാ വിശകലനം, നിരസിക്കൽ പ്രതിരോധം, മുൻകൂട്ടി പൂരിപ്പിച്ച അപേക്ഷാ രേഖകൾ, വിദ്യാസമ്പന്നരായ കുടുംബാംഗങ്ങൾക്കും സർക്കാർ ഓപ്പറേറ്റർമാർക്കും സ്റ്റാറ്റസ് ട്രാക്കിംഗ്.',
      'bn-IN': 'সম্পূর্ণ যোগ্যতা বিশ্লেষণ, প্রত্যাখ্যান প্রতিরোধ, আগে থেকে পূরণ করা আবেদনপত্র, এবং শিক্ষিত পরিবারের সদস্য ও সরকারি অপারেটরদের জন্য স্ট্যাটাস ট্র্যাকিং।',
      'gu-IN': 'સંપૂર્ણ પાત્રતા વિશ્લેષણ, અસ્વીકાર નિવારણ, અગાઉથી ભરેલા અરજી દસ્તાવેજો, અને શિક્ષિત કુટુંબના સભ્યો અને સરકારી ઓપરેટરો માટે સ્થિતિ ટ્રેકિંગ.',
      'pa-IN': 'ਪੂਰਾ ਯੋਗਤਾ ਵਿਸ਼ਲੇਸ਼ਣ, ਅਸਵੀਕਾਰ ਰੋਕਥਾਮ, ਪਹਿਲਾਂ ਤੋਂ ਭਰੇ ਅਰਜ਼ੀ ਦਸਤਾਵੇਜ਼, ਅਤੇ ਪੜ੍ਹੇ-ਲਿਖੇ ਪਰਿਵਾਰਕ ਮੈਂਬਰਾਂ ਅਤੇ ਸਰਕਾਰੀ ਓਪਰੇਟਰਾਂ ਲਈ ਸਥਿਤੀ ਟਰੈਕਿੰਗ।',
    } as Str,
    fullFeat1: { 'hi-IN': 'प्रत्येक योजना के लिए विस्तृत पात्रता जाँच', 'mr-IN': 'प्रत्येक योजनेसाठी सविस्तर पात्रता तपासणी', 'en-IN': 'Detailed eligibility check per scheme', 'ta-IN': 'ஒவ்வொரு திட்டத்திற்கும் விரிவான தகுதி சரிபார்ப்பு', 'te-IN': 'ప్రతి పథకానికి వివరణాత్మక అర్హత తనిఖీ', 'kn-IN': 'ಪ್ರತಿ ಯೋಜನೆಗೆ ವಿವರವಾದ ಅರ್ಹತಾ ಪರಿಶೀಲನೆ', 'ml-IN': 'ഓരോ പദ്ധതിക്കും വിശദമായ യോഗ്യതാ പരിശോധന', 'bn-IN': 'প্রতিটি প্রকল্পের জন্য বিস্তারিত যোগ্যতা পরীক্ষা', 'gu-IN': 'દરેક યોજના માટે વિગતવાર પાત્રતા ચકાસણી', 'pa-IN': 'ਹਰੇਕ ਯੋਜਨਾ ਲਈ ਵਿਸਤ੍ਰਿਤ ਯੋਗਤਾ ਜਾਂਚ' } as Str,
    fullFeat2: { 'hi-IN': 'अस्वीकृति रोकथाम चेतावनियां', 'mr-IN': 'नकार प्रतिबंध इशारे', 'en-IN': 'Rejection prevention warnings', 'ta-IN': 'நிராகரிப்பு தடுப்பு எச்சரிக்கைகள்', 'te-IN': 'తిరస్కరణ నివారణ హెచ్చరికలు', 'kn-IN': 'ತಿರಸ್ಕಾರ ತಡೆಗಟ್ಟುವ ಎಚ್ಚರಿಕೆಗಳು', 'ml-IN': 'നിരസിക്കൽ പ്രതിരോധ മുന്നറിയിപ്പുകൾ', 'bn-IN': 'প্রত্যাখ্যান প্রতিরোধ সতর্কতা', 'gu-IN': 'અસ્વીકાર નિવારણ ચેતવણીઓ', 'pa-IN': 'ਅਸਵੀਕਾਰ ਰੋਕਥਾਮ ਚੇਤਾਵਨੀਆਂ' } as Str,
    fullFeat3: { 'hi-IN': 'प्रिंट करने योग्य पहले से भरा आवेदन सारांश', 'mr-IN': 'छापण्यायोग्य आधीच भरलेला अर्ज सारांश', 'en-IN': 'Printable pre-filled application summary', 'ta-IN': 'அச்சிடக்கூடிய முன்பே நிரப்பப்பட்ட விண்ணப்பச் சுருக்கம்', 'te-IN': 'ప్రింట్ చేయదగిన ముందుగా నింపిన దరఖాస్తు సారాంశం', 'kn-IN': 'ಮುದ್ರಿಸಬಹುದಾದ ಮೊದಲೇ ಭರ್ತಿ ಮಾಡಿದ ಅರ್ಜಿ ಸಾರಾಂಶ', 'ml-IN': 'പ്രിന്റ് ചെയ്യാവുന്ന മുൻകൂട്ടി പൂരിപ്പിച്ച അപേക്ഷാ സംഗ്രഹം', 'bn-IN': 'প্রিন্টযোগ্য পূর্বে পূরণ করা আবেদন সারাংশ', 'gu-IN': 'છાપી શકાય તેવો પહેલેથી ભરેલો અરજી સારાંશ', 'pa-IN': 'ਪ੍ਰਿੰਟ ਕਰਨ ਯੋਗ ਪਹਿਲਾਂ ਤੋਂ ਭਰਿਆ ਅਰਜ਼ੀ ਸਾਰ' } as Str,
    fullFeat4: { 'hi-IN': 'प्रोफ़ाइल में आवेदन स्थिति ट्रैकर', 'mr-IN': 'प्रोफाइलमध्ये अर्ज स्थिती ट्रॅकर', 'en-IN': 'Application status tracker in profile', 'ta-IN': 'சுயவிவரத்தில் விண்ணப்ப நிலை கண்காணிப்பான்', 'te-IN': 'ప్రొఫైల్‌లో దరఖాస్తు స్థితి ట్రాకర్', 'kn-IN': 'ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕರ್', 'ml-IN': 'പ്രൊഫൈലിൽ അപേക്ഷാ സ്റ്റാറ്റസ് ട്രാക്കർ', 'bn-IN': 'প্রোফাইলে আবেদনের অবস্থা ট্র্যাকার', 'gu-IN': 'પ્રોફાઇલમાં અરજી સ્થિતિ ટ્રેકર', 'pa-IN': 'ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ ਅਰਜ਼ੀ ਸਥਿਤੀ ਟਰੈਕਰ' } as Str,
    useFullMode: { 'hi-IN': 'फुल मोड उपयोग करें — पूर्ण सुविधा', 'mr-IN': 'फुल मोड वापरा — पूर्ण सुविधा', 'en-IN': 'Use Full Mode — Complete Toolkit', 'ta-IN': 'முழு முறையைப் பயன்படுத்து — முழுமையான கருவித்தொகுப்பு', 'te-IN': 'పూర్తి మోడ్ ఉపయోగించండి — పూర్తి టూల్‌కిట్', 'kn-IN': 'ಪೂರ್ಣ ಮೋಡ್ ಬಳಸಿ — ಸಂಪೂರ್ಣ ಟೂಲ್‌ಕಿಟ್', 'ml-IN': 'ഫുൾ മോഡ് ഉപയോഗിക്കുക — സമ്പൂർണ്ണ ടൂൾകിറ്റ്', 'bn-IN': 'ফুল মোড ব্যবহার করুন — সম্পূর্ণ টুলকিট', 'gu-IN': 'ફુલ મોડ વાપરો — સંપૂર્ણ ટૂલકિટ', 'pa-IN': 'ਫੁੱਲ ਮੋਡ ਵਰਤੋ — ਪੂਰੀ ਟੂਲਕਿੱਟ' } as Str,

    problemTag: { 'hi-IN': 'असली समस्या', 'mr-IN': 'खरी समस्या', 'en-IN': 'The real problem', 'ta-IN': 'உண்மையான பிரச்சினை', 'te-IN': 'నిజమైన సమస్య', 'kn-IN': 'ನಿಜವಾದ ಸಮಸ್ಯೆ', 'ml-IN': 'യഥാർത്ഥ പ്രശ്നം', 'bn-IN': 'আসল সমস্যা', 'gu-IN': 'ખરી સમસ્યા', 'pa-IN': 'ਅਸਲੀ ਸਮੱਸਿਆ' } as Str,
    problemHeading: { 'hi-IN': '₹12 लाख करोड़ का कल्याण। ज़्यादातर दावा नहीं किया गया।', 'mr-IN': '₹12 लाख कोटींचे कल्याण. बहुतांश दावा केलेला नाही.', 'en-IN': '₹12 lakh crore in welfare. Most of it unclaimed.', 'ta-IN': '₹12 லட்சம் கோடி நலத்திட்டங்கள். பெரும்பாலானவை பெறப்படவில்லை.', 'te-IN': '₹12 లక్షల కోట్ల సంక్షేమం. చాలా వరకు క్లెయిమ్ చేయలేదు.', 'kn-IN': '₹12 ಲಕ್ಷ ಕೋಟಿ ಕಲ್ಯಾಣ. ಹೆಚ್ಚಿನವು ಪಡೆಯಲಾಗಿಲ್ಲ.', 'ml-IN': '₹12 ലക്ഷം കോടി ക്ഷേമം. ഭൂരിഭാഗവും അവകാശപ്പെട്ടിട്ടില്ല.', 'bn-IN': '₹12 লক্ষ কোটি কল্যাণ। বেশিরভাগ দাবি করা হয়নি।', 'gu-IN': '₹12 લાખ કરોડનું કલ્યાણ. મોટાભાગનું દાવો કરાયું નથી.', 'pa-IN': '₹12 ਲੱਖ ਕਰੋੜ ਦੀ ਭਲਾਈ। ਜ਼ਿਆਦਾਤਰ ਦਾਅਵਾ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।' } as Str,
    problemSub: {
      'hi-IN': 'भारत अधिकांश विकासशील देशों की तुलना में प्रति नागरिक अधिक आवंटित करता है। समस्या बजट नहीं है — यह योजनाओं के अस्तित्व और नागरिकों को वास्तव में मिलने के बीच का अंतर है।',
      'mr-IN': 'भारत बहुतेक विकसनशील देशांपेक्षा प्रति नागरिक जास्त वाटप करतो. समस्या बजेट नाही — योजना अस्तित्वात असणे आणि नागरिकांना प्रत्यक्ष मिळणे यामधील ही तफावत आहे.',
      'en-IN': 'India allocates more per citizen than most developing nations. The problem is not the budget — it is the gap between schemes existing and citizens actually receiving them.',
      'ta-IN': 'பெரும்பாலான வளரும் நாடுகளை விட இந்தியா ஒரு குடிமகனுக்கு அதிகமாக ஒதுக்குகிறது. பிரச்சினை பட்ஜெட் அல்ல — திட்டங்கள் இருப்பதற்கும் குடிமக்கள் உண்மையில் பெறுவதற்கும் இடையிலான இடைவெளிதான்.',
      'te-IN': 'చాలా అభివృద్ధి చెందుతున్న దేశాల కంటే భారతదేశం ఒక్కో పౌరుడికి ఎక్కువ కేటాయిస్తుంది. సమస్య బడ్జెట్ కాదు — పథకాలు ఉండటానికి మరియు పౌరులకు నిజంగా అందటానికి మధ్య అంతరమే సమస్య.',
      'kn-IN': 'ಹೆಚ್ಚಿನ ಅಭಿವೃದ್ಧಿಶೀಲ ರಾಷ್ಟ್ರಗಳಿಗಿಂತ ಭಾರತವು ಪ್ರತಿ ನಾಗರಿಕರಿಗೆ ಹೆಚ್ಚು ಹಂಚಿಕೆ ಮಾಡುತ್ತದೆ. ಸಮಸ್ಯೆ ಬಜೆಟ್ ಅಲ್ಲ — ಯೋಜನೆಗಳು ಇರುವುದು ಮತ್ತು ನಾಗರಿಕರಿಗೆ ನಿಜವಾಗಿ ಸಿಗುವುದರ ನಡುವಿನ ಅಂತರವೇ ಸಮಸ್ಯೆ.',
      'ml-IN': 'മിക്ക വികസ്വര രാജ്യങ്ങളേക്കാളും ഇന്ത്യ ഓരോ പൗരനും കൂടുതൽ വകയിരുത്തുന്നു. പ്രശ്നം ബജറ്റല്ല — പദ്ധതികൾ നിലവിലുണ്ടെന്നതും പൗരന്മാർക്ക് യഥാർത്ഥത്തിൽ ലഭിക്കുന്നതും തമ്മിലുള്ള വിടവാണ്.',
      'bn-IN': 'ভারত বেশিরভাগ উন্নয়নশীল দেশের তুলনায় প্রতি নাগরিকের জন্য বেশি বরাদ্দ করে। সমস্যা বাজেট নয় — এটি প্রকল্পের অস্তিত্ব এবং নাগরিকরা প্রকৃতপক্ষে তা পাওয়ার মধ্যে ব্যবধান।',
      'gu-IN': 'ભારત મોટાભાગના વિકાસશીલ દેશો કરતાં દરેક નાગરિક દીઠ વધુ ફાળવે છે. સમસ્યા બજેટ નથી — તે યોજનાઓના અસ્તિત્વ અને નાગરિકોને ખરેખર મળવા વચ્ચેનું અંતર છે.',
      'pa-IN': 'ਭਾਰਤ ਜ਼ਿਆਦਾਤਰ ਵਿਕਾਸਸ਼ੀਲ ਦੇਸ਼ਾਂ ਦੇ ਮੁਕਾਬਲੇ ਪ੍ਰਤੀ ਨਾਗਰਿਕ ਵੱਧ ਅਲਾਟ ਕਰਦਾ ਹੈ। ਸਮੱਸਿਆ ਬਜਟ ਨਹੀਂ ਹੈ — ਇਹ ਯੋਜਨਾਵਾਂ ਦੇ ਮੌਜੂਦ ਹੋਣ ਅਤੇ ਨਾਗਰਿਕਾਂ ਨੂੰ ਅਸਲ ਵਿੱਚ ਮਿਲਣ ਵਿਚਕਾਰ ਦਾ ਪਾੜਾ ਹੈ।',
    } as Str,
    statAwareness: { 'hi-IN': 'पात्र नागरिक जो कभी आवेदन नहीं करते', 'mr-IN': 'पात्र नागरिक जे कधीच अर्ज करत नाहीत', 'en-IN': 'Eligible citizens who never apply', 'ta-IN': 'தகுதியுள்ள குடிமக்கள் ஒருபோதும் விண்ணப்பிக்கவில்லை', 'te-IN': 'అర్హులైన పౌరులు ఎప్పుడూ దరఖాస్తు చేయరు', 'kn-IN': 'ಅರ್ಹ ನಾಗರಿಕರು ಎಂದಿಗೂ ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದಿಲ್ಲ', 'ml-IN': 'അർഹരായ പൗരന്മാർ ഒരിക്കലും അപേക്ഷിക്കുന്നില്ല', 'bn-IN': 'যোগ্য নাগরিকরা কখনো আবেদন করেন না', 'gu-IN': 'પાત્ર નાગરિકો ક્યારેય અરજી કરતા નથી', 'pa-IN': 'ਯੋਗ ਨਾਗਰਿਕ ਜੋ ਕਦੇ ਅਰਜ਼ੀ ਨਹੀਂ ਦਿੰਦੇ' } as Str,
    statUsability: { 'hi-IN': 'सरकारी डिजिटल पोर्टल को उपयोग करना बहुत कठिन पाते हैं', 'mr-IN': 'सरकारी डिजिटल पोर्टल वापरणे खूप कठीण वाटते', 'en-IN': 'Find government digital portals too difficult to use', 'ta-IN': 'அரசு டிஜிட்டல் போர்டல்களைப் பயன்படுத்துவது மிகவும் கடினமாக உள்ளது', 'te-IN': 'ప్రభుత్వ డిజిటల్ పోర్టళ్లను ఉపయోగించడం చాలా కష్టంగా భావిస్తారు', 'kn-IN': 'ಸರ್ಕಾರಿ ಡಿಜಿಟಲ್ ಪೋರ್ಟಲ್‌ಗಳನ್ನು ಬಳಸಲು ತುಂಬಾ ಕಷ್ಟಕರ ಎಂದು ಕಂಡುಕೊಳ್ಳುತ್ತಾರೆ', 'ml-IN': 'സർക്കാർ ഡിജിറ്റൽ പോർട്ടലുകൾ ഉപയോഗിക്കാൻ വളരെ ബുദ്ധിമുട്ടാണെന്ന് കണ്ടെത്തുന്നു', 'bn-IN': 'সরকারি ডিজিটাল পোর্টাল ব্যবহার করা খুব কঠিন মনে করেন', 'gu-IN': 'સરકારી ડિજિટલ પોર્ટલ વાપરવું ખૂબ મુશ્કેલ લાગે છે', 'pa-IN': 'ਸਰਕਾਰੀ ਡਿਜੀਟਲ ਪੋਰਟਲ ਵਰਤਣਾ ਬਹੁਤ ਔਖਾ ਲੱਗਦਾ ਹੈ' } as Str,
    statLanguage: { 'hi-IN': 'भारतीय भाषाएं पसंद करते हैं — अधिकांश पोर्टल केवल अंग्रेज़ी में', 'mr-IN': 'भारतीय भाषा पसंत करतात — बहुतेक पोर्टल फक्त इंग्रजीत', 'en-IN': 'Prefer Indic languages — most portals are English only', 'ta-IN': 'இந்திய மொழிகளை விரும்புகிறார்கள் — பெரும்பாலான போர்டல்கள் ஆங்கிலத்தில் மட்டுமே', 'te-IN': 'భారతీయ భాషలను ఇష్టపడతారు — చాలా పోర్టళ్లు ఇంగ్లీష్‌లో మాత్రమే', 'kn-IN': 'ಭಾರತೀಯ ಭಾಷೆಗಳನ್ನು ಬಯಸುತ್ತಾರೆ — ಹೆಚ್ಚಿನ ಪೋರ್ಟಲ್‌ಗಳು ಇಂಗ್ಲಿಷ್ ಮಾತ್ರ', 'ml-IN': 'ഇന്ത്യൻ ഭാഷകൾ ഇഷ്ടപ്പെടുന്നു — മിക്ക പോർട്ടലുകളും ഇംഗ്ലീഷ് മാത്രം', 'bn-IN': 'ভারতীয় ভাষা পছন্দ করেন — বেশিরভাগ পোর্টাল শুধু ইংরেজিতে', 'gu-IN': 'ભારતીય ભાષાઓ પસંદ કરે છે — મોટાભાગના પોર્ટલ ફક્ત અંગ્રેજીમાં', 'pa-IN': 'ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਪਸੰਦ ਕਰਦੇ ਹਨ — ਜ਼ਿਆਦਾਤਰ ਪੋਰਟਲ ਸਿਰਫ਼ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ' } as Str,
    statGuidance: { 'hi-IN': 'गुम या गलत दस्तावेज़ों के कारण आवेदन अस्वीकृत', 'mr-IN': 'हरवलेल्या किंवा चुकीच्या कागदपत्रांमुळे अर्ज नाकारले', 'en-IN': 'Applications rejected due to missing or incorrect documents', 'ta-IN': 'விட்டுப்போன அல்லது தவறான ஆவணங்களால் விண்ணப்பங்கள் நிராகரிக்கப்படுகின்றன', 'te-IN': 'తప్పిపోయిన లేదా తప్పు పత్రాల కారణంగా దరఖాస్తులు తిరస్కరించబడతాయి', 'kn-IN': 'ಕಾಣೆಯಾದ ಅಥವಾ ತಪ್ಪಾದ ದಾಖಲೆಗಳಿಂದಾಗಿ ಅರ್ಜಿಗಳು ತಿರಸ್ಕರಿಸಲ್ಪಡುತ್ತವೆ', 'ml-IN': 'നഷ്ടപ്പെട്ടതോ തെറ്റായതോ ആയ രേഖകൾ കാരണം അപേക്ഷകൾ നിരസിക്കപ്പെടുന്നു', 'bn-IN': 'অনুপস্থিত বা ভুল নথির কারণে আবেদন প্রত্যাখ্যাত হয়', 'gu-IN': 'ગુમ અથવા ખોટા દસ્તાવેજોના કારણે અરજીઓ નકારવામાં આવે છે', 'pa-IN': 'ਗੁੰਮ ਜਾਂ ਗਲਤ ਦਸਤਾਵੇਜ਼ਾਂ ਕਾਰਨ ਅਰਜ਼ੀਆਂ ਅਸਵੀਕਾਰ' } as Str,
    badgeAwareness: { 'hi-IN': 'जागरूकता की कमी', 'mr-IN': 'जागरूकतेची कमतरता', 'en-IN': 'Awareness gap', 'ta-IN': 'விழிப்புணர்வு இடைவெளி', 'te-IN': 'అవగాహన లోపం', 'kn-IN': 'ಜಾಗೃತಿ ಅಂತರ', 'ml-IN': 'അവബോധ വിടവ്', 'bn-IN': 'সচেতনতার ঘাটতি', 'gu-IN': 'જાગૃતિની ખામી', 'pa-IN': 'ਜਾਗਰੂਕਤਾ ਦੀ ਘਾਟ' } as Str,
    badgeUsability: { 'hi-IN': 'उपयोगिता की कमी', 'mr-IN': 'वापरण्यायोग्यतेची कमतरता', 'en-IN': 'Usability gap', 'ta-IN': 'பயன்பாட்டு இடைவெளி', 'te-IN': 'వినియోగ లోపం', 'kn-IN': 'ಬಳಕೆ ಅಂತರ', 'ml-IN': 'ഉപയോഗക്ഷമതാ വിടവ്', 'bn-IN': 'ব্যবহারযোগ্যতার ঘাটতি', 'gu-IN': 'ઉપયોગિતાની ખામી', 'pa-IN': 'ਵਰਤੋਂਯੋਗਤਾ ਦੀ ਘਾਟ' } as Str,
    badgeLanguageGap: { 'hi-IN': 'भाषा की कमी', 'mr-IN': 'भाषेची कमतरता', 'en-IN': 'Language gap', 'ta-IN': 'மொழி இடைவெளி', 'te-IN': 'భాషా లోపం', 'kn-IN': 'ಭಾಷಾ ಅಂತರ', 'ml-IN': 'ഭാഷാ വിടവ്', 'bn-IN': 'ভাষার ঘাটতি', 'gu-IN': 'ભાષાની ખામી', 'pa-IN': 'ਭਾਸ਼ਾ ਦੀ ਘਾਟ' } as Str,
    badgeGuidance: { 'hi-IN': 'मार्गदर्शन की कमी', 'mr-IN': 'मार्गदर्शनाची कमतरता', 'en-IN': 'Guidance gap', 'ta-IN': 'வழிகாட்டல் இடைவெளி', 'te-IN': 'మార్గదర్శకత్వం లోపం', 'kn-IN': 'ಮಾರ್ಗದರ್ಶನ ಅಂತರ', 'ml-IN': 'മാർഗനിർദേശ വിടവ്', 'bn-IN': 'দিকনির্দেশনার ঘাটতি', 'gu-IN': 'માર્ગદર્શનની ખામી', 'pa-IN': 'ਮਾਰਗਦਰਸ਼ਨ ਦੀ ਘਾਟ' } as Str,
    barrier1Title: { 'hi-IN': 'अंग्रेज़ी इंटरफेस नेविगेट नहीं कर सकते', 'mr-IN': 'इंग्रजी इंटरफेस वापरता येत नाही', 'en-IN': 'Cannot navigate English interfaces', 'ta-IN': 'ஆங்கில இடைமுகங்களை வழிநடத்த முடியாதவர்கள்', 'te-IN': 'ఇంగ్లీష్ ఇంటర్‌ఫేస్‌లను నావిగేట్ చేయలేరు', 'kn-IN': 'ಇಂಗ್ಲಿಷ್ ಇಂಟರ್‌ಫೇಸ್‌ಗಳನ್ನು ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲಾಗುವುದಿಲ್ಲ', 'ml-IN': 'ഇംഗ്ലീഷ് ഇന്റർഫേസുകൾ നാവിഗേറ്റ് ചെയ്യാൻ കഴിയില്ല', 'bn-IN': 'ইংরেজি ইন্টারফেস ব্যবহার করতে পারেন না', 'gu-IN': 'અંગ્રેજી ઇન્ટરફેસ નેવિગેટ કરી શકતા નથી', 'pa-IN': 'ਅੰਗਰੇਜ਼ੀ ਇੰਟਰਫੇਸ ਨੈਵੀਗੇਟ ਨਹੀਂ ਕਰ ਸਕਦੇ' } as Str,
    barrier1Desc: { 'hi-IN': 'अधिकांश पोर्टल में बुनियादी योजनाएं खोजने के लिए अंग्रेज़ी साक्षरता चाहिए', 'mr-IN': 'बहुतेक पोर्टलमध्ये मूलभूत योजना शोधण्यासाठी इंग्रजी साक्षरता आवश्यक आहे', 'en-IN': 'Most portals require English literacy to find basic schemes', 'ta-IN': 'பெரும்பாலான போர்டல்களில் அடிப்படை திட்டங்களைக் கண்டுபிடிக்க ஆங்கில அறிவு தேவை', 'te-IN': 'చాలా పోర్టళ్లలో ప్రాథమిక పథకాలను కనుగొనడానికి ఇంగ్లీష్ అక్షరాస్యత అవసరం', 'kn-IN': 'ಹೆಚ್ಚಿನ ಪೋರ್ಟಲ್‌ಗಳಲ್ಲಿ ಮೂಲ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಲು ಇಂಗ್ಲಿಷ್ ಸಾಕ್ಷರತೆ ಬೇಕು', 'ml-IN': 'മിക്ക പോർട്ടലുകളിലും അടിസ്ഥാന പദ്ധതികൾ കണ്ടെത്താൻ ഇംഗ്ലീഷ് സാക്ഷരത ആവശ്യമാണ്', 'bn-IN': 'বেশিরভাগ পোর্টালে মৌলিক প্রকল্প খুঁজতে ইংরেজি সাক্ষরতা প্রয়োজন', 'gu-IN': 'મોટાભાગના પોર્ટલમાં મૂળભૂત યોજનાઓ શોધવા અંગ્રેજી સાક્ષરતા જરૂરી છે', 'pa-IN': 'ਜ਼ਿਆਦਾਤਰ ਪੋਰਟਲਾਂ ਵਿੱਚ ਮੂਲ ਯੋਜਨਾਵਾਂ ਲੱਭਣ ਲਈ ਅੰਗਰੇਜ਼ੀ ਸਾਖਰਤਾ ਲੋੜੀਂਦੀ ਹੈ' } as Str,
    barrier2Title: { 'hi-IN': 'पोर्टल जो हिंदी में परिणाम बोलते हैं', 'mr-IN': 'पोर्टल जे हिंदीत निकाल सांगतात', 'en-IN': 'Portals that speak results in Hindi', 'ta-IN': 'உங்கள் மொழியில் முடிவுகளைப் பேசும் போர்டல்கள்', 'te-IN': 'మీ భాషలో ఫలితాలను చెప్పే పోర్టళ్లు', 'kn-IN': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಫಲಿತಾಂಶಗಳನ್ನು ಹೇಳುವ ಪೋರ್ಟಲ್‌ಗಳು', 'ml-IN': 'നിങ്ങളുടെ ഭാഷയിൽ ഫലങ്ങൾ പറയുന്ന പോർട്ടലുകൾ', 'bn-IN': 'যেসব পোর্টাল আপনার ভাষায় ফলাফল বলে', 'gu-IN': 'તમારી ભાષામાં પરિણામો બોલતા પોર્ટલ', 'pa-IN': 'ਪੋਰਟਲ ਜੋ ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਨਤੀਜੇ ਬੋਲਦੇ ਹਨ' } as Str,
    barrier2Desc: { 'hi-IN': '14 करोड़ भारतीय रोज़ आवाज़ का उपयोग करते हैं — कोई पोर्टल इसे समर्थन नहीं करता', 'mr-IN': '14 कोटी भारतीय दररोज आवाज वापरतात — कोणताही पोर्टल याला समर्थन देत नाही', 'en-IN': '140M Indians use voice daily — no portal supports it', 'ta-IN': '14 கோடி இந்தியர்கள் தினமும் குரலைப் பயன்படுத்துகின்றனர் — எந்த போர்டலும் இதை ஆதரிக்கவில்லை', 'te-IN': '14 కోట్ల మంది భారతీయులు రోజూ వాయిస్ ఉపయోగిస్తారు — ఏ పోర్టల్ దీన్ని సపోర్ట్ చేయదు', 'kn-IN': '14 ಕೋಟಿ ಭಾರತೀಯರು ಪ್ರತಿದಿನ ಧ್ವನಿ ಬಳಸುತ್ತಾರೆ — ಯಾವುದೇ ಪೋರ್ಟಲ್ ಇದನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ', 'ml-IN': '14 കോടി ഇന്ത്യക്കാർ ദിവസവും വോയ്സ് ഉപയോഗിക്കുന്നു — ഒരു പോർട്ടലും ഇത് പിന്തുണയ്ക്കുന്നില്ല', 'bn-IN': '১৪ কোটি ভারতীয় প্রতিদিন ভয়েস ব্যবহার করেন — কোনো পোর্টাল এটি সমর্থন করে না', 'gu-IN': '14 કરોડ ભારતીયો રોજ વૉઇસનો ઉપયોગ કરે છે — કોઈ પોર્ટલ આને સપોર્ટ કરતું નથી', 'pa-IN': '14 ਕਰੋੜ ਭਾਰਤੀ ਰੋਜ਼ ਆਵਾਜ਼ ਵਰਤਦੇ ਹਨ — ਕੋਈ ਪੋਰਟਲ ਇਸਦਾ ਸਮਰਥਨ ਨਹੀਂ ਕਰਦਾ' } as Str,
    barrier3Title: { 'hi-IN': 'ग्रामीण उपयोगकर्ता आवाज़ इंटरफेस पसंद करते हैं', 'mr-IN': 'ग्रामीण वापरकर्ते आवाज इंटरफेस पसंत करतात', 'en-IN': 'Rural users prefer voice interfaces', 'ta-IN': 'கிராமப்புற பயனர்கள் குரல் இடைமுகங்களை விரும்புகிறார்கள்', 'te-IN': 'గ్రామీణ వినియోగదారులు వాయిస్ ఇంటర్‌ఫేస్‌లను ఇష్టపడతారు', 'kn-IN': 'ಗ್ರಾಮೀಣ ಬಳಕೆದಾರರು ಧ್ವನಿ ಇಂಟರ್‌ಫೇಸ್‌ಗಳನ್ನು ಬಯಸುತ್ತಾರೆ', 'ml-IN': 'ഗ്രാമീണ ഉപയോക്താക്കൾ വോയ്സ് ഇന്റർഫേസുകൾ ഇഷ്ടപ്പെടുന്നു', 'bn-IN': 'গ্রামীণ ব্যবহারকারীরা ভয়েস ইন্টারফেস পছন্দ করেন', 'gu-IN': 'ગ્રામીણ વપરાશકર્તાઓ વૉઇસ ઇન્ટરફેસ પસંદ કરે છે', 'pa-IN': 'ਪੇਂਡੂ ਉਪਭੋਗਤਾ ਆਵਾਜ਼ ਇੰਟਰਫੇਸ ਪਸੰਦ ਕਰਦੇ ਹਨ' } as Str,
    barrier3Desc: { 'hi-IN': 'समाधान मौजूद है — इसे कल्याण पर लागू नहीं किया गया', 'mr-IN': 'उपाय अस्तित्वात आहे — तो कल्याणासाठी वापरला गेला नाही', 'en-IN': 'The solution exists — it just hasn\'t been applied to welfare', 'ta-IN': 'தீர்வு உள்ளது — அது நலத்திட்டங்களுக்குப் பயன்படுத்தப்படவில்லை', 'te-IN': 'పరిష్కారం ఉంది — ఇది సంక్షేమానికి వర్తింపజేయలేదు', 'kn-IN': 'ಪರಿಹಾರ ಇದೆ — ಅದನ್ನು ಕಲ್ಯಾಣಕ್ಕೆ ಅನ್ವಯಿಸಿಲ್ಲ', 'ml-IN': 'പരിഹാരം നിലവിലുണ്ട് — അത് ക്ഷേമത്തിന് പ്രയോഗിച്ചിട്ടില്ല', 'bn-IN': 'সমাধান বিদ্যমান — এটি কল্যাণে প্রয়োগ করা হয়নি', 'gu-IN': 'ઉકેલ અસ્તિત્વમાં છે — તે કલ્યાણ પર લાગુ કરાયો નથી', 'pa-IN': 'ਹੱਲ ਮੌਜੂਦ ਹੈ — ਇਸਨੂੰ ਭਲਾਈ ਲਈ ਲਾਗੂ ਨਹੀਂ ਕੀਤਾ ਗਿਆ' } as Str,
    chartTitle: { 'hi-IN': 'मौजूदा कल्याण पोर्टल वास्तव में किन तक पहुंचते हैं?', 'mr-IN': 'सध्याचे कल्याण पोर्टल प्रत्यक्षात कोणापर्यंत पोहोचतात?', 'en-IN': 'Who do existing welfare portals actually reach?', 'ta-IN': 'தற்போதைய நலத்திட்ட போர்டல்கள் உண்மையில் யாரை சென்றடைகின்றன?', 'te-IN': 'ప్రస్తుత సంక్షేమ పోర్టళ్లు నిజంగా ఎవరిని చేరుకుంటున్నాయి?', 'kn-IN': 'ಇರುವ ಕಲ್ಯಾಣ ಪೋರ್ಟಲ್‌ಗಳು ನಿಜವಾಗಿ ಯಾರನ್ನು ತಲುಪುತ್ತವೆ?', 'ml-IN': 'നിലവിലുള്ള ക്ഷേമ പോർട്ടലുകൾ യഥാർത്ഥത്തിൽ ആരിലേക്കാണ് എത്തുന്നത്?', 'bn-IN': 'বিদ্যমান কল্যাণ পোর্টাল আসলে কাদের কাছে পৌঁছায়?', 'gu-IN': 'હાલના કલ્યાણ પોર્ટલ ખરેખર કોના સુધી પહોંચે છે?', 'pa-IN': 'ਮੌਜੂਦਾ ਭਲਾਈ ਪੋਰਟਲ ਅਸਲ ਵਿੱਚ ਕਿਸ ਤੱਕ ਪਹੁੰਚਦੇ ਹਨ?' } as Str,
    chartSub: { 'hi-IN': 'पात्र जनसंख्या का % सक्रिय मासिक उपयोगकर्ता · भारत 2024', 'mr-IN': 'पात्र लोकसंख्येच्या % सक्रिय मासिक वापरकर्ते · भारत 2024', 'en-IN': 'Active monthly users as % of eligible population · India 2024', 'ta-IN': 'தகுதியான மக்கள்தொகையில் % செயலில் உள்ள மாதாந்திர பயனர்கள் · இந்தியா 2024', 'te-IN': 'అర్హత గల జనాభాలో % క్రియాశీల నెలవారీ వినియోగదారులు · భారతదేశం 2024', 'kn-IN': 'ಅರ್ಹ ಜನಸಂಖ್ಯೆಯ % ಸಕ್ರಿಯ ಮಾಸಿಕ ಬಳಕೆದಾರರು · ಭಾರತ 2024', 'ml-IN': 'യോഗ്യരായ ജനസംഖ്യയുടെ % സജീവ പ്രതിമാസ ഉപയോക്താക്കൾ · ഇന്ത്യ 2024', 'bn-IN': 'যোগ্য জনসংখ্যার % সক্রিয় মাসিক ব্যবহারকারী · ভারত ২০২৪', 'gu-IN': 'પાત્ર વસ્તીના % સક્રિય માસિક વપરાશકર્તાઓ · ભારત 2024', 'pa-IN': 'ਯੋਗ ਆਬਾਦੀ ਦਾ % ਸਰਗਰਮ ਮਾਸਿਕ ਉਪਭੋਗਤਾ · ਭਾਰਤ 2024' } as Str,
    barUrban: { 'hi-IN': 'शहरी शिक्षित उपयोगकर्ता', 'mr-IN': 'शहरी सुशिक्षित वापरकर्ते', 'en-IN': 'Urban educated users', 'ta-IN': 'நகர்ப்புற படித்த பயனர்கள்', 'te-IN': 'పట్టణ విద్యావంతులైన వినియోగదారులు', 'kn-IN': 'ನಗರ ವಿದ್ಯಾವಂತ ಬಳಕೆದಾರರು', 'ml-IN': 'നഗര വിദ്യാസമ്പന്നരായ ഉപയോക്താക്കൾ', 'bn-IN': 'শহুরে শিক্ষিত ব্যবহারকারী', 'gu-IN': 'શહેરી શિક્ષિત વપરાશકર્તાઓ', 'pa-IN': 'ਸ਼ਹਿਰੀ ਪੜ੍ਹੇ-ਲਿਖੇ ਉਪਭੋਗਤਾ' } as Str,
    barSemiUrban: { 'hi-IN': 'अर्ध-शहरी उपयोगकर्ता', 'mr-IN': 'निमशहरी वापरकर्ते', 'en-IN': 'Semi-urban users', 'ta-IN': 'அரை-நகர்ப்புற பயனர்கள்', 'te-IN': 'సెమీ-అర్బన్ వినియోగదారులు', 'kn-IN': 'ಅರೆ-ನಗರ ಬಳಕೆದಾರರು', 'ml-IN': 'അർദ്ധ-നഗര ഉപയോക്താക്കൾ', 'bn-IN': 'আধা-শহুরে ব্যবহারকারী', 'gu-IN': 'અર્ધ-શહેરી વપરાશકર્તાઓ', 'pa-IN': 'ਅਰਧ-ਸ਼ਹਿਰੀ ਉਪਭੋਗਤਾ' } as Str,
    barRural: { 'hi-IN': 'ग्रामीण उपयोगकर्ता — मुख्य लाभार्थी', 'mr-IN': 'ग्रामीण वापरकर्ते — प्रमुख लाभार्थी', 'en-IN': 'Rural users — primary beneficiaries', 'ta-IN': 'கிராமப்புற பயனர்கள் — முதன்மை பயனாளிகள்', 'te-IN': 'గ్రామీణ వినియోగదారులు — ప్రధాన లబ్ధిదారులు', 'kn-IN': 'ಗ್ರಾಮೀಣ ಬಳಕೆದಾರರು — ಪ್ರಮುಖ ಫಲಾನುಭವಿಗಳು', 'ml-IN': 'ഗ്രാമീണ ഉപയോക്താക്കൾ — പ്രാഥമിക ഗുണഭോക്താക്കൾ', 'bn-IN': 'গ্রামীণ ব্যবহারকারী — মূল সুবিধাভোগী', 'gu-IN': 'ગ્રામીણ વપરાશકર્તાઓ — મુખ્ય લાભાર્થીઓ', 'pa-IN': 'ਪੇਂਡੂ ਉਪਭੋਗਤਾ — ਮੁੱਖ ਲਾਭਪਾਤਰੀ' } as Str,
    barRuralVoice: { 'hi-IN': 'आवाज़ से सहज ग्रामीण उपयोगकर्ता', 'mr-IN': 'आवाजाने सोयीस्कर ग्रामीण वापरकर्ते', 'en-IN': 'Rural users comfortable with voice', 'ta-IN': 'குரலில் வசதியான கிராமப்புற பயனர்கள்', 'te-IN': 'వాయిస్‌తో సౌకర్యంగా ఉండే గ్రామీణ వినియోగదారులు', 'kn-IN': 'ಧ್ವನಿಯೊಂದಿಗೆ ಆರಾಮದಾಯಕ ಗ್ರಾಮೀಣ ಬಳಕೆದಾರರು', 'ml-IN': 'വോയ്സിൽ സൗകര്യമുള്ള ഗ്രാമീണ ഉപയോക്താക്കൾ', 'bn-IN': 'ভয়েসে স্বাচ্ছন্দ্যবোধ করা গ্রামীণ ব্যবহারকারী', 'gu-IN': 'વૉઇસથી આરામદાયક ગ્રામીણ વપરાશકર્તાઓ', 'pa-IN': 'ਆਵਾਜ਼ ਨਾਲ ਸਹਿਜ ਪੇਂਡੂ ਉਪਭੋਗਤਾ' } as Str,
    barVoiceSearch: { 'hi-IN': 'रोज़ आवाज़ खोज उपयोग करने वाले भारतीय', 'mr-IN': 'दररोज आवाज शोध वापरणारे भारतीय', 'en-IN': 'Indians using voice search daily', 'ta-IN': 'தினமும் குரல் தேடலைப் பயன்படுத்தும் இந்தியர்கள்', 'te-IN': 'ప్రతిరోజూ వాయిస్ శోధన ఉపయోగించే భారతీయులు', 'kn-IN': 'ಪ್ರತಿದಿನ ಧ್ವನಿ ಹುಡುಕಾಟ ಬಳಸುವ ಭಾರತೀಯರು', 'ml-IN': 'ദിവസവും വോയ്സ് സെർച്ച് ഉപയോഗിക്കുന്ന ഇന്ത്യക്കാർ', 'bn-IN': 'প্রতিদিন ভয়েস সার্চ ব্যবহারকারী ভারতীয়', 'gu-IN': 'રોજ વૉઇસ સર્ચ વાપરતા ભારતીયો', 'pa-IN': 'ਰੋਜ਼ ਆਵਾਜ਼ ਖੋਜ ਵਰਤਣ ਵਾਲੇ ਭਾਰਤੀ' } as Str,
    calloutTitle: { 'hi-IN': 'सीधे शब्दों में अंतर', 'mr-IN': 'सोप्या शब्दांत तफावत', 'en-IN': 'The gap in plain terms', 'ta-IN': 'எளிய வார்த்தைகளில் இடைவெளி', 'te-IN': 'సాధారణ మాటల్లో అంతరం', 'kn-IN': 'ಸರಳ ಪದಗಳಲ್ಲಿ ಅಂತರ', 'ml-IN': 'ലളിതമായ വാക്കുകളിൽ വിടവ്', 'bn-IN': 'সহজ ভাষায় ব্যবধান', 'gu-IN': 'સાદા શબ્દોમાં તફાવત', 'pa-IN': 'ਸਧਾਰਨ ਸ਼ਬਦਾਂ ਵਿੱਚ ਪਾੜਾ' } as Str,
    calloutBoldPart: { 'hi-IN': 'ग्रामीण नागरिक अधिकांश कल्याण योजनाओं के मुख्य इच्छित लाभार्थी हैं', 'mr-IN': 'ग्रामीण नागरिक बहुतेक कल्याण योजनांचे मुख्य इच्छित लाभार्थी आहेत', 'en-IN': 'Rural citizens are the primary intended beneficiaries of most welfare schemes', 'ta-IN': 'கிராமப்புற குடிமக்கள் பெரும்பாலான நலத்திட்டங்களின் முதன்மையான நோக்கம் கொண்ட பயனாளிகள்', 'te-IN': 'గ్రామీణ పౌరులు చాలా సంక్షేమ పథకాల ప్రధాన ఉద్దేశిత లబ్ధిదారులు', 'kn-IN': 'ಗ್ರಾಮೀಣ ನಾಗರಿಕರು ಹೆಚ್ಚಿನ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳ ಪ್ರಾಥಮಿಕ ಉದ್ದೇಶಿತ ಫಲಾನುಭವಿಗಳು', 'ml-IN': 'ഗ്രാമീണ പൗരന്മാരാണ് മിക്ക ക്ഷേമ പദ്ധതികളുടെയും പ്രാഥമിക ലക്ഷ്യ ഗുണഭോക്താക്കൾ', 'bn-IN': 'গ্রামীণ নাগরিকরা বেশিরভাগ কল্যাণ প্রকল্পের প্রধান লক্ষ্য সুবিধাভোগী', 'gu-IN': 'ગ્રામીણ નાગરિકો મોટાભાગની કલ્યાણ યોજનાઓના મુખ્ય ઇચ્છિત લાભાર્થીઓ છે', 'pa-IN': 'ਪੇਂਡੂ ਨਾਗਰਿਕ ਜ਼ਿਆਦਾਤਰ ਭਲਾਈ ਯੋਜਨਾਵਾਂ ਦੇ ਮੁੱਖ ਇਰਾਦਾ ਲਾਭਪਾਤਰੀ ਹਨ' } as Str,
    calloutRest: { 'hi-IN': '— फिर भी मौजूदा डिजिटल पोर्टल उनमें से केवल 9% तक पहुंचते हैं। SuvidhaAI उस 91% के लिए बनाया गया है जिन तक मौजूदा उपकरण नहीं पहुंचे।', 'mr-IN': '— तरीही सध्याचे डिजिटल पोर्टल त्यांच्यापैकी फक्त 9% पर्यंत पोहोचतात. SuvidhaAI त्या 91% साठी बनवले आहे ज्यांच्यापर्यंत सध्याची साधने पोहोचली नाहीत.', 'en-IN': '— yet existing digital portals reach only 9% of them. SuvidhaAI is built for the 91% that existing tools have not reached.', 'ta-IN': '— இருந்தும் தற்போதைய டிஜிட்டல் போர்டல்கள் அவர்களில் 9% மட்டுமே சென்றடைகின்றன. தற்போதைய கருவிகள் சென்றடையாத 91% பேருக்காக SuvidhaAI உருவாக்கப்பட்டுள்ளது.', 'te-IN': '— అయినప్పటికీ ప్రస్తుత డిజిటల్ పోర్టళ్లు వారిలో 9% మందిని మాత్రమే చేరుకుంటాయి. ప్రస్తుత సాధనాలు చేరుకోని 91% మంది కోసం SuvidhaAI నిర్మించబడింది.', 'kn-IN': '— ಆದರೂ ಇರುವ ಡಿಜಿಟಲ್ ಪೋರ್ಟಲ್‌ಗಳು ಅವರಲ್ಲಿ ಕೇವಲ 9% ಅನ್ನು ತಲುಪುತ್ತವೆ. ಇರುವ ಸಾಧನಗಳು ತಲುಪದ 91% ಗಾಗಿ SuvidhaAI ನಿರ್ಮಿಸಲಾಗಿದೆ.', 'ml-IN': '— എന്നിട്ടും നിലവിലുള്ള ഡിജിറ്റൽ പോർട്ടലുകൾ അവരിൽ 9% മാത്രമേ എത്തുന്നുള്ളൂ. നിലവിലുള്ള ഉപകരണങ്ങൾ എത്താത്ത 91% പേർക്കായി SuvidhaAI നിർമ്മിച്ചതാണ്.', 'bn-IN': '— তবুও বিদ্যমান ডিজিটাল পোর্টাল তাদের মধ্যে মাত্র ৯% পর্যন্ত পৌঁছায়। SuvidhaAI সেই ৯১% এর জন্য তৈরি যাদের কাছে বিদ্যমান সরঞ্জাম পৌঁছায়নি।', 'gu-IN': '— તેમ છતાં હાલના ડિજિટલ પોર્ટલ તેમાંથી ફક્ત 9% સુધી પહોંચે છે. SuvidhaAI તે 91% માટે બનાવવામાં આવ્યું છે જેમના સુધી હાલના સાધનો પહોંચ્યા નથી.', 'pa-IN': '— ਫਿਰ ਵੀ ਮੌਜੂਦਾ ਡਿਜੀਟਲ ਪੋਰਟਲ ਉਹਨਾਂ ਵਿੱਚੋਂ ਸਿਰਫ਼ 9% ਤੱਕ ਪਹੁੰਚਦੇ ਹਨ। SuvidhaAI ਉਸ 91% ਲਈ ਬਣਾਇਆ ਗਿਆ ਹੈ ਜਿਨ੍ਹਾਂ ਤੱਕ ਮੌਜੂਦਾ ਸਾਧਨ ਨਹੀਂ ਪਹੁੰਚੇ।' } as Str,

    howTag: { 'hi-IN': 'चरण दर चरण', 'mr-IN': 'टप्प्याटप्प्याने', 'en-IN': 'Step by step', 'ta-IN': 'படிப்படியாக', 'te-IN': 'దశలవారీగా', 'kn-IN': 'ಹಂತ ಹಂತವಾಗಿ', 'ml-IN': 'ഘട്ടം ഘട്ടമായി', 'bn-IN': 'ধাপে ধাপে', 'gu-IN': 'પગલું દર પગલું', 'pa-IN': 'ਕਦਮ ਦਰ ਕਦਮ' } as Str,
    howHeading: { 'hi-IN': '3 मिनट से कम में भ्रम से स्पष्टता तक', 'mr-IN': '3 मिनिटांपेक्षा कमी वेळात गोंधळापासून स्पष्टतेपर्यंत', 'en-IN': 'From confusion to clarity in under 3 minutes', 'ta-IN': '3 நிமிடங்களுக்குள் குழப்பத்திலிருந்து தெளிவுக்கு', 'te-IN': '3 నిమిషాల కంటే తక్కువ సమయంలో గందరగోళం నుండి స్పష్టతకు', 'kn-IN': '3 ನಿಮಿಷಗಳಿಗಿಂತ ಕಡಿಮೆ ಅವಧಿಯಲ್ಲಿ ಗೊಂದಲದಿಂದ ಸ್ಪಷ್ಟತೆಗೆ', 'ml-IN': '3 മിനിറ്റിനുള്ളിൽ ആശയക്കുഴപ്പത്തിൽ നിന്ന് വ്യക്തതയിലേക്ക്', 'bn-IN': '৩ মিনিটেরও কম সময়ে বিভ্রান্তি থেকে স্পষ্টতায়', 'gu-IN': '3 મિનિટથી ઓછા સમયમાં મૂંઝવણથી સ્પષ્ટતા સુધી', 'pa-IN': '3 ਮਿੰਟ ਤੋਂ ਘੱਟ ਵਿੱਚ ਉਲਝਣ ਤੋਂ ਸਪਸ਼ਟਤਾ ਤੱਕ' } as Str,
    howSub: {
      'hi-IN': 'SuvidhaAI आपको हर चरण में मार्गदर्शन करता है — यह न जानने से कि आप किस के लिए पात्र हैं, पूरी तरह तैयार होकर CSC में जाने तक।',
      'mr-IN': 'SuvidhaAI तुम्हाला प्रत्येक टप्प्यात मार्गदर्शन करते — तुम्ही कशासाठी पात्र आहात हे माहीत नसण्यापासून, पूर्ण तयारीनिशी CSC मध्ये जाण्यापर्यंत.',
      'en-IN': 'SuvidhaAI guides you through every step — from not knowing what you qualify for, to walking into a CSC fully prepared.',
      'ta-IN': 'நீங்கள் எதற்குத் தகுதியுடையவர் என்று தெரியாததிலிருந்து, முழுமையாகத் தயாராகி CSC-க்குள் நுழையும் வரை — SuvidhaAI ஒவ்வொரு படியிலும் உங்களை வழிநடத்துகிறது.',
      'te-IN': 'మీరు దేనికి అర్హులో తెలియకపోవడం నుండి, పూర్తిగా సిద్ధమై CSCలోకి వెళ్లేవరకు — SuvidhaAI ప్రతి దశలో మిమ్మల్ని మార్గనిర్దేశం చేస్తుంది.',
      'kn-IN': 'ನೀವು ಯಾವುದಕ್ಕೆ ಅರ್ಹರು ಎಂದು ತಿಳಿಯದಿರುವುದರಿಂದ, ಸಂಪೂರ್ಣ ಸಿದ್ಧರಾಗಿ CSC ಗೆ ಹೋಗುವವರೆಗೆ — SuvidhaAI ಪ್ರತಿ ಹಂತದಲ್ಲೂ ನಿಮ್ಮನ್ನು ಮಾರ್ಗದರ್ಶನ ಮಾಡುತ್ತದೆ.',
      'ml-IN': 'നിങ്ങൾക്ക് എന്തിന് അർഹതയുണ്ടെന്ന് അറിയാത്തതിൽ നിന്ന്, പൂർണ്ണമായി തയ്യാറായി CSC-യിലേക്ക് നടക്കുന്നത് വരെ — SuvidhaAI ഓരോ ഘട്ടത്തിലും നിങ്ങളെ നയിക്കുന്നു.',
      'bn-IN': 'আপনি কীসের জন্য যোগ্য তা না জানা থেকে, সম্পূর্ণ প্রস্তুত হয়ে CSC-তে যাওয়া পর্যন্ত — SuvidhaAI প্রতিটি ধাপে আপনাকে গাইড করে।',
      'gu-IN': 'તમે શેના માટે પાત્ર છો તે ન જાણવાથી લઈને, સંપૂર્ણ તૈયાર થઈને CSC માં જવા સુધી — SuvidhaAI તમને દરેક પગલામાં માર્ગદર્શન આપે છે.',
      'pa-IN': 'ਤੁਸੀਂ ਕਿਸ ਲਈ ਯੋਗ ਹੋ ਇਹ ਨਾ ਜਾਣਨ ਤੋਂ ਲੈ ਕੇ, ਪੂਰੀ ਤਰ੍ਹਾਂ ਤਿਆਰ ਹੋ ਕੇ CSC ਵਿੱਚ ਜਾਣ ਤੱਕ — SuvidhaAI ਤੁਹਾਨੂੰ ਹਰ ਕਦਮ ਵਿੱਚ ਮਾਰਗਦਰਸ਼ਨ ਕਰਦਾ ਹੈ।',
    } as Str,
    step1Title: { 'hi-IN': 'बोलें या टाइप करें', 'mr-IN': 'बोला किंवा टाइप करा', 'en-IN': 'Speak or Type', 'ta-IN': 'பேசுங்கள் அல்லது தட்டச்சு செய்யுங்கள்', 'te-IN': 'మాట్లాడండి లేదా టైప్ చేయండి', 'kn-IN': 'ಮಾತನಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ', 'ml-IN': 'സംസാരിക്കുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക', 'bn-IN': 'বলুন বা টাইপ করুন', 'gu-IN': 'બોલો અથવા ટાઇપ કરો', 'pa-IN': 'ਬੋਲੋ ਜਾਂ ਟਾਈਪ ਕਰੋ' } as Str,
    step1Desc: { 'hi-IN': 'हिंदी, मराठी, या अंग्रेज़ी में बताएं कि आप कौन हैं। कोई ड्रॉपडाउन नहीं, कोई फॉर्म नहीं। बस स्वाभाविक रूप से बोलें।', 'mr-IN': 'हिंदी, मराठी किंवा इंग्रजीत सांगा तुम्ही कोण आहात. कोणतेही ड्रॉपडाउन नाही, फॉर्म नाही. फक्त नैसर्गिकपणे बोला.', 'en-IN': 'Say who you are in Hindi, Marathi, or English. No dropdowns, no forms. Just speak naturally.', 'ta-IN': 'உங்கள் மொழியில் நீங்கள் யார் என்று சொல்லுங்கள். ட்ராப்டவுன் இல்லை, படிவங்கள் இல்லை. இயல்பாகப் பேசுங்கள்.', 'te-IN': 'మీ భాషలో మీరు ఎవరో చెప్పండి. డ్రాప్‌డౌన్‌లు లేవు, ఫారమ్‌లు లేవు. సహజంగా మాట్లాడండి.', 'kn-IN': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ನೀವು ಯಾರೆಂದು ಹೇಳಿ. ಡ್ರಾಪ್‌ಡೌನ್‌ಗಳಿಲ್ಲ, ಫಾರ್ಮ್‌ಗಳಿಲ್ಲ. ಸಹಜವಾಗಿ ಮಾತನಾಡಿ.', 'ml-IN': 'നിങ്ങളുടെ ഭാഷയിൽ നിങ്ങൾ ആരാണെന്ന് പറയുക. ഡ്രോപ്ഡൗണുകളില്ല, ഫോമുകളില്ല. സ്വാഭാവികമായി സംസാരിക്കുക.', 'bn-IN': 'আপনার ভাষায় বলুন আপনি কে। কোনো ড্রপডাউন নেই, ফর্ম নেই। শুধু স্বাভাবিকভাবে বলুন।', 'gu-IN': 'તમારી ભાષામાં કહો તમે કોણ છો. કોઈ ડ્રોપડાઉન નહીં, ફોર્મ નહીં. ફક્ત સ્વાભાવિક રીતે બોલો.', 'pa-IN': 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਦੱਸੋ ਤੁਸੀਂ ਕੌਣ ਹੋ। ਕੋਈ ਡ੍ਰੌਪਡਾਊਨ ਨਹੀਂ, ਫਾਰਮ ਨਹੀਂ। ਬਸ ਕੁਦਰਤੀ ਤੌਰ ਤੇ ਬੋਲੋ।' } as Str,
    step2Title: { 'hi-IN': 'AI 500+ योजनाएं स्कैन करता है', 'mr-IN': 'AI 500+ योजना स्कॅन करते', 'en-IN': 'AI Scans 500+ Schemes', 'ta-IN': 'AI 500+ திட்டங்களை ஸ்கேன் செய்கிறது', 'te-IN': 'AI 500+ పథకాలను స్కాన్ చేస్తుంది', 'kn-IN': 'AI 500+ ಯೋಜನೆಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತದೆ', 'ml-IN': 'AI 500+ പദ്ധതികൾ സ്കാൻ ചെയ്യുന്നു', 'bn-IN': 'AI 500+ প্রকল্প স্ক্যান করে', 'gu-IN': 'AI 500+ યોજનાઓ સ્કેન કરે છે', 'pa-IN': 'AI 500+ ਯੋਜਨਾਵਾਂ ਸਕੈਨ ਕਰਦਾ ਹੈ' } as Str,
    step2Desc: { 'hi-IN': 'हम आपकी प्रोफ़ाइल स्वचालित रूप से निकालते हैं और आपको हर केंद्र और राज्य सरकार योजना से मिलाते हैं।', 'mr-IN': 'आम्ही तुमची प्रोफाइल आपोआप काढतो आणि तुम्हाला प्रत्येक केंद्र आणि राज्य सरकार योजनेशी जुळवतो.', 'en-IN': 'We extract your profile automatically and match you against every central and state government scheme.', 'ta-IN': 'உங்கள் சுயவிவரத்தை தானாகவே பிரித்தெடுத்து, ஒவ்வொரு மத்திய மற்றும் மாநில அரசு திட்டத்திற்கும் உங்களைப் பொருத்துகிறோம்.', 'te-IN': 'మేము మీ ప్రొఫైల్‌ను స్వయంచాలకంగా సేకరించి, ప్రతి కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకంతో మిమ్మల్ని జతచేస్తాము.', 'kn-IN': 'ನಾವು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊರತೆಗೆದು, ಪ್ರತಿ ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರಿ ಯೋಜನೆಯೊಂದಿಗೆ ನಿಮ್ಮನ್ನು ಹೊಂದಿಸುತ್ತೇವೆ.', 'ml-IN': 'ഞങ്ങൾ നിങ്ങളുടെ പ്രൊഫൈൽ യാന്ത്രികമായി വേർതിരിച്ചെടുത്ത്, ഓരോ കേന്ദ്ര, സംസ്ഥാന സർക്കാർ പദ്ധതിയുമായി നിങ്ങളെ പൊരുത്തപ്പെടുത്തുന്നു.', 'bn-IN': 'আমরা আপনার প্রোফাইল স্বয়ংক্রিয়ভাবে বের করি এবং আপনাকে প্রতিটি কেন্দ্রীয় ও রাজ্য সরকারি প্রকল্পের সাথে মিলিয়ে দিই।', 'gu-IN': 'અમે તમારી પ્રોફાઇલ આપમેળે કાઢીએ છીએ અને તમને દરેક કેન્દ્ર અને રાજ્ય સરકારની યોજના સાથે મેચ કરીએ છીએ.', 'pa-IN': 'ਅਸੀਂ ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਆਪਣੇ ਆਪ ਕੱਢਦੇ ਹਾਂ ਅਤੇ ਤੁਹਾਨੂੰ ਹਰ ਕੇਂਦਰ ਅਤੇ ਰਾਜ ਸਰਕਾਰੀ ਯੋਜਨਾ ਨਾਲ ਮੇਲ ਖਾਂਦੇ ਹਾਂ।' } as Str,
    step3Title: { 'hi-IN': 'देखें आप किसके लिए पात्र हैं', 'mr-IN': 'तुम्ही कशासाठी पात्र आहात ते पहा', 'en-IN': 'See What You Qualify For', 'ta-IN': 'நீங்கள் எதற்குத் தகுதியுடையவர் என்று பாருங்கள்', 'te-IN': 'మీరు దేనికి అర్హులో చూడండి', 'kn-IN': 'ನೀವು ಯಾವುದಕ್ಕೆ ಅರ್ಹರು ಎಂದು ನೋಡಿ', 'ml-IN': 'നിങ്ങൾക്ക് എന്തിന് അർഹതയുണ്ടെന്ന് കാണുക', 'bn-IN': 'আপনি কীসের জন্য যোগ্য তা দেখুন', 'gu-IN': 'તમે શેના માટે પાત્ર છો તે જુઓ', 'pa-IN': 'ਦੇਖੋ ਤੁਸੀਂ ਕਿਸ ਲਈ ਯੋਗ ਹੋ' } as Str,
    step3Desc: { 'hi-IN': 'हर परिणाम स्पष्ट रूप से बताता है: पात्र, संभवतः पात्र, या अपात्र — सरल-भाषा स्पष्टीकरण के साथ।', 'mr-IN': 'प्रत्येक निकाल स्पष्टपणे सांगतो: पात्र, कदाचित पात्र, किंवा अपात्र — सोप्या भाषेतील स्पष्टीकरणासह.', 'en-IN': 'Each result tells you clearly: Eligible, Maybe Eligible, or Not Eligible — with a plain-language explanation.', 'ta-IN': 'ஒவ்வொரு முடிவும் தெளிவாகக் கூறுகிறது: தகுதி, ஒருவேளை தகுதி, அல்லது தகுதியற்றது — எளிய மொழி விளக்கத்துடன்.', 'te-IN': 'ప్రతి ఫలితం స్పష్టంగా చెబుతుంది: అర్హత, బహుశా అర్హత, లేదా అనర్హత — సాధారణ భాషలో వివరణతో.', 'kn-IN': 'ಪ್ರತಿ ಫಲಿತಾಂಶವು ಸ್ಪಷ್ಟವಾಗಿ ಹೇಳುತ್ತದೆ: ಅರ್ಹ, ಬಹುಶಃ ಅರ್ಹ, ಅಥವಾ ಅನರ್ಹ — ಸರಳ ಭಾಷೆಯ ವಿವರಣೆಯೊಂದಿಗೆ.', 'ml-IN': 'ഓരോ ഫലവും വ്യക്തമായി പറയുന്നു: യോഗ്യൻ, ഒരുപക്ഷേ യോഗ്യൻ, അല്ലെങ്കിൽ യോഗ്യനല്ല — ലളിതമായ ഭാഷാ വിശദീകരണത്തോടെ.', 'bn-IN': 'প্রতিটি ফলাফল স্পষ্টভাবে বলে: যোগ্য, সম্ভবত যোগ্য, বা অযোগ্য — সহজ-ভাষা ব্যাখ্যা সহ।', 'gu-IN': 'દરેક પરિણામ સ્પષ્ટપણે કહે છે: પાત્ર, કદાચ પાત્ર, અથવા અપાત્ર — સરળ-ભાષા સમજૂતી સાથે.', 'pa-IN': 'ਹਰ ਨਤੀਜਾ ਸਪਸ਼ਟ ਤੌਰ ਤੇ ਦੱਸਦਾ ਹੈ: ਯੋਗ, ਸ਼ਾਇਦ ਯੋਗ, ਜਾਂ ਅਯੋਗ — ਸਧਾਰਨ-ਭਾਸ਼ਾ ਵਿਆਖਿਆ ਨਾਲ।' } as Str,
    step4Title: { 'hi-IN': 'आवेदन करने से पहले चेतावनी पाएं', 'mr-IN': 'अर्ज करण्यापूर्वी इशारा मिळवा', 'en-IN': 'Get Warned Before You Apply', 'ta-IN': 'விண்ணப்பிக்கும் முன் எச்சரிக்கை பெறுங்கள்', 'te-IN': 'దరఖాస్తు చేయడానికి ముందు హెచ్చరిక పొందండి', 'kn-IN': 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ಎಚ್ಚರಿಕೆ ಪಡೆಯಿರಿ', 'ml-IN': 'അപേക്ഷിക്കുന്നതിന് മുമ്പ് മുന്നറിയിപ്പ് നേടുക', 'bn-IN': 'আবেদনের আগে সতর্কতা পান', 'gu-IN': 'અરજી કરતા પહેલા ચેતવણી મેળવો', 'pa-IN': 'ਅਰਜ਼ੀ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਚੇਤਾਵਨੀ ਪ੍ਰਾਪਤ ਕਰੋ' } as Str,
    step4Desc: { 'hi-IN': 'हम सामान्य अस्वीकृति कारण दिखाते हैं ताकि आप आवेदन करने से पहले उन्हें ठीक करें — व्यर्थ यात्राओं की बचत।', 'mr-IN': 'आम्ही सामान्य नकार कारणे दाखवतो जेणेकरून तुम्ही अर्ज करण्यापूर्वी ती दुरुस्त करू शकाल — वाया जाणाऱ्या फेऱ्या वाचतील.', 'en-IN': 'We show common rejection reasons so you fix them before applying — saving wasted trips.', 'ta-IN': 'விண்ணப்பிக்கும் முன் அவற்றைச் சரிசெய்ய பொதுவான நிராகரிப்பு காரணங்களைக் காட்டுகிறோம் — வீண் பயணங்களைத் தவிர்க்கிறது.', 'te-IN': 'దరఖాస్తు చేయడానికి ముందు వాటిని సరిదిద్దుకోవడానికి సాధారణ తిరస్కరణ కారణాలను చూపిస్తాము — వృథా ప్రయాణాలను ఆదా చేస్తుంది.', 'kn-IN': 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ಅವುಗಳನ್ನು ಸರಿಪಡಿಸಲು ಸಾಮಾನ್ಯ ತಿರಸ್ಕಾರ ಕಾರಣಗಳನ್ನು ತೋರಿಸುತ್ತೇವೆ — ವ್ಯರ್ಥ ಪ್ರಯಾಣಗಳನ್ನು ಉಳಿಸುತ್ತದೆ.', 'ml-IN': 'അപേക്ഷിക്കുന്നതിന് മുമ്പ് അവ പരിഹരിക്കാൻ സാധാരണ നിരസിക്കൽ കാരണങ്ങൾ ഞങ്ങൾ കാണിക്കുന്നു — പാഴായ യാത്രകൾ ലാഭിക്കുന്നു.', 'bn-IN': 'আমরা সাধারণ প্রত্যাখ্যানের কারণ দেখাই যাতে আপনি আবেদনের আগে তা ঠিক করতে পারেন — অপচয়িত ভ্রমণ বাঁচায়।', 'gu-IN': 'અમે સામાન્ય અસ્વીકાર કારણો બતાવીએ છીએ જેથી તમે અરજી કરતા પહેલા તેને ઠીક કરો — બગડેલી મુસાફરી બચાવે છે.', 'pa-IN': 'ਅਸੀਂ ਆਮ ਅਸਵੀਕਾਰ ਕਾਰਨ ਦਿਖਾਉਂਦੇ ਹਾਂ ਤਾਂ ਜੋ ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਉਹਨਾਂ ਨੂੰ ਠੀਕ ਕਰੋ — ਵਿਅਰਥ ਯਾਤਰਾਵਾਂ ਬਚਾਉਂਦਾ ਹੈ।' } as Str,
    step5Title: { 'hi-IN': 'अपना तैयारी दस्तावेज़ पाएं', 'mr-IN': 'तुमचा तयारी दस्तऐवज मिळवा', 'en-IN': 'Get Your Preparation Document', 'ta-IN': 'உங்கள் தயார்நிலை ஆவணத்தைப் பெறுங்கள்', 'te-IN': 'మీ సన్నద్ధత పత్రాన్ని పొందండి', 'kn-IN': 'ನಿಮ್ಮ ಸಿದ್ಧತಾ ದಾಖಲೆಯನ್ನು ಪಡೆಯಿರಿ', 'ml-IN': 'നിങ്ങളുടെ തയ്യാറെടുപ്പ് രേഖ നേടുക', 'bn-IN': 'আপনার প্রস্তুতি নথি পান', 'gu-IN': 'તમારો તૈયારી દસ્તાવેજ મેળવો', 'pa-IN': 'ਆਪਣਾ ਤਿਆਰੀ ਦਸਤਾਵੇਜ਼ ਪ੍ਰਾਪਤ ਕਰੋ' } as Str,
    step5Desc: { 'hi-IN': 'आपके विवरण के साथ पहले से भरा एक प्रिंट करने योग्य सारांश, ले जाने वाले दस्तावेज़, और कहाँ जाना है — आपकी भाषा में।', 'mr-IN': 'तुमच्या तपशिलांसह आधीच भरलेला छापण्यायोग्य सारांश, सोबत न्यायची कागदपत्रे, आणि कुठे जायचे — तुमच्या भाषेत.', 'en-IN': 'A printable summary with your details pre-filled, documents to carry, and where to go — in your language.', 'ta-IN': 'உங்கள் விவரங்களுடன் முன்பே நிரப்பப்பட்ட அச்சிடக்கூடிய சுருக்கம், எடுத்துச் செல்ல வேண்டிய ஆவணங்கள், எங்கு செல்ல வேண்டும் — உங்கள் மொழியில்.', 'te-IN': 'మీ వివరాలతో ముందుగా నింపిన ప్రింట్ చేయదగిన సారాంశం, తీసుకెళ్లాల్సిన పత్రాలు, ఎక్కడికి వెళ్లాలో — మీ భాషలో.', 'kn-IN': 'ನಿಮ್ಮ ವಿವರಗಳೊಂದಿಗೆ ಮೊದಲೇ ಭರ್ತಿ ಮಾಡಿದ ಮುದ್ರಿಸಬಹುದಾದ ಸಾರಾಂಶ, ಒಯ್ಯಬೇಕಾದ ದಾಖಲೆಗಳು, ಮತ್ತು ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು — ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ.', 'ml-IN': 'നിങ്ങളുടെ വിവരങ്ങൾ മുൻകൂട്ടി പൂരിപ്പിച്ച പ്രിന്റ് ചെയ്യാവുന്ന സംഗ്രഹം, കൊണ്ടുപോകേണ്ട രേഖകൾ, എവിടെ പോകണം — നിങ്ങളുടെ ഭാഷയിൽ.', 'bn-IN': 'আপনার বিবরণ সহ পূর্বে পূরণ করা প্রিন্টযোগ্য সারাংশ, বহন করার নথি, এবং কোথায় যেতে হবে — আপনার ভাষায়।', 'gu-IN': 'તમારી વિગતો સાથે પહેલેથી ભરેલો છાપી શકાય તેવો સારાંશ, લઈ જવાના દસ્તાવેજો, અને ક્યાં જવું — તમારી ભાષામાં.', 'pa-IN': 'ਤੁਹਾਡੇ ਵੇਰਵਿਆਂ ਨਾਲ ਪਹਿਲਾਂ ਤੋਂ ਭਰਿਆ ਪ੍ਰਿੰਟ ਕਰਨ ਯੋਗ ਸਾਰ, ਲਿਜਾਣ ਵਾਲੇ ਦਸਤਾਵੇਜ਼, ਅਤੇ ਕਿੱਥੇ ਜਾਣਾ ਹੈ — ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ।' } as Str,
    step6Title: { 'hi-IN': 'WhatsApp पर शेयर करें', 'mr-IN': 'WhatsApp वर शेअर करा', 'en-IN': 'Share on WhatsApp', 'ta-IN': 'WhatsApp-இல் பகிரவும்', 'te-IN': 'WhatsApp‌లో షేర్ చేయండి', 'kn-IN': 'WhatsApp‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ', 'ml-IN': 'WhatsApp‌ൽ പങ്കിടുക', 'bn-IN': 'WhatsApp‌এ শেয়ার করুন', 'gu-IN': 'WhatsApp પર શેર કરો', 'pa-IN': 'WhatsApp ਤੇ ਸਾਂਝਾ ਕਰੋ' } as Str,
    step6Desc: { 'hi-IN': 'एक टैप आपकी सभी मिलान योजनाओं को WhatsApp पर भेजता है ताकि आपका परिवार या CSC संचालक आवेदन करने में मदद कर सके।', 'mr-IN': 'एक टॅप तुमच्या सर्व जुळलेल्या योजना WhatsApp वर पाठवतो जेणेकरून तुमचे कुटुंब किंवा CSC ऑपरेटर अर्ज करण्यास मदत करू शकेल.', 'en-IN': 'One tap sends all your matched schemes to WhatsApp so your family or CSC operator can help you apply.', 'ta-IN': 'ஒரு தட்டு உங்கள் அனைத்து பொருந்திய திட்டங்களையும் WhatsApp-க்கு அனுப்புகிறது, உங்கள் குடும்பம் அல்லது CSC இயக்குநர் விண்ணப்பிக்க உதவலாம்.', 'te-IN': 'ఒక ట్యాప్ మీ అన్ని సరిపోలిన పథకాలను WhatsApp‌కు పంపుతుంది, తద్వారా మీ కుటుంబం లేదా CSC ఆపరేటర్ దరఖాస్తు చేయడంలో సహాయపడగలరు.', 'kn-IN': 'ಒಂದು ಟ್ಯಾಪ್ ನಿಮ್ಮ ಎಲ್ಲಾ ಹೊಂದಾಣಿಕೆಯಾದ ಯೋಜನೆಗಳನ್ನು WhatsApp‌ಗೆ ಕಳುಹಿಸುತ್ತದೆ ಇದರಿಂದ ನಿಮ್ಮ ಕುಟುಂಬ ಅಥವಾ CSC ನಿರ್ವಾಹಕರು ಅರ್ಜಿ ಸಲ್ಲಿಸಲು ಸಹಾಯ ಮಾಡಬಹುದು.', 'ml-IN': 'ഒറ്റ ടാപ്പ് നിങ്ങളുടെ എല്ലാ പൊരുത്തപ്പെട്ട പദ്ധതികളും WhatsApp‌ലേക്ക് അയയ്ക്കുന്നു, അതിനാൽ നിങ്ങളുടെ കുടുംബത്തിനോ CSC ഓപ്പറേറ്റർക്കോ അപേക്ഷിക്കാൻ സഹായിക്കാം.', 'bn-IN': 'এক ট্যাপ আপনার সমস্ত মিলিত প্রকল্প WhatsApp‌এ পাঠায় যাতে আপনার পরিবার বা CSC অপারেটর আবেদনে সাহায্য করতে পারেন।', 'gu-IN': 'એક ટેપ તમારી બધી મેચ થયેલી યોજનાઓ WhatsApp પર મોકલે છે જેથી તમારું કુટુંબ અથવા CSC ઓપરેટર અરજી કરવામાં મદદ કરી શકે.', 'pa-IN': 'ਇੱਕ ਟੈਪ ਤੁਹਾਡੀਆਂ ਸਾਰੀਆਂ ਮੇਲ ਖਾਂਦੀਆਂ ਯੋਜਨਾਵਾਂ WhatsApp ਤੇ ਭੇਜਦਾ ਹੈ ਤਾਂ ਜੋ ਤੁਹਾਡਾ ਪਰਿਵਾਰ ਜਾਂ CSC ਓਪਰੇਟਰ ਅਰਜ਼ੀ ਦੇਣ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕੇ।' } as Str,

    audienceTag: { 'hi-IN': 'आप कौन हैं उसके आधार पर खोजें', 'mr-IN': 'तुम्ही कोण आहात त्यानुसार शोधा', 'en-IN': 'Find by who you are', 'ta-IN': 'நீங்கள் யார் என்பதன் அடிப்படையில் தேடுங்கள்', 'te-IN': 'మీరు ఎవరో దాని ఆధారంగా వెతకండి', 'kn-IN': 'ನೀವು ಯಾರೆಂಬುದರ ಆಧಾರದ ಮೇಲೆ ಹುಡುಕಿ', 'ml-IN': 'നിങ്ങൾ ആരാണെന്നതിന്റെ അടിസ്ഥാനത്തിൽ കണ്ടെത്തുക', 'bn-IN': 'আপনি কে তার ভিত্তিতে খুঁজুন', 'gu-IN': 'તમે કોણ છો તેના આધારે શોધો', 'pa-IN': 'ਤੁਸੀਂ ਕੌਣ ਹੋ ਦੇ ਆਧਾਰ ਤੇ ਲੱਭੋ' } as Str,
    audienceHeading: { 'hi-IN': 'हर नागरिक। हर योजना।', 'mr-IN': 'प्रत्येक नागरिक. प्रत्येक योजना.', 'en-IN': 'Every citizen. Every scheme.', 'ta-IN': 'ஒவ்வொரு குடிமகனும். ஒவ்வொரு திட்டமும்.', 'te-IN': 'ప్రతి పౌరుడు. ప్రతి పథకం.', 'kn-IN': 'ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕ. ಪ್ರತಿ ಯೋಜನೆ.', 'ml-IN': 'എല്ലാ പൗരനും. എല്ലാ പദ്ധതിയും.', 'bn-IN': 'প্রতিটি নাগরিক। প্রতিটি প্রকল্প।', 'gu-IN': 'દરેક નાગરિક. દરેક યોજના.', 'pa-IN': 'ਹਰ ਨਾਗਰਿਕ। ਹਰ ਯੋਜਨਾ।' } as Str,
    audienceSub: { 'hi-IN': 'अपनी स्थिति चुनें — हम आपको हर योजना दिखाते हैं जिसके आप पात्र हैं, दावा करने के पूर्ण मार्गदर्शन के साथ।', 'mr-IN': 'तुमची परिस्थिती निवडा — आम्ही तुम्हाला तुम्ही पात्र असलेली प्रत्येक योजना संपूर्ण मार्गदर्शनासह दाखवतो.', 'en-IN': 'Select your situation — we show every scheme you qualify for with full guidance to claim it.', 'ta-IN': 'உங்கள் நிலையைத் தேர்ந்தெடுக்கவும் — நீங்கள் தகுதியுள்ள ஒவ்வொரு திட்டத்தையும் முழு வழிகாட்டுதலுடன் காட்டுகிறோம்.', 'te-IN': 'మీ పరిస్థితిని ఎంచుకోండి — మీరు అర్హత పొందిన ప్రతి పథకాన్ని పూర్తి మార్గదర్శకత్వంతో చూపిస్తాము.', 'kn-IN': 'ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ — ನೀವು ಅರ್ಹರಾಗಿರುವ ಪ್ರತಿ ಯೋಜನೆಯನ್ನು ಸಂಪೂರ್ಣ ಮಾರ್ಗದರ್ಶನದೊಂದಿಗೆ ತೋರಿಸುತ್ತೇವೆ.', 'ml-IN': 'നിങ്ങളുടെ സാഹചര്യം തിരഞ്ഞെടുക്കുക — നിങ്ങൾക്ക് അർഹതയുള്ള എല്ലാ പദ്ധതിയും പൂർണ്ണ മാർഗനിർദേശത്തോടെ കാണിക്കുന്നു.', 'bn-IN': 'আপনার পরিস্থিতি নির্বাচন করুন — আমরা আপনার যোগ্য প্রতিটি প্রকল্প সম্পূর্ণ নির্দেশনা সহ দেখাই।', 'gu-IN': 'તમારી પરિસ્થિતિ પસંદ કરો — અમે તમને તમે પાત્ર છો તે દરેક યોજના સંપૂર્ણ માર્ગદર્શન સાથે બતાવીએ છીએ.', 'pa-IN': 'ਆਪਣੀ ਸਥਿਤੀ ਚੁਣੋ — ਅਸੀਂ ਤੁਹਾਨੂੰ ਹਰ ਯੋਜਨਾ ਦਿਖਾਉਂਦੇ ਹਾਂ ਜਿਸ ਲਈ ਤੁਸੀਂ ਯੋਗ ਹੋ, ਪੂਰੇ ਮਾਰਗਦਰਸ਼ਨ ਨਾਲ।' } as Str,
    schemesCount: { 'hi-IN': (n: number) => `${n} योजनाएं`, 'mr-IN': (n: number) => `${n} योजना`, 'en-IN': (n: number) => `${n} SCHEMES`, 'ta-IN': (n: number) => `${n} திட்டங்கள்`, 'te-IN': (n: number) => `${n} పథకాలు`, 'kn-IN': (n: number) => `${n} ಯೋಜನೆಗಳು`, 'ml-IN': (n: number) => `${n} പദ്ധതികൾ`, 'bn-IN': (n: number) => `${n} প্রকল্প`, 'gu-IN': (n: number) => `${n} યોજનાઓ`, 'pa-IN': (n: number) => `${n} ਯੋਜਨਾਵਾਂ` } as StrFn1,
    viewAll: { 'hi-IN': 'सभी योजनाएं देखें', 'mr-IN': 'सर्व योजना पहा', 'en-IN': 'View all schemes', 'ta-IN': 'அனைத்து திட்டங்களையும் காண்க', 'te-IN': 'అన్ని పథకాలను చూడండి', 'kn-IN': 'ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ', 'ml-IN': 'എല്ലാ പദ്ധതികളും കാണുക', 'bn-IN': 'সব প্রকল্প দেখুন', 'gu-IN': 'બધી યોજનાઓ જુઓ', 'pa-IN': 'ਸਾਰੀਆਂ ਯੋਜਨਾਵਾਂ ਵੇਖੋ' } as Str,
    audFarmers: { 'hi-IN': 'किसान', 'mr-IN': 'शेतकरी', 'en-IN': 'Farmers', 'ta-IN': 'விவசாயிகள்', 'te-IN': 'రైతులు', 'kn-IN': 'ರೈತರು', 'ml-IN': 'കർഷകർ', 'bn-IN': 'কৃষক', 'gu-IN': 'ખેડૂતો', 'pa-IN': 'ਕਿਸਾਨ' } as Str,
    audFarmersDesc: { 'hi-IN': 'फसल बीमा, आय सहायता, सोलर पंप, कर्ज़', 'mr-IN': 'पीक विमा, उत्पन्न सहाय्य, सोलर पंप, कर्ज', 'en-IN': 'Crop insurance, income support, solar pumps, credit', 'ta-IN': 'பயிர் காப்பீடு, வருமான உதவி, சோலார் பம்புகள், கடன்', 'te-IN': 'పంట బీమా, ఆదాయ మద్దతు, సోలార్ పంపులు, రుణం', 'kn-IN': 'ಬೆಳೆ ವಿಮೆ, ಆದಾಯ ಬೆಂಬಲ, ಸೌರ ಪಂಪ್‌ಗಳು, ಸಾಲ', 'ml-IN': 'വിള ഇൻഷുറൻസ്, വരുമാന പിന്തുണ, സോളാർ പമ്പുകൾ, വായ്പ', 'bn-IN': 'ফসল বীমা, আয় সহায়তা, সোলার পাম্প, ঋণ', 'gu-IN': 'પાક વીમો, આવક સહાય, સોલર પંપ, લોન', 'pa-IN': 'ਫਸਲ ਬੀਮਾ, ਆਮਦਨ ਸਹਾਇਤਾ, ਸੋਲਰ ਪੰਪ, ਕਰਜ਼ਾ' } as Str,
    audWomen: { 'hi-IN': 'महिलाएं', 'mr-IN': 'महिला', 'en-IN': 'Women', 'ta-IN': 'பெண்கள்', 'te-IN': 'మహిళలు', 'kn-IN': 'ಮಹಿಳೆಯರು', 'ml-IN': 'സ്ത്രീകൾ', 'bn-IN': 'নারী', 'gu-IN': 'મહિલાઓ', 'pa-IN': 'ਔਰਤਾਂ' } as Str,
    audWomenDesc: { 'hi-IN': 'मातृत्व, विधवा पेंशन, LPG, उद्यमिता ऋण', 'mr-IN': 'मातृत्व, विधवा निवृत्तीवेतन, LPG, उद्योजकता कर्ज', 'en-IN': 'Maternity, widow pension, LPG, entrepreneurship loans', 'ta-IN': 'மகப்பேறு, விதவை ஓய்வூதியம், LPG, தொழில்முனைவோர் கடன்', 'te-IN': 'ప్రసూతి, వితంతు పింఛను, LPG, వ్యవస్థాపక రుణాలు', 'kn-IN': 'ಹೆರಿಗೆ, ವಿಧವಾ ಪಿಂಚಣಿ, LPG, ಉದ್ಯಮಶೀಲತಾ ಸಾಲ', 'ml-IN': 'പ്രസവാനുകൂല്യം, വിധവാ പെൻഷൻ, LPG, സംരംഭക വായ്പ', 'bn-IN': 'মাতৃত্ব, বিধবা পেনশন, LPG, উদ্যোক্তা ঋণ', 'gu-IN': 'માતૃત્વ, વિધવા પેન્શન, LPG, ઉદ્યોગસાહસિક લોન', 'pa-IN': 'ਜਣੇਪਾ, ਵਿਧਵਾ ਪੈਨਸ਼ਨ, LPG, ਉੱਦਮਤਾ ਕਰਜ਼ਾ' } as Str,
    audSeniors: { 'hi-IN': 'वरिष्ठ नागरिक', 'mr-IN': 'ज्येष्ठ नागरिक', 'en-IN': 'Senior Citizens', 'ta-IN': 'மூத்த குடிமக்கள்', 'te-IN': 'వృద్ధ పౌరులు', 'kn-IN': 'ಹಿರಿಯ ನಾಗರಿಕರು', 'ml-IN': 'മുതിർന്ന പൗരന്മാർ', 'bn-IN': 'প্রবীণ নাগরিক', 'gu-IN': 'વરિષ્ઠ નાગરિકો', 'pa-IN': 'ਸੀਨੀਅਰ ਨਾਗਰਿਕ' } as Str,
    audSeniorsDesc: { 'hi-IN': 'वृद्धावस्था पेंशन, आयुष्मान स्वास्थ्य कवर, बचत', 'mr-IN': 'वृद्धापकाळ निवृत्तीवेतन, आयुष्मान आरोग्य कवच, बचत', 'en-IN': 'Old age pension, Ayushman health cover, savings', 'ta-IN': 'முதுமை ஓய்வூதியம், ஆயுஷ்மான் சுகாதார காப்பீடு, சேமிப்பு', 'te-IN': 'వృద్ధాప్య పింఛను, ఆయుష్మాన్ ఆరోగ్య కవర్, పొదుపు', 'kn-IN': 'ವೃದ್ಧಾಪ್ಯ ಪಿಂಚಣಿ, ಆಯುಷ್ಮಾನ್ ಆರೋಗ್ಯ ಕವರ್, ಉಳಿತಾಯ', 'ml-IN': 'വാർദ്ധക്യ പെൻഷൻ, ആയുഷ്മാൻ ആരോഗ്യ കവർ, സമ്പാദ്യം', 'bn-IN': 'বার্ধক্য পেনশন, আয়ুষ্মান স্বাস্থ্য কভার, সঞ্চয়', 'gu-IN': 'વૃદ્ધાવસ્થા પેન્શન, આયુષ્માન આરોગ્ય કવર, બચત', 'pa-IN': 'ਬੁਢਾਪਾ ਪੈਨਸ਼ਨ, ਆਯੁਸ਼ਮਾਨ ਸਿਹਤ ਕਵਰ, ਬਚਤ' } as Str,
    audStudents: { 'hi-IN': 'छात्र और युवा', 'mr-IN': 'विद्यार्थी आणि युवक', 'en-IN': 'Students & Youth', 'ta-IN': 'மாணவர்கள் & இளைஞர்கள்', 'te-IN': 'విద్యార్థులు & యువత', 'kn-IN': 'ವಿದ್ಯಾರ್ಥಿಗಳು ಮತ್ತು ಯುವಕರು', 'ml-IN': 'വിദ്യാർത്ഥികളും യുവാക്കളും', 'bn-IN': 'ছাত্র ও যুবক', 'gu-IN': 'વિદ્યાર્થીઓ અને યુવાનો', 'pa-IN': 'ਵਿਦਿਆਰਥੀ ਅਤੇ ਨੌਜਵਾਨ' } as Str,
    audStudentsDesc: { 'hi-IN': 'छात्रवृत्ति, कौशल प्रशिक्षण, इंटर्नशिप, ऋण', 'mr-IN': 'शिष्यवृत्ती, कौशल्य प्रशिक्षण, इंटर्नशिप, कर्ज', 'en-IN': 'Scholarships, skill training, internships, loans', 'ta-IN': 'உதவித்தொகை, திறன் பயிற்சி, பயிற்சி, கடன்', 'te-IN': 'స్కాలర్‌షిప్‌లు, నైపుణ్య శిక్షణ, ఇంటర్న్‌షిప్‌లు, రుణాలు', 'kn-IN': 'ವಿದ್ಯಾರ್ಥಿವೇತನ, ಕೌಶಲ್ಯ ತರಬೇತಿ, ಇಂಟರ್ನ್‌ಶಿಪ್, ಸಾಲಗಳು', 'ml-IN': 'സ്കോളർഷിപ്പ്, നൈപുണ്യ പരിശീലനം, ഇന്റേൺഷിപ്പ്, വായ്പ', 'bn-IN': 'বৃত্তি, দক্ষতা প্রশিক্ষণ, ইন্টার্নশিপ, ঋণ', 'gu-IN': 'શિષ્યવૃત્તિ, કૌશલ્ય તાલીમ, ઇન્ટર્નશિપ, લોન', 'pa-IN': 'ਸਕਾਲਰਸ਼ਿਪ, ਹੁਨਰ ਸਿਖਲਾਈ, ਇੰਟਰਨਸ਼ਿਪ, ਕਰਜ਼ਾ' } as Str,
    audBusiness: { 'hi-IN': 'व्यापार और स्व-रोज़गार', 'mr-IN': 'व्यवसाय आणि स्वयंरोजगार', 'en-IN': 'Business & Self-Employed', 'ta-IN': 'வணிகம் & சுயதொழில்', 'te-IN': 'వ్యాపారం & స్వయం ఉపాధి', 'kn-IN': 'ವ್ಯಾಪಾರ ಮತ್ತು ಸ್ವಯಂ ಉದ್ಯೋಗ', 'ml-IN': 'ബിസിനസ്സും സ്വയം തൊഴിലും', 'bn-IN': 'ব্যবসা ও স্ব-নিযুক্ত', 'gu-IN': 'વ્યવસાય અને સ્વ-રોજગાર', 'pa-IN': 'ਵਪਾਰ ਅਤੇ ਸਵੈ-ਰੁਜ਼ਗਾਰ' } as Str,
    audBusinessDesc: { 'hi-IN': 'मुद्रा ऋण, विक्रेता ऋण, PMEGP अनुदान', 'mr-IN': 'मुद्रा कर्ज, विक्रेता कर्ज, PMEGP अनुदान', 'en-IN': 'Mudra loans, vendor credit, PMEGP grants', 'ta-IN': 'முத்ரா கடன், விற்பனையாளர் கடன், PMEGP மானியம்', 'te-IN': 'ముద్ర రుణాలు, విక్రేత రుణం, PMEGP గ్రాంట్లు', 'kn-IN': 'ಮುದ್ರಾ ಸಾಲ, ಮಾರಾಟಗಾರ ಸಾಲ, PMEGP ಅನುದಾನ', 'ml-IN': 'മുദ്ര വായ്പ, വെണ്ടർ ക്രെഡിറ്റ്, PMEGP ഗ്രാന്റുകൾ', 'bn-IN': 'মুদ্রা ঋণ, বিক্রেতা ঋণ, PMEGP অনুদান', 'gu-IN': 'મુદ્રા લોન, વિક્રેતા ધિરાણ, PMEGP અનુદાન', 'pa-IN': 'ਮੁਦਰਾ ਕਰਜ਼ਾ, ਵਿਕਰੇਤਾ ਕਰਜ਼ਾ, PMEGP ਗ੍ਰਾਂਟ' } as Str,
    audHealth: { 'hi-IN': 'स्वास्थ्य और आवास', 'mr-IN': 'आरोग्य आणि गृहनिर्माण', 'en-IN': 'Health & Housing', 'ta-IN': 'சுகாதாரம் & வீட்டுவசதி', 'te-IN': 'ఆరోగ్యం & గృహనిర్మాణం', 'kn-IN': 'ಆರೋಗ್ಯ ಮತ್ತು ವಸತಿ', 'ml-IN': 'ആരോഗ്യവും പാർപ്പിടവും', 'bn-IN': 'স্বাস্থ্য ও আবাসন', 'gu-IN': 'આરોગ્ય અને આવાસ', 'pa-IN': 'ਸਿਹਤ ਅਤੇ ਰਿਹਾਇਸ਼' } as Str,
    audHealthDesc: { 'hi-IN': 'आयुष्मान स्वास्थ्य कवर, PM आवास योजना, स्वच्छता', 'mr-IN': 'आयुष्मान आरोग्य कवच, PM आवास योजना, स्वच्छता', 'en-IN': 'Ayushman health cover, PM Awas Yojana, sanitation', 'ta-IN': 'ஆயுஷ்மான் சுகாதார காப்பீடு, PM ஆவாஸ் யோஜனா, சுகாதாரம்', 'te-IN': 'ఆయుష్మాన్ ఆరోగ్య కవర్, PM ఆవాస్ యోజన, పారిశుద్ధ్యం', 'kn-IN': 'ಆಯುಷ್ಮಾನ್ ಆರೋಗ್ಯ ಕವರ್, PM ಆವಾಸ್ ಯೋಜನೆ, ನೈರ್ಮಲ್ಯ', 'ml-IN': 'ആയുഷ്മാൻ ആരോഗ്യ കവർ, PM ആവാസ് യോജന, ശുചിത്വം', 'bn-IN': 'আয়ুষ্মান স্বাস্থ্য কভার, PM আবাস যোজনা, স্বাস্থ্যবিধি', 'gu-IN': 'આયુષ્માન આરોગ્ય કવર, PM આવાસ યોજના, સ્વચ્છતા', 'pa-IN': 'ਆਯੁਸ਼ਮਾਨ ਸਿਹਤ ਕਵਰ, PM ਆਵਾਸ ਯੋਜਨਾ, ਸਫਾਈ' } as Str,

    footerInfo: { 'hi-IN': 'भारत सरकार के आधिकारिक पोर्टल से प्राप्त डेटा · हर नागरिक के लिए मुफ्त', 'mr-IN': 'भारत सरकारच्या अधिकृत पोर्टलवरून घेतलेला डेटा · प्रत्येक नागरिकासाठी मोफत', 'en-IN': 'Data sourced from official Government of India portals · Free for every citizen', 'ta-IN': 'இந்திய அரசின் அதிகாரப்பூர்வ போர்டல்களிலிருந்து பெறப்பட்ட தரவு · ஒவ்வொரு குடிமகனுக்கும் இலவசம்', 'te-IN': 'భారత ప్రభుత్వ అధికారిక పోర్టళ్ల నుండి పొందిన డేటా · ప్రతి పౌరుడికి ఉచితం', 'kn-IN': 'ಭಾರತ ಸರ್ಕಾರದ ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ಗಳಿಂದ ಪಡೆದ ಡೇಟಾ · ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕರಿಗೆ ಉಚಿತ', 'ml-IN': 'ഇന്ത്യാ ഗവൺമെന്റിന്റെ ഔദ്യോഗിക പോർട്ടലുകളിൽ നിന്ന് ലഭിച്ച ഡാറ്റ · എല്ലാ പൗരനും സൗജന്യം', 'bn-IN': 'ভারত সরকারের সরকারি পোর্টাল থেকে সংগৃহীত তথ্য · প্রতিটি নাগরিকের জন্য বিনামূল্যে', 'gu-IN': 'ભારત સરકારના સત્તાવાર પોર્ટલમાંથી મેળવેલ ડેટા · દરેક નાગરિક માટે મફત', 'pa-IN': 'ਭਾਰਤ ਸਰਕਾਰ ਦੇ ਅਧਿਕਾਰਤ ਪੋਰਟਲਾਂ ਤੋਂ ਪ੍ਰਾਪਤ ਡਾਟਾ · ਹਰ ਨਾਗਰਿਕ ਲਈ ਮੁਫ਼ਤ' } as Str,
    footerAbout: { 'hi-IN': 'हमारे बारे में', 'mr-IN': 'आमच्याबद्दल', 'en-IN': 'About', 'ta-IN': 'எங்களைப் பற்றி', 'te-IN': 'మా గురించి', 'kn-IN': 'ನಮ್ಮ ಬಗ್ಗೆ', 'ml-IN': 'ഞങ്ങളെക്കുറിച്ച്', 'bn-IN': 'আমাদের সম্পর্কে', 'gu-IN': 'અમારા વિશે', 'pa-IN': 'ਸਾਡੇ ਬਾਰੇ' } as Str,
    footerHelp: { 'hi-IN': 'मदद', 'mr-IN': 'मदत', 'en-IN': 'Help', 'ta-IN': 'உதவி', 'te-IN': 'సహాయం', 'kn-IN': 'ಸಹಾಯ', 'ml-IN': 'സഹായം', 'bn-IN': 'সাহায্য', 'gu-IN': 'મદદ', 'pa-IN': 'ਮਦਦ' } as Str,
    footerPrivacy: { 'hi-IN': 'गोपनीयता', 'mr-IN': 'गोपनीयता', 'en-IN': 'Privacy', 'ta-IN': 'தனியுரிமை', 'te-IN': 'గోప్యత', 'kn-IN': 'ಗೌಪ್ಯತೆ', 'ml-IN': 'സ്വകാര്യത', 'bn-IN': 'গোপনীয়তা', 'gu-IN': 'ગોપનીયતા', 'pa-IN': 'ਗੋਪਨੀਯਤਾ' } as Str,
    footerContact: { 'hi-IN': 'संपर्क करें', 'mr-IN': 'संपर्क', 'en-IN': 'Contact', 'ta-IN': 'தொடர்பு கொள்ளுங்கள்', 'te-IN': 'సంప్రదించండి', 'kn-IN': 'ಸಂಪರ್ಕಿಸಿ', 'ml-IN': 'ബന്ധപ്പെടുക', 'bn-IN': 'যোগাযোগ করুন', 'gu-IN': 'સંપર્ક કરો', 'pa-IN': 'ਸੰਪਰਕ ਕਰੋ' } as Str,

    helpModalTitle: { 'hi-IN': 'मदद और सहायता', 'mr-IN': 'मदत आणि सहाय्य', 'en-IN': 'Help & Support', 'ta-IN': 'உதவி & ஆதரவு', 'te-IN': 'సహాయం & మద్దతు', 'kn-IN': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ', 'ml-IN': 'സഹായവും പിന്തുണയും', 'bn-IN': 'সাহায্য ও সহায়তা', 'gu-IN': 'મદદ અને સહાય', 'pa-IN': 'ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ' } as Str,
    helpModalBody: {
      'hi-IN': 'SuvidhaAI आपको सरकारी योजनाएं खोजने में मदद करता है। सरल मोड में बोलकर खोजें — कोई टाइपिंग या फॉर्म नहीं। फुल मोड में विस्तृत पात्रता जाँच और आवेदन तैयारी करें। दोनों 10 भारतीय भाषाओं में उपलब्ध हैं।',
      'mr-IN': 'SuvidhaAI तुम्हाला सरकारी योजना शोधण्यात मदत करते. सोप्या पद्धतीत बोलून शोधा — टायपिंग किंवा फॉर्म नाही. फुल मोडमध्ये सविस्तर पात्रता तपासणी आणि अर्ज तयारी करा. दोन्ही 10 भारतीय भाषांमध्ये उपलब्ध आहेत.',
      'en-IN': 'SuvidhaAI helps you find government schemes. In Simple Mode, just speak — no typing or forms. In Full Mode, do a detailed eligibility check and application prep. Both are available in 10 Indian languages.',
      'ta-IN': 'SuvidhaAI அரசு திட்டங்களைக் கண்டுபிடிக்க உதவுகிறது. எளிய முறையில் பேசுங்கள் — தட்டச்சு அல்லது படிவங்கள் இல்லை. முழு முறையில் விரிவான தகுதி சரிபார்ப்பு மற்றும் விண்ணப்ப தயாரிப்பு செய்யுங்கள். இரண்டும் 10 இந்திய மொழிகளில் கிடைக்கின்றன.',
      'te-IN': 'SuvidhaAI మీకు ప్రభుత్వ పథకాలను కనుగొనడంలో సహాయపడుతుంది. సరళ మోడ్‌లో మాట్లాడండి — టైపింగ్ లేదా ఫారమ్‌లు లేవు. పూర్తి మోడ్‌లో వివరణాత్మక అర్హత తనిఖీ మరియు దరఖాస్తు తయారీ చేయండి. రెండూ 10 భారతీయ భాషల్లో అందుబాటులో ఉన్నాయి.',
      'kn-IN': 'SuvidhaAI ನಿಮಗೆ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಸರಳ ಮೋಡ್‌ನಲ್ಲಿ ಮಾತನಾಡಿ — ಟೈಪಿಂಗ್ ಅಥವಾ ಫಾರ್ಮ್‌ಗಳಿಲ್ಲ. ಪೂರ್ಣ ಮೋಡ್‌ನಲ್ಲಿ ವಿವರವಾದ ಅರ್ಹತಾ ಪರಿಶೀಲನೆ ಮತ್ತು ಅರ್ಜಿ ತಯಾರಿ ಮಾಡಿ. ಎರಡೂ 10 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಲಭ್ಯವಿದೆ.',
      'ml-IN': 'SuvidhaAI സർക്കാർ പദ്ധതികൾ കണ്ടെത്താൻ നിങ്ങളെ സഹായിക്കുന്നു. ലളിത മോഡിൽ സംസാരിക്കുക — ടൈപ്പിംഗോ ഫോമുകളോ ഇല്ല. ഫുൾ മോഡിൽ വിശദമായ യോഗ്യതാ പരിശോധനയും അപേക്ഷാ തയ്യാറെടുപ്പും നടത്തുക. രണ്ടും 10 ഇന്ത്യൻ ഭാഷകളിൽ ലഭ്യമാണ്.',
      'bn-IN': 'SuvidhaAI আপনাকে সরকারি প্রকল্প খুঁজে পেতে সাহায্য করে। সহজ মোডে বলুন — টাইপিং বা ফর্ম নেই। ফুল মোডে বিস্তারিত যোগ্যতা পরীক্ষা এবং আবেদন প্রস্তুতি করুন। উভয়ই ১০টি ভারতীয় ভাষায় উপলব্ধ।',
      'gu-IN': 'SuvidhaAI તમને સરકારી યોજનાઓ શોધવામાં મદદ કરે છે. સરળ મોડમાં બોલો — ટાઇપિંગ અથવા ફોર્મ નથી. ફુલ મોડમાં વિગતવાર પાત્રતા ચકાસણી અને અરજી તૈયારી કરો. બંને 10 ભારતીય ભાષાઓમાં ઉપલબ્ધ છે.',
      'pa-IN': 'SuvidhaAI ਤੁਹਾਨੂੰ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਲੱਭਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ। ਸਧਾਰਨ ਮੋਡ ਵਿੱਚ ਬੋਲੋ — ਟਾਈਪਿੰਗ ਜਾਂ ਫਾਰਮ ਨਹੀਂ। ਫੁੱਲ ਮੋਡ ਵਿੱਚ ਵਿਸਤ੍ਰਿਤ ਯੋਗਤਾ ਜਾਂਚ ਅਤੇ ਅਰਜ਼ੀ ਤਿਆਰੀ ਕਰੋ। ਦੋਵੇਂ 10 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਉਪਲਬਧ ਹਨ।',
    } as Str,
    helpModalHelplineLabel: { 'hi-IN': 'हेल्पलाइन', 'mr-IN': 'हेल्पलाइन', 'en-IN': 'Helpline', 'ta-IN': 'உதவி எண்', 'te-IN': 'హెల్ప్‌లైన్', 'kn-IN': 'ಸಹಾಯವಾಣಿ', 'ml-IN': 'ഹെൽപ്പ്‌ലൈൻ', 'bn-IN': 'হেল্পলাইন', 'gu-IN': 'હેલ્પલાઇન', 'pa-IN': 'ਹੈਲਪਲਾਈਨ' } as Str,
    helpModalClose: { 'hi-IN': 'बंद करें', 'mr-IN': 'बंद करा', 'en-IN': 'Close', 'ta-IN': 'மூடு', 'te-IN': 'మూసివేయండి', 'kn-IN': 'ಮುಚ್ಚಿ', 'ml-IN': 'അടയ്ക്കുക', 'bn-IN': 'বন্ধ করুন', 'gu-IN': 'બંધ કરો', 'pa-IN': 'ਬੰਦ ਕਰੋ' } as Str,
  },
}
